### PR TITLE
Fixes bug in free surface build for `HydrostaticFreeSurfaceModel`s on a `ConformalCubedSphereGrid`

### LINKED ISSUE #3295: Error in free surface build for `HydrostaticFreeSurfaceModels` on a `ConformalCubedSphereGrid`
```Julia
julia> using Oceananigans

julia> grid = ConformalCubedSphereGrid(; panel_size = (3, 3, 3),
                                         z = (-1, 0),
                                         horizontal_direction_halo = 6)
ConformalCubedSphereGrid{Float64, FullyConnected, FullyConnected, Bounded} partitioned on CPU():
├── grids: 3×3×3 OrthogonalSphericalShellGrid{Float64, FullyConnected, FullyConnected, Bounded} on CPU with 6×6×6 halo and with precomputed metrics
├── partitioning: CubedSpherePartition with (1 region in each panel)
├── connectivity: CubedSphereConnectivity
└── devices: (CPU(), CPU(), CPU(), CPU(), CPU(), CPU())

julia> model = HydrostaticFreeSurfaceModel(; grid, momentum_advection = VectorInvariant())
ERROR: UndefVarError: `rotation_from_panel_index` not defined
Stacktrace:
 [1] with_halo(new_halo::Tuple{Int64, Int64, Int64}, csg::ConformalCubedSphereGrid{Float64, FullyConnected, ....
   @ Oceananigans.MultiRegion ~/Research/OC8.jl/src/MultiRegion/multi_region_cubed_sphere_grid.jl:431
 [2] Oceananigans.Models.HydrostaticFreeSurfaceModels.PCGImplicitFreeSurfaceSolver(grid::ConformalCubedSphereGrid{Float64, ...
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl:47
 [3] build_implicit_step_solver(#unused#::Val{:Default}, grid::ConformalCubedSphereGrid{Float64, ...
   @ Oceananigans.MultiRegion ~/Research/OC8.jl/src/MultiRegion/unified_implicit_free_surface_solver.jl:67
 [4] FreeSurface(free_surface::ImplicitFreeSurface{Nothing, Float64, Nothing, Nothing, Symbol, ...
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl:95
 [5] HydrostaticFreeSurfaceModel(; grid::ConformalCubedSphereGrid{Float64, ...
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:169
 [6] top-level scope
   @ REPL[63]:1
```

cc @siddharthabishnu

### PR DESCRIPTION
**Pull request by navidcy**
Closes  #3295

Before this PR:

```Julia
julia> using Oceananigans

julia> grid = ConformalCubedSphereGrid(; panel_size = (3, 3, 3), z = (-1, 0));

julia> model = HydrostaticFreeSurfaceModel(; grid, momentum_advection = VectorInvariant())
ERROR: UndefVarError: `rotation_from_panel_index` not defined
Stacktrace:
 [1] with_halo(new_halo::Tuple{Int64, Int64, Int64}, csg::ConformalCubedSphereGrid{Float64, FullyConnected, ....
   @ Oceananigans.MultiRegion ~/Research/OC8.jl/src/MultiRegion/multi_region_cubed_sphere_grid.jl:431
 [2] Oceananigans.Models.HydrostaticFreeSurfaceModels.PCGImplicitFreeSurfaceSolver(grid::ConformalCubedSphereGrid{Float64, ...
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl:47
 [3] build_implicit_step_solver(#unused#::Val{:Default}, grid::ConformalCubedSphereGrid{Float64, ...
   @ Oceananigans.MultiRegion ~/Research/OC8.jl/src/MultiRegion/unified_implicit_free_surface_solver.jl:67
 [4] FreeSurface(free_surface::ImplicitFreeSurface{Nothing, Float64, Nothing, Nothing, Symbol, ...
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl:95
 [5] HydrostaticFreeSurfaceModel(; grid::ConformalCubedSphereGrid{Float64, ...
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Research/OC8.jl/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:169
 [6] top-level scope
   @ REPL[63]:1
```

With this PR:

```Julia
julia> using Oceananigans

julia> grid = ConformalCubedSphereGrid(; panel_size = (3, 3, 3), z = (-1, 0));

julia> model = HydrostaticFreeSurfaceModel(; grid, momentum_advection = VectorInvariant())
HydrostaticFreeSurfaceModel{CPU, MultiRegionGrid}(time = 0 seconds, iteration = 0)
├── grid: 3×3×3 ConformalCubedSphereGrid{Float64, FullyConnected, FullyConnected, Bounded} on CPU with 6×6×6 halo
├── timestepper: QuasiAdamsBashforth2TimeStepper
├── tracers: (T, S)
├── closure: Nothing
├── buoyancy: SeawaterBuoyancy with g=9.80665 and LinearEquationOfState(thermal_expansion=0.000167, haline_contraction=0.00078) with ĝ = NegativeZDirection()
├── free surface: ImplicitFreeSurface with gravitational acceleration 9.80665 m s⁻²
│   └── solver: PCGImplicitFreeSurfaceSolver
└── coriolis: Nothing
```

### CODE REVIEW

**Comment by navidcy** [comment]
This is also related to work that started in #3094 but left stale..

File: src/MultiRegion/multi_region_cubed_sphere_grid.jl [hunk 1]
```diff
@@ -424,11 +424,11 @@ function ConformalCubedSphereGrid(filepath::AbstractString, arch::AbstractArchit
...
 end
 
-function with_halo(new_halo, csg::ConformalCubedSphereGrid) 
+function with_halo(new_halo, csg::ConformalCubedSphereGrid)
     region_rotation = []
 
-    for r in 1:length(csg.partition)
-        push!(region_rotation, rotation_from_panel_index(panel_index(r, csg.partition)))
+    for region in 1:length(csg.partition)
+        push!(region_rotation, csg[region].conformal_mapping.rotation)
```
Comment (glwagner) [inline src/MultiRegion/multi_region_cubed_sphere_grid.jl:431]: Is this the key change? What is the issue?

Comment (siddharthabishnu) [reply src/MultiRegion/multi_region_cubed_sphere_grid.jl:431]: The function rotation_from_panel_index is undefined within the code, leading to the error message: "ERROR: LoadError: UndefVarError: rotation_from_panel_index not defined". It's likely that the function's definition was removed in a previous commit. Hence this amendment suggested by @navidcy.

**Review by siddharthabishnu — APPROVED** [review]

File: src/MultiRegion/multi_region_cubed_sphere_grid.jl (hunk 1 above)
Comment (glwagner) [reply src/MultiRegion/multi_region_cubed_sphere_grid.jl:431]: Thanks @siddharthabishnu

Comment (simone-silvestri) [reply src/MultiRegion/multi_region_cubed_sphere_grid.jl:431]: multi-region syntax prefers the definition of a function and the use `@apply_regionally`. We do not want to use loops because of the possibility of data being on different devices

Comment (glwagner) [reply src/MultiRegion/multi_region_cubed_sphere_grid.jl:431]: @simone-silvestri can you be more explicit about the change that is needed?
