### PR TITLE
(0.96.2) Support `BoussinesqEquationOfState` in `NetCDFWriter`

### LINKED ISSUE #4251: Missing method for `default_tracer_attributes` in `NetCDFWriter` when using a `BoussinesqEquationOfState` from SeawaterPolynomails.jl
The following mwe shows that there is no method to save using `NectCDFWriter` if `BuoyancyForce` is using an equation of state from SeawaterPolynomails.jl:

```julia
using Oceananigans, NCDatasets, SeawaterPolynomials

using SeawaterPolynomials: TEOS10EquationOfState

grid = RectilinearGrid(size=(32, 32, 32), extent=(6, 6, 6))
tracers = (:S, :T)
buoyancy = SeawaterBuoyancy(equation_of_state = TEOS10EquationOfState())
model = NonhydrostaticModel(; grid, tracers, buoyancy)
output = NetCDFWriter(model, ("T" => model.tracers.T, "S" => model.tracers.S), 
                        filename = "test.nc", schedule = IterationInterval(1))

ERROR: MethodError: no method matching default_tracer_attributes(::BuoyancyForce{SeawaterBuoyancy{…}, Oceananigans.Grids.NegativeZDirection})
The function `default_tracer_attributes` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  default_tracer_attributes(::Nothing)
   @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/kw9Pz/ext/OceananigansNCDatasetsExt.jl:595
  default_tracer_attributes(::SeawaterBuoyancy)
   @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/kw9Pz/ext/OceananigansNCDatasetsExt.jl:604
  default_tracer_attributes(::BuoyancyForce{<:SeawaterBuoyancy{FT, <:LinearEquationOfState}}) where FT
   @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/kw9Pz/ext/OceananigansNCDatasetsExt.jl:599
  ...

Stacktrace:
 [1] default_output_attributes(model::NonhydrostaticModel{…})
   @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/kw9Pz/ext/OceananigansNCDatasetsExt.jl:610
 [2] initialize_nc_file(model::NonhydrostaticModel{…}, filepath::String, outputs::Dict{…}, schedule::IterationInterval, array_type::Type{…}, indices::Tuple{…}, global_attributes::Dict{…}, output_attributes::Dict{…}, dimensions::Dict{…}, with_halos::Bool, include_grid_metrics::Bool, overwrite_existing::Bool, deflatelevel::Int64, dimension_name_generator::typeof(OceananigansNCDatasetsExt.trilocation_dim_name))
   @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/kw9Pz/ext/OceananigansNCDatasetsExt.jl:1118
 [3] NetCDFWriter(model::NonhydrostaticModel{…}, outputs::Tuple{…}; filename::String, schedule::IterationInterval, grid::RectilinearGrid{…}, dir::String, array_type::Type, indices::Tuple{…}, global_attributes::Dict{…}, output_attributes::Dict{…}, dimensions::Dict{…}, with_halos::Bool, include_grid_metrics::Bool, overwrite_existing::Nothing, verbose::Bool, deflatelevel::Int64, part::Int64, file_splitting::Oceananigans.OutputWriters.NoFileSplitting, dimension_name_generator::typeof(OceananigansNCDatasetsExt.trilocation_dim_name))
   @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/kw9Pz/ext/OceananigansNCDatasetsExt.jl:1036
 [4] top-level scope
   @ ~/Documents/PhD data and code/StaircaseShenanigans/examples/single_interface.jl:44
Some type information was truncated. Use `show(err)` to see complete types.
```

I have a PR coming!

### PR DESCRIPTION
**Pull request by jbisits**
~Still need to add a test.~ 
Added a test that checks that a `NetCDFOutputWriter` is returned when using `BoussinesqEquationOfState` and there is a file at the `NetCDFOutputWriter` 's `filepath`.

Closes #4251

### CODE REVIEW

File: test/test_netcdf_writer.jl [hunk 1]
```diff
@@ -2673,6 +2675,50 @@ function test_netcdf_free_surface_mixed_output(arch)
...
+                           halo = (Hx, Hz),
+                           x = (-Lx, Lx),
+                           z = (-H, 0))
+
+    Boussinesq_eos = (TEOS10EquationOfState(),
+                        RoquetEquationOfState(:Linear),
+                        RoquetEquationOfState(:Cabbeling),
+                        RoquetEquationOfState(:CabbelingThermobaricity),
+                        RoquetEquationOfState(:SecondOrder),
+                        RoquetEquationOfState(:SimplestRealistic))
```
Comment (tomchor) [inline test/test_netcdf_writer.jl:2696]:
```suggestion
    Boussinesq_eos = (TEOS10EquationOfState(),
                      RoquetEquationOfState(:Linear),
                      RoquetEquationOfState(:Cabbeling),
                      RoquetEquationOfState(:CabbelingThermobaricity),
                      RoquetEquationOfState(:SecondOrder),
                      RoquetEquationOfState(:SimplestRealistic))
```

Comment (tomchor) [reply test/test_netcdf_writer.jl:2696]: I don't know that much about different options for equations of state, but does this cover all cases that are currently available? I know this is implicitly tested elsewhere but shouldn't we add a linear EOS there for good measure/completeness?

**Comment by tomchor** [comment]
Nice catch! Thanks! Let's tag a patch version with this, please.

File: test/test_netcdf_writer.jl (hunk 1 above)
Comment (jbisits) [reply test/test_netcdf_writer.jl]: I forgot the the `:Freezing` coefficient set sorry! After that all the options from SeawaterPolynomials.jl are included. Did you mean to add `LinearEquationOfState` from the Oceananigans package?

File: ext/OceananigansNCDatasetsExt.jl [hunk 2]
```diff
@@ -600,9 +603,9 @@ default_tracer_attributes(::BuoyancyForce{<:SeawaterBuoyancy{FT, <:LinearEquatio
     "T" => Dict("long_name" => "Temperature", "units" => "°C"),
     "S" => Dict("long_name" => "Salinity",    "units" => "practical salinity unit (psu)"))
 
-# Assuming TEOS-10 I guess?
-default_tracer_attributes(::SeawaterBuoyancy) = Dict("T" => Dict("long_name" => "Conservative temperature", "units" => "°C"),
-                                                     "S" => Dict("long_name" => "Absolute salinity",        "units" => "g/kg"))
+default_tracer_attributes(::BuoyancyBoussinesqEOSModel) = Dict(
+        "T" => Dict("long_name" => "Conservative temperature", "units" => "°C"),
+        "S" => Dict("long_name" => "Absolute salinity",        "units" => "g/kg"))
```
Comment (tomchor) [inline ext/OceananigansNCDatasetsExt.jl:608]:
```suggestion
default_tracer_attributes(::BuoyancyBoussinesqEOSModel) = Dict("T" => Dict("long_name" => "Conservative temperature", "units" => "°C"),
                                                               "S" => Dict("long_name" => "Absolute salinity",        "units" => "g/kg"))
```

I think this follows closer to the Oceananigans convention.

**Review by tomchor — APPROVED** [review]
Looks good!

**Comment by jbisits** [comment]
@tomchor did you want me to change to 0.96.1 in `Project.toml`?

**Comment by jbisits** [comment]
Also just a question (not for this PR and maybe never). It might be easier to maintain if the main module [OceananigansNCDatasetsExt.jl](https://github.com/CliMA/Oceananigans.jl/blob/main/ext/OceananigansNCDatasetsExt.jl) is broken up into smaller scripts. You can do this by placing OceananigansNCDatasetsExt.jl inside a directory called OceananigansNCDatasetsExt then have e.g.

```julia
module OceananigansNCDatasetsExt

using NCDatasets

using Dates: AbstractTime, UTC, now
using Printf: @sprintf

using Oceananigans.Fields

using Oceananigans: initialize!, prettytime, pretty_filesize, AbstractModel
using Oceananigans.Grids: Center, Face, Flat, AbstractGrid, RectilinearGrid, LatitudeLongitudeGrid, StaticVerticalDiscretization
using Oceananigans.Grids: topology, halo_size, xspacings, yspacings, zspacings, λspacings, φspacings,
                          parent_index_range, ξnodes, ηnodes, rnodes, validate_index, peripheral_node
using Oceananigans.Fields: reduced_dimensions, reduced_location, location
using Oceananigans.AbstractOperations: KernelFunctionOperation
using Oceananigans.Models: ShallowWaterModel, LagrangianParticles
using Oceananigans.ImmersedBoundaries: ImmersedBoundaryGrid, GridFittedBottom, GFBIBG, GridFittedBoundary
using Oceananigans.TimeSteppers: float_or_date_time
using Oceananigans.BuoyancyFormulations: BuoyancyForce, BuoyancyTracer, SeawaterBuoyancy, LinearEquationOfState
using Oceananigans.Utils: TimeInterval, IterationInterval, WallTimeInterval
using Oceananigans.Utils: versioninfo_with_gpu, oceananigans_versioninfo, prettykeys

using Oceananigans.OutputWriters:
    auto_extension,
    output_averaging_schedule,
    show_averaging_schedule,
    AveragedTimeInterval,
    WindowedTimeAverage,
    NoFileSplitting,
    update_file_splitting_schedule!,
    construct_output,
    time_average_outputs,
    restrict_to_interior,
    fetch_output,
    convert_output,
    fetch_and_convert_output,
    show_array_type

import Oceananigans: write_output!
import Oceananigans.OutputWriters: NetCDFWriter

const c = Center()
const f = Face()

include("utils.jl")
include("getgrids.jl")
include("interpolation.jl")

end
```

The names above are just placeholders for demonstration!

**Comment by jbisits** [comment]
Having another look I think my suggestion above would amount to putting each heading section in OceananaigansNCDatasetsExt.jl, i.e. the bits marked with

```julia
####
#### section
####
```

into a different script. But no problem if you prefer as is!

**Comment by glwagner** [comment]
A nice pattern for Extensions is to mirror the module names in Oceananigans, eg 
```julia
module OceanaingansNCDatasetsExt

include("Grids.jl")
using .Grids

include("OutputWriters.jl")
using .OutputWriters

end
```

**Comment by jbisits** [comment]
> @tomchor did you want me to change to 0.96.1 in `Project.toml`?

I did this and changed title of the PR to reflect this.

**Comment by tomchor** [comment]
> > @tomchor did you want me to change to 0.96.1 in `Project.toml`?
> 
> I did this and changed title of the PR to reflect this.

Yes, that's what I meant. Although now I think we need to bump up to 0.96.2 after tests pass.

**Comment by jbisits** [comment]
@tomchor and @navidcy the tests I added now passed so perhaps after update merging with main this PR could be merged (though now patch might need 0.96.3)?

**Comment by glwagner** [comment]
The Reactant tests will hopefully be fixed soon, but we can merge this without them. Let me know if that's what you want and I will do it.
