### PR TITLE
More support for `Flat` dimensions

### LINKED ISSUE #35: Only perform operations as needed depending on model dimension.
E.g. no need to calculate y-derivatives or y-averages, or even evolve v if the model is a 2D xz-slice. But this is low priority as it only affects the already fast 2D and 1D models.

### LINKED ISSUE #902: Eliding differences, interpolation, and `fill_halo_regions` for `Flat` dimensions
The topology of a dimension can be labeled `Flat`. However, this doesn't produce any special behavior. To fully take advantage of this abstraction, we need differences across `Flat` dimensions to return 0:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/Operators/difference_operators.jl#L5-L25

eg

```julia
 @inline δxᶜᵃᵃ(i, j, k, grid::RegularCartesianGrid{FT, Flat}, args...) where FT = zero(FT)
```

etc.

In addition, interpolation should have no effect:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/Operators/interpolation_operators.jl#L12-L32

I think we should probably use `nothing` for boundary conditions in `Flat` dimensions:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/BoundaryConditions/field_boundary_conditions.jl#L17

which will make it easy to elide `fill_halo_regions!`, since we can dispatch on `nothing`.

Finally, we should set halo size to 0 in the grid constructor:

https://github.com/CliMA/Oceananigans.jl/blob/edcedc38c55a9c219514c5234c1a663be03beced/src/Grids/regular_cartesian_grid.jl#L117-L126

### LINKED ISSUE #940: Model immediately turns to `NaN` after 1 time step when grid length is zero along `Flat` dimensions
Might get fixed with #35 and #902 but worth documenting this issue.

I guess you shouldn't need to specify the grid length/extent/domain along `Flat` dimensions, it's assumed to take on one value only. So maybe we should allow for e.g.
```julia
grid = RegularCartesianGrid(topology=(Periodic, Flat, Flat), size=(4, 1, 1), x=(-1, 1), z=2.5)
```

---

```julia
using Oceananigans
grid = RegularCartesianGrid(topology=(Periodic, Flat, Flat), size=(4, 1, 1), x=(-1, 1), y=(0, 0), z=(0, 0))
model = IncompressibleModel(grid=grid)
time_step!(model, 1, euler=true)
interior(model.velocities.u)[:]
```

```
4-element Array{Float64,1}:
 NaN
 NaN
 NaN
 NaN
```

### LINKED ISSUE #1001: Requiring Lz and Nz for two-dimensional grids is a bit counterintuitive
At the moment, to solve equations on a two-dimensional grid one has to provide `Nz=1` and any `Lz` they wish. For example, giving `Lz=2e-16` works pretty well:

```julia
julia> grid = RegularCartesianGrid(size=(128, 128, 1), extent=(2π, 2π, eps(Float64)))
RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 6.283185307179586], y ∈ [0.0, 6.283185307179586], z ∈ [-2.220446049250313e-16, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (128, 128, 1)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (0.04908738521234052, 0.04908738521234052, 2.220446049250313e-16)
```

However, `Lz=0` spits out an error...
```julia
julia> grid = RegularCartesianGrid(size=(128, 128, 1), extent=(2π, 2π, 0))
ERROR: ArgumentError: Elements of extent=(6.283185307179586, 6.283185307179586, 0) must be > 0!
Stacktrace:
 [1] validate_tupled_argument at /Users/navid/Research/Oceananigans.jl/src/Grids/grid_utils.jl:306 [inlined]
 [2] validate_regular_grid_size_and_extent(::Type{T} where T, ::Tuple{Int64,Int64,Int64}, ::Tuple{Float64,Float64,Int64}, ::Tuple{Int64,Int64,Int64}, ::Nothing, ::Nothing, ::Nothing) at /Users/navid/Research/Oceananigans.jl/src/Grids/grid_utils.jl:330
 [3] RegularCartesianGrid(::Type{T} where T; size::Tuple{Int64,Int64,Int64}, x::Nothing, y::Nothing, z::Nothing, extent::Tuple{Float64,Float64,Int64}, topology::Tuple{DataType,DataType,DataType}, halo::Tuple{Int64,Int64,Int64}) at /Users/navid/Research/Oceananigans.jl/src/Grids/regular_cartesian_grid.jl:126
 [4] top-level scope at REPL[33]:1
```

Perhaps it makes sense that there should be a check and each dimension that has extent =0 and number of grid-points =1 should be treated "specially" and bypass the validation at https://github.com/CliMA/Oceananigans.jl/blob/e808a821d78949b0482b8372533e992cabb5d65f/src/Grids/grid_utils.jl#L306?

### PR DESCRIPTION
**Pull request by glwagner**
This PR increases our support for `Flat` dimensions of `RegularCartesianGrid`. When topology in a direction is `Flat`, the halo size is set to 0, the grid size to 1, and halo filling, interpolation, and differences are all elided.

Two new examples in the docstring for `RegularCartesianGrid` illustrate it's use:

* A two-dimenisional, horizontally-periodic grid:

```julia
julia> using Oceananigans

julia> grid = RegularCartesianGrid(size=(32, 32), extent=(2π, 4π), topology=(Periodic, Periodic, Flat))
RegularCartesianGrid{Float64, Periodic, Periodic, Flat}
                   domain: x ∈ [0.0, 6.283185307179586], y ∈ [0.0, 12.566370614359172], z ∈ [0.0, 0.0]
                 topology: (Periodic, Periodic, Flat)
  resolution (Nx, Ny, Nz): (32, 32, 1)
   halo size (Hx, Hy, Hz): (1, 1, 0)
grid spacing (Δx, Δy, Δz): (0.19634954084936207, 0.39269908169872414, 0.0)
```

* A one-dimensional "column" grid:

```julia
julia> using Oceananigans

julia> grid = RegularCartesianGrid(size=256, z=(-128, 0), topology=(Flat, Flat, Bounded))
RegularCartesianGrid{Float64, Flat, Flat, Bounded}
                   domain: x ∈ [0.0, 0.0], y ∈ [0.0, 0.0], z ∈ [-128.0, 0.0]
                 topology: (Flat, Flat, Bounded)
  resolution (Nx, Ny, Nz): (1, 1, 256)
   halo size (Hx, Hy, Hz): (0, 0, 1)
grid spacing (Δx, Δy, Δz): (0.0, 0.0, 0.5)
```

In principle we can also eliminate the pressure solver for column models. I'll leave this optimization for a future PR.

Resolves #902 
Resolves #940 
Resolves #1001
Resolves #35

### CODE REVIEW

File: src/Operators/difference_operators.jl [hunk 1]
```diff
@@ -49,3 +51,25 @@
 @inline δᴶyᵃᶠᶠ(i, j, k, grid, c) = δyᵃᶠᵃ(i, j, k, grid, Ay_ψᵃᵃᶠ, c)
 @inline δᴶzᵃᵃᶜ(i, j, k, grid, c) = δzᵃᵃᶜ(i, j, k, grid, Az_ψᵃᵃᵃ, c)
 @inline δᴶzᵃᵃᶠ(i, j, k, grid, c) = δzᵃᵃᶠ(i, j, k, grid, Az_ψᵃᵃᵃ, c)
+
+#####
+##### Support for Flat Earths
+#####
```
Comment (ali-ramadhan) [inline src/Operators/difference_operators.jl:57]: Yes 🗺️

**Review by ali-ramadhan — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
Also resolves #35
