### PR TITLE
Fix flat advective fluxes

### LINKED ISSUE #2742: Advection for the Flat Direction Momentum Equation Seems Missing
Hi all,

I run a 2D grid setup (y-z) for a while and I get advection terms through a kernel function below. 
With the recent upgrade, I switched the advection scheme from WENO5() to WENO(). 
However,  the output of the u advection (fluctuation and background) becomes zero. And x-momentum is perfectly balanced between Coriolis force and viscosity.
The problem only happens in the flat direction and it remains with 5th order upwind too.

I wonder if I write the function wrong, or the model really does not calculate the advection for the velocity in the flat direction.

```
@inline function _Duu_div(i,j,k,grid,dep,params)
return div_𝐯u(i, j, k, grid,params.adv,params.vel,params.tracer);
end
Duu_div = Field(KernelFunctionOperation{Face, Center, Center}(_Duu_div,model.grid;parameters=(; adv = model.advection, vel = model.velocities, tracer = model.velocities.u),computed_dependencies = (1)));
```

_My model Setup:_

```
## Grid 
L = 1e3;
H = 100;

Ny = 1024;
Nz = 128;

## Streched Grid
hc = 1.37;
theta_s = 3.53;

@inline Space_z(k) = (hc*(k-Nz-1)/Nz + (H-hc)*sinh(theta_s*(k-Nz-1)/Nz)/sinh(theta_s));

grid = RectilinearGrid(GPU(); topology = (Flat, Periodic, Bounded),
                      size = (Ny, Nz),
                       y = (0, L),
                       z = Space_z,
                      );
```

```
model = NonhydrostaticModel(; grid, buoyancy = BuoyancyTracer(),
                       advection = WENO(; grid = grid),
                          timestepper = :RungeKutta3,
                            tracers = (:b), 
                           coriolis = FPlane(f=f),`
                            forcing = (b=b_force, u=u_force, v=v_force, w=w_force),
                            closure = (vertical_diffusive_closure, horizontal_diffusive_closure),
                           boundary_conditions = (u = u_bcs,),
                            background_fields = (u = U_bfield, b = B_bfield))
```
Let me know if more information is needed.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #2742

### CODE REVIEW

**Comment by navidcy** [comment]
@fucent does this fix the issue?

**Review by glwagner — APPROVED** [review]
Not sure if it makes sense to test this (but it might). It's not exactly a "bug" or "typo", so I feel the risk that this will be reintroduced in the future is small.

**Comment by simone-silvestri** [comment]
I guess then you also have to fix the interpolations to account for `Flat` dimensions

**Comment by navidcy** [comment]
Isn't this done here:
https://github.com/CliMA/Oceananigans.jl/blob/a31eb0e966d1104cda741184f2f68f2527a6c559/src/Operators/interpolation_operators.jl#L93-L117

?

**Comment by simone-silvestri** [comment]
I decoupled the high-order reconstructions from the low-order interpolations. 
The reconstruction for advective fluxes are in `Advection/reconstruction_coefficients.jl`

You can probably extend all the instances of `symmetric_interpolate`, `left_biased_interpolate` and `right_biased_interpolate` in `flat_advective_fluxes`. Or maybe put a fallback for Flat grids in `topologically_conditional_interpolation.jl`

**Comment by simone-silvestri** [comment]
The only problem are the low order advection schemes. High order advection should be taken care of by the `boundary_buffer`

**Comment by navidcy** [comment]
I don't understand what I need to do tbh.

File: src/Advection/flat_advective_fluxes.jl [hunk 1]
```diff
@@ -6,24 +6,15 @@
...
         @inline advective_momentum_flux_Vu(i, j, k, grid::AbstractGrid{FT, TX, Flat}, scheme::$SchemeType, V, u) where {FT, TX} = zero(grid)
         @inline advective_momentum_flux_Vw(i, j, k, grid::AbstractGrid{FT, TX, Flat}, scheme::$SchemeType, V, w) where {FT, TX} = zero(grid)
 
         @inline advective_momentum_flux_Wu(i, j, k, grid::AbstractGrid{FT, TX, TY, Flat}, scheme::$SchemeType, W, u) where {FT, TX, TY} = zero(grid)
         @inline advective_momentum_flux_Wv(i, j, k, grid::AbstractGrid{FT, TX, TY, Flat}, scheme::$SchemeType, W, v) where {FT, TX, TY} = zero(grid)
+        @inline advective_momentum_flux_Ww(i, j, k, grid::AbstractGrid{FT, TX, TY, Flat}, scheme::$SchemeType, W, w) where {FT, TX, TY} = zero(grid)
     end
-end
\ No newline at end of file
+end
```
Comment (simone-silvestri) [inline src/Advection/flat_advective_fluxes.jl:20]:
```suggestion
end

@inline inner_right_biased_interpolate_xᶠᵃᵃ(i, j, k, grid::XFlatGrid, scheme, ψ, args...) = ψ[i, j, k]
@inline inner_right_biased_interpolate_yᵃᶠᵃ(i, j, k, grid::YFlatGrid, scheme, ψ, args...) = ψ[i, j, k]
@inline inner_right_biased_interpolate_zᵃᵃᶠ(i, j, k, grid::ZFlatGrid, scheme, ψ, args...) = ψ[i, j, k]

@inline inner_right_biased_interpolate_xᶠᵃᵃ(i, j, k, grid::XFlatGrid, scheme, ψ::Function, idx, loc, args...) = ψ(i, j, k, grid, args...)
@inline inner_right_biased_interpolate_yᵃᶠᵃ(i, j, k, grid::YFlatGrid, scheme, ψ::Function, idx, loc, args...) = ψ(i, j, k, grid, args...)
@inline inner_right_biased_interpolate_zᵃᵃᶠ(i, j, k, grid::ZFlatGrid, scheme, ψ::Function, idx, loc, args...) = ψ(i, j, k, grid, args...)
```

Comment (simone-silvestri) [reply src/Advection/flat_advective_fluxes.jl:20]: and the same for `left_biased` and the `symmetric` interpolation

File: src/Advection/flat_advective_fluxes.jl [hunk 2]
```diff
@@ -19,6 +19,10 @@ for SchemeType in [:CenteredScheme, :UpwindScheme]
     end
 end
 
+const XFlatGrid = AG{<:Any, Flat}
+const YFlatGrid = AG{<:Any, <:Any, Flat}
+const ZFlatGrid = AG{<:Any, <:Any, <:Any, Flat}
+
```
Comment (simone-silvestri) [inline src/Advection/flat_advective_fluxes.jl]: using Oceananigans.Operators: XFlatGrid, YFlatGrid, ZFlatGrid

Comment (navidcy) [reply src/Advection/flat_advective_fluxes.jl]: done

Comment (simone-silvestri) [reply src/Advection/flat_advective_fluxes.jl]: ah ok you have already done it :sweat_smile:

**Comment by navidcy** [comment]
@simone-silvestri, it's complaining about some ambiguity...
https://buildkite.com/clima/oceananigans/builds/8786#0183a37d-5379-46f9-882f-42e84bdaccd8/36-373

is the `Flat` parameter part of the scheme also?

File: src/Advection/flat_advective_fluxes.jl [hunk 3]
```diff
@@ -3,27 +3,44 @@
...
+@inline inner_left_biased_interpolate_yᵃᶠᵃ(i, j, k, grid::YFlatGrid, scheme, ψ::Function, idx, loc, args...) = @inbounds ψ(i, j, k, grid, args...)
+@inline inner_left_biased_interpolate_zᵃᵃᶠ(i, j, k, grid::ZFlatGrid, scheme, ψ::Function, idx, loc, args...) = @inbounds ψ(i, j, k, grid, args...)
+
+@inline inner_symmetric_interpolate_xᶠᵃᵃ(i, j, k, ::XFlatGrid, scheme, ψ, args...) = @inbounds ψ[i, j, k]
+@inline inner_symmetric_interpolate_yᵃᶠᵃ(i, j, k, ::YFlatGrid, scheme, ψ, args...) = @inbounds ψ[i, j, k]
+@inline inner_symmetric_interpolate_zᵃᵃᶠ(i, j, k, ::ZFlatGrid, scheme, ψ, args...) = @inbounds ψ[i, j, k]
+
+@inline inner_symmetric_interpolate_xᶠᵃᵃ(i, j, k, grid::XFlatGrid, scheme, ψ::Function, idx, loc, args...) = @inbounds ψ(i, j, k, grid, args...)
+@inline inner_symmetric_interpolate_yᵃᶠᵃ(i, j, k, grid::YFlatGrid, scheme, ψ::Function, idx, loc, args...) = @inbounds ψ(i, j, k, grid, args...)
+@inline inner_symmetric_interpolate_zᵃᵃᶠ(i, j, k, grid::ZFlatGrid, scheme, ψ::Function, idx, loc, args...) = @inbounds ψ(i, j, k, grid, args...)
```
Comment (simone-silvestri) [inline src/Advection/flat_advective_fluxes.jl]:
```suggestion

Grids = [:XFlatGrid, :YFlatGrid, :ZFlatGrid, :XFlatGrid, :YFlatGrid, :ZFlatGrid]

for side in (:left_biased, :right_biased, :symmetric)
    for (dir, Grid) in zip([:xᶠᵃᵃ, :yᵃᶠᵃ, :zᵃᵃᶠ, :xᶜᵃᵃ, :yᵃᶜᵃ, :zᵃᵃᶜ], Grids)
        interp_function = Symbol(side, :_interpolate_, dir)
        @eval begin
            $interp_function(i, j, k, grid::$Grid, ψ, args...) = @inbounds ψ[i, j, k]
            $interp_function(i, j, k, grid::$Grid, ψ::Function, args...) = @inbounds ψ(i, j, k, grid, args...)
        end
    end
end
```
since we need a bunch of interpolates maybe metaprogramming is good for it

Comment (navidcy) [reply src/Advection/flat_advective_fluxes.jl]: Done

**Comment by navidcy** [comment]
Still some issues...
https://buildkite.com/clima/oceananigans/builds/8820#0183d019-d738-4486-ac24-f0ac93745862/19-788

**Comment by simone-silvestri** [comment]
you need to extend the same functions specifically for `scheme::AbstractUpwindBiasedAdvectionScheme` because of

https://github.com/CliMA/Oceananigans.jl/blob/74ce7d2248792560ea0c9286a3274c2dbacfabea/src/Advection/upwind_biased_reconstruction.jl#L92-L98

```suggestion
@inline symmetric_interpolate_xᶠᵃᵃ(i, j, k, grid::XFlatGrid, scheme::AbstractUpwindBiasedAdvectionScheme, c) = @inbounds c[i, j, k]
@inline symmetric_interpolate_yᵃᶠᵃ(i, j, k, grid::YFlatGrid, scheme::AbstractUpwindBiasedAdvectionScheme, c) = @inbounds c[i, j, k]
@inline symmetric_interpolate_zᵃᵃᶠ(i, j, k, grid::ZFlatGrid, scheme::AbstractUpwindBiasedAdvectionScheme, c) = @inbounds c[i, j, k]

@inline symmetric_interpolate_xᶜᵃᵃ(i, j, k, grid::XFlatGrid, scheme::AbstractUpwindBiasedAdvectionScheme, u) = @inbounds c[i, j, k]
@inline symmetric_interpolate_yᵃᶜᵃ(i, j, k, grid::YFlatGrid, scheme::AbstractUpwindBiasedAdvectionScheme, v) = @inbounds c[i, j, k]
@inline symmetric_interpolate_zᵃᵃᶜ(i, j, k, grid::ZFlatGrid, scheme::AbstractUpwindBiasedAdvectionScheme, w) = @inbounds c[i, j, k]
```

File: src/Advection/flat_advective_fluxes.jl [hunk 4]
```diff
@@ -3,27 +3,40 @@
...
+Grids = [:XFlatGrid, :YFlatGrid, :ZFlatGrid, :XFlatGrid, :YFlatGrid, :ZFlatGrid]
 
-        @inline advective_momentum_flux_Wu(i, j, k, grid::AbstractGrid{FT, TX, TY, Flat}, scheme::$SchemeType, W, u) where {FT, TX, TY} = zero(grid)
-        @inline advective_momentum_flux_Wv(i, j, k, grid::AbstractGrid{FT, TX, TY, Flat}, scheme::$SchemeType, W, v) where {FT, TX, TY} = zero(grid)
+for side in (:left_biased, :right_biased, :symmetric)
+    for (dir, Grid) in zip([:xᶠᵃᵃ, :yᵃᶠᵃ, :zᵃᵃᶠ, :xᶜᵃᵃ, :yᵃᶜᵃ, :zᵃᵃᶜ], Grids)
+        interp_function = Symbol(side, :_interpolate_, dir)
+        @eval begin
+            $interp_function(i, j, k, grid::$Grid, scheme, ψ, args...) = @inbounds ψ[i, j, k]
+            $interp_function(i, j, k, grid::$Grid, scheme, ψ::Function, idx, loc, args...) = @inbounds ψ(i, j, k, grid, args...)
```
Comment (simone-silvestri) [inline src/Advection/flat_advective_fluxes.jl:31]:
```suggestion
            $interp_function(i, j, k, grid::$Grid, scheme, ψ::Function, args...) = @inbounds ψ(i, j, k, grid, args...)
```
