### PR TITLE
Informative error message for non-regularly spaced grids in `NonhydrostaticModel`

### LINKED ISSUE #2940: Nonhydrostatic pressure solver does not accept a horizontally irregular grid.
Hello,
I noticed a vertically irregular grid can be passed to a nonhydrostatic model and seems to run without a problem, but when the same formulation is applied to the horizontal, a method error is returned by the PressureSolver. The error persists if either the FFTBasedPoissonSolver or the FourierTridiagonalPoissonSolver are called. Is this a known issue?

A MWE follows. Notice the MWE is a reduction of the example given in the [grid documentation](https://clima.github.io/OceananigansDocumentation/stable/model_setup/grids/), which also gives back the same error when passed to a nonhydrostatic model.
``` 
using Oceananigans

Lx, Ly, Lz = 1e4, 1e4, 1e3;
Nx, Ny, Nz = 64, 64, 32;
chebychev_spaced_y_faces(j) = - Ly/2 * cos(π * (j - 1) / Ny)

grid = RectilinearGrid(size = (Nx, Ny, Nz),
topology = (Periodic, Bounded, Bounded),
                              x = (0, Lx),
                              y = chebychev_spaced_y_faces,
                              z = (-Lz,0)
                              )

model = NonhydrostaticModel(; grid)
```

Gives:
```  
ERROR: MethodError: no method matching PressureSolver(::CPU, ::RectilinearGrid{Float64, Periodic, Bounded, Bounded, Float64, OffsetArrays.OffsetVector{Float64, Vector{Float64}}, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, 
Int64}}, OffsetArrays.OffsetVector{Float64, Vector{Float64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU})
Closest candidates are:
  PressureSolver(::Any, ::RectilinearGrid{<:Any, <:Any, <:Any, <:Any, <:Number, <:Number, <:Number}) at C:\Users\.julia\packages\Oceananigans\MDeEL\src\Models\NonhydrostaticModels\NonhydrostaticModels.jl:23
  PressureSolver(::Any, ::RectilinearGrid{<:Any, <:Any, <:Any, <:Any, <:Number, <:Number}) at C:\Users\.julia\packages\Oceananigans\MDeEL\src\Models\NonhydrostaticModels\NonhydrostaticModels.jl:24
  PressureSolver(::Any, ::ImmersedBoundaryGrid) at C:\Users\.julia\packages\Oceananigans\MDeEL\src\Models\NonhydrostaticModels\NonhydrostaticModels.jl:27
Stacktrace:
 [1] NonhydrostaticModel(; grid::RectilinearGrid{Float64, Periodic, Bounded, Bounded, Float64, OffsetArrays.OffsetVector{Float64, Vector{Float64}}, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, Vector{Float64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, clock::Clock{Float64}, advection::Centered{1, Float64, Nothing, Nothing, Nothing, Nothing}, buoyancy::Nothing, coriolis::Nothing, stokes_drift::Nothing, forcing::NamedTuple{(), Tuple{}}, closure::Nothing, boundary_conditions::NamedTuple{(), Tuple{}}, tracers::Tuple{}, timestepper::Symbol, background_fields::NamedTuple{(), Tuple{}}, particles::Nothing, velocities::Nothing, pressures::Nothing, diffusivity_fields::Nothing, pressure_solver::Nothing, immersed_boundary::Nothing, auxiliary_fields::NamedTuple{(), Tuple{}}, calculate_only_active_cells_tendencies::Bool)
   @ Oceananigans.Models.NonhydrostaticModels C:\Users\.julia\packages\Oceananigans\MDeEL\src\Models\NonhydrostaticModels\nonhydrostatic_model.jl:184
 [2] top-level scope
   @ d:\Documentos\Oceananigans\inertial-instability\Minimum_notworking_example.jl:17
  ```
All the best.

### PR DESCRIPTION
**Pull request by navidcy**
This PR adds an informative error when a grid with non-regularly spaced $x$ or $y$ dimensions is provided in the `NonhydrostaticModel`.

Closes #2940

### CODE REVIEW

File: src/Models/NonhydrostaticModels/nonhydrostatic_model.jl [hunk 1]
```diff
@@ -77,8 +77,9 @@ Keyword arguments
 =================
 
   - `grid`: (required) The resolution and discrete geometry on which the `model` is solved. The
-            architecture (CPU/GPU) that the model is solve is inferred from the architecture
-            of the `grid`.
+            architecture (CPU/GPU) that the model is solve on is inferred from the architecture
```
Comment (tomchor) [inline src/Models/NonhydrostaticModels/nonhydrostatic_model.jl:80]:
```suggestion
            architecture (CPU/GPU) that the model is solved on is inferred from the architecture
```

**Comment by glwagner** [comment]
Maybe better to throw an error in the `PressureSolver` function?

**Review by glwagner — APPROVED** [review]

File: src/Models/NonhydrostaticModels/NonhydrostaticModels.jl [hunk 2]
```diff
@@ -26,6 +26,9 @@ PressureSolver(arch, grid::HRegRectilinearGrid) = FourierTridiagonalPoissonSolve
 # *Evil grin*
 PressureSolver(arch, ibg::ImmersedBoundaryGrid) = PressureSolver(arch, ibg.underlying_grid)
 
+# fall back
+PressureSolver(arch, grid) = error("Pressure solver for NonhydrostaticModel only supports horizontally regularly spaced grids at the moment.")
```
Comment (glwagner) [inline src/Models/NonhydrostaticModels/NonhydrostaticModels.jl:30]:
```suggestion
PressureSolver(arch, grid) = error("None of the implemented pressure solvers for NonhydrostaticModel support horizontally-stretched grids.")
```

**Review by simone-silvestri — APPROVED** [review]
