### PR TITLE
Bugfix for `parent_index_range`

### LINKED ISSUE #3572: Bug in determination of indices of parent array by `parent_index_range`
Consider the following MWE:

```julia
julia> using Oceananigans

julia> grid = RectilinearGrid(size=(3, 3, 1), x=(0, 1), y=(0, 1), z=(0, 1));

julia> model = HydrostaticFreeSurfaceModel(; grid,
                                           momentum_advection = nothing,
                                           free_surface = ExplicitFreeSurface(; gravitational_acceleration = 10),
                                           closure = nothing,
                                           tracers = nothing,
                                           buoyancy = nothing)
HydrostaticFreeSurfaceModel{CPU, RectilinearGrid}(time = 0 seconds, iteration = 0)
├── grid: 3×3×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×1 halo
├── timestepper: QuasiAdamsBashforth2TimeStepper
├── tracers: ()
├── closure: Nothing
├── buoyancy: Nothing
├── free surface: ExplicitFreeSurface with gravitational acceleration 10.0 m s⁻²
├── advection scheme:
│   └── momentum: Nothing
└── coriolis: Nothing

julia> Hc, Nc, Nz = grid.Hx, grid.Nx, grid.Nz
(2, 4, 1)

julia> model.free_surface.η[1:Hc, 1:Nc, Nz+1:Nz+1] .= 1
ERROR: BoundsError: attempt to access 9×9×1 Array{Float64, 3} at index [4:6, 4:6, 3:3]
Stacktrace:
 [1] throw_boundserror(A::Array{Float64, 3}, I::Tuple{UnitRange{Int64}, UnitRange{Int64}, UnitRange{Int64}})
   @ Base ./abstractarray.jl:737
 [2] checkbounds
   @ ./abstractarray.jl:702 [inlined]
 [3] view
   @ ./subarray.jl:184 [inlined]
 [4] offset_windowed_data(data::OffsetArrays.OffsetArray{…}, Loc::Tuple{…}, grid::RectilinearGrid{…}, indices::Tuple{…})
   @ Oceananigans.Fields /Users/Sid/Library/CloudStorage/Dropbox/StudyFolder/PostDocMITDesktop/Codes/Oceananigans/main/src/Fields/field.jl:248
 [5] view(f::Field{…}, i::UnitRange{…}, j::UnitRange{…}, k::UnitRange{…})
   @ Oceananigans.Fields /Users/Sid/Library/CloudStorage/Dropbox/StudyFolder/PostDocMITDesktop/Codes/Oceananigans/main/src/Fields/field.jl:316
 [6] maybeview
   @ ./views.jl:148 [inlined]
 [7] dotview(::Field{…}, ::UnitRange{…}, ::UnitRange{…}, ::UnitRange{…})
   @ Base.Broadcast ./broadcast.jl:1244
 [8] top-level scope
   @ REPL[40]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

The error occurs because the parent array of `model.free_surface.η` takes the z-halo into consideration, which does not exist for the ssh field. Generally, when dealing with 1D or 2D fields, the parent array should consider halos only in the dimensions along which the field is defined, rather than in all dimensions as currently implemented. PR #3573 aims to close this issue.

### PR DESCRIPTION
**Pull request by siddharthabishnu**
Closes #3572.

### CODE REVIEW

File: src/Fields/field.jl [hunk 1]
```diff
@@ -245,6 +245,10 @@ function offset_windowed_data(data, Loc, grid, indices)
         windowed_parent = parent(data)
     else
         parent_indices = map(parent_index_range, indices, loc, topo, halo)
+        if size(data)[3] == 1 && first.(axes(data))[3] == grid.Nz + 1 # take ssh into consideration
```
Comment (glwagner) [inline src/Fields/field.jl:248]: What is special about `3`? This code is not supposed to know anything about physics or which way is up...

Comment (glwagner) [reply src/Fields/field.jl:248]: What does

```julia
first.(axes(data))[3] == grid.Nz + 1
```

mean?\

Comment (siddharthabishnu) [reply src/Fields/field.jl]: It's a very specific conditional statement stating that if the size of third dimension is 1, and its first (only) index is Nz+1, then perform the following operation. But thanks to my discussion with you, @glwagner, the issue has now been resolved in commit [bbfc656](https://github.com/CliMA/Oceananigans.jl/pull/3573/commits/bbfc656582689e35256f0f3f8f93e98c2479c810).

Comment (glwagner) [reply src/Fields/field.jl]: ok great, note too that `size(data, 3)` is preferred to `size(data)[3]`

**Comment by glwagner** [comment]
There are a couple issues dedicated to index issues with the free surface that might be related. @siddharthabishnu can you try to track these down?

**Comment by glwagner** [comment]
Might be good to add a test (or more than just one) for windowed fields. Even a simple one like

```julia
windowed_field = CenterField(grid, indices=(:, :, 1:1))
@test view(windowed_field, :, :, 1:1) isa AbstractArray
```

or something.

@siddharthabishnu can you add that? Pretty basic test so probably belongs in `test_field.jl`:

https://github.com/CliMA/Oceananigans.jl/blob/sb/extend-parent-indices/test/test_field.jl

**Comment by navidcy** [comment]
A lot of tests seem to fail...

**Comment by glwagner** [comment]
> A lot of tests seem to fail...

This is troubling

**Comment by glwagner** [comment]
Ok, I think it's because `parent_index_range` is used by the `NetCDFOutputWriter`. I suspect that it is being used incorrectly there though --- because I am nearly positive that this change does in fact fix a bug.

**Comment by glwagner** [comment]
Ok I think I understand the issue. `parent_index_range` is being used for two different purposes.

In `NetCDFOutputWriter` the "parent" is an array that spans the entire dimension; we just want to translate indices defined on the grid to indices defined on the underlying parent array (I think the reason we need a function is because we need to treat `Nothing` locations specially).

In `offset_windowed_data` the `indices` argument are the indices of a windowed field itself.

I think we just need two different functions. I'll fix it.

**Comment by glwagner** [comment]
Ok here's a little more insight into the problem. The issue is actually with `view`, which doesn't work when called on windowed field. `view` can only _create_ a windowed field from a full field, right now. In other words, `view` cannot act on a `view`. Haha.

I'm extending `view` to work correctly when the argument itself is already windowed.

**Comment by navidcy** [comment]
nice one!

**Comment by glwagner** [comment]
OY.

Ok I worked on it a bit. This works:

```julia
julia> grid = RectilinearGrid(size=(1, 1, 3), x=(0, 1), y=(0, 1), z=(0, 1));

julia> c = CenterField(grid);

julia> set!(c, (x, y, z) -> rand())
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.92472, min=0.40508, mean=0.67047

julia> cv = view(c, :, :, 2:3)
1×1×2 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 2:3)
└── data: 3×3×2 OffsetArray(view(::Array{Float64, 3}, :, :, 5:6), 0:2, 0:2, 2:3) with eltype Float64 with indices 0:2×0:2×2:3
    └── max=0.92472, min=0.681611, mean=0.803165

julia> cvv = view(cv, :, :, 3)
1×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 3:3)
└── data: 3×3×1 OffsetArray(view(::Array{Float64, 3}, :, :, 6:6), 0:2, 0:2, 3:3) with eltype Float64 with indices 0:2×0:2×3:3
    └── max=0.681611, min=0.681611, mean=0.681611

julia> cvvv = view(cvv, :, :, 3)
1×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 3:3)
└── data: 3×3×1 OffsetArray(view(::Array{Float64, 3}, :, :, 6:6), 0:2, 0:2, 3:3) with eltype Float64 with indices 0:2×0:2×3:3
    └── max=0.681611, min=0.681611, mean=0.681611

julia> interior(c, :, :, 3) .= 0
1×1 view(::Array{Float64, 3}, 2:2, 2:2, 6) with eltype Float64:
 0.0

julia> cvv
1×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 3:3)
└── data: 3×3×1 OffsetArray(view(::Array{Float64, 3}, :, :, 6:6), 0:2, 0:2, 3:3) with eltype Float64 with indices 0:2×0:2×3:3
    └── max=0.0, min=0.0, mean=0.0

julia> cv
1×1×2 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 2:3)
└── data: 3×3×2 OffsetArray(view(::Array{Float64, 3}, :, :, 5:6), 0:2, 0:2, 2:3) with eltype Float64 with indices 0:2×0:2×2:3
    └── max=0.92472, min=0.0, mean=0.46236
```

Note that one of the quirks of fields that come from views, is that `parent` returns a `view`: 

```julia
julia> parent(cv)
3×3×2 view(::Array{Float64, 3}, :, :, 5:6) with eltype Float64:
[:, :, 1] =
 0.0  0.0      0.0
 0.0  0.92472  0.0
 0.0  0.0      0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> parent(cvv)
3×3×1 view(::Array{Float64, 3}, :, :, 6:6) with eltype Float64:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
```

That's different than if you create a windowed field from scratch:

```julia
julia> b = CenterField(grid, indices=(:, :, 3))
1×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 3:3)
└── data: 3×3×1 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, 3:3) with eltype Float64 with indices 0:2×0:2×3:3
    └── max=0.0, min=0.0, mean=0.0

julia> parent(b)
3×3×1 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
```

This is how output works --- we use `parent` to get the data that needs to be saved down.

**Comment by glwagner** [comment]
@siddharthabishnu could you help by adding some simple unit tests for views of views? It'd be nice to test correctness, I think something like this would work:

```julia
grid = RectilinearGrid(size=(1, 1, 3), x=(0, 1), y=(0, 1), z=(0, 1))
c = CenterField(grid)
set!(c, (x, y, z) -> rand())

# First test that regular view is right
cv = view(c, :, :, 2:3)
@test c[1, 1, 2] == cv[1, 1, 2]
@test c[1, 1, 3] == cv[1, 1, 3]

# Now test views of views
cvv = view(cv, :, :, 3)
@test cv[1, 1, 3] == cvv[1, 1, 3]
```

We may also want to test that things error correctly like

```julia
julia> view(cv, :, :, 1)
ERROR: ArgumentError: view indices (Colon(), Colon(), 1) do not intersect field indices (Colon(), Colon(), 2:3)
Stacktrace:
 [1] view(f::Field{…}, i::Function, j::Function, k::Int64)
   @ Oceananigans.Fields ~/Projects/dev/Oceananigans.jl/src/Fields/field.jl:315
 [2] top-level scope
   @ REPL[25]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

Maybe

```julia
@test_throws ArgumentError view(cv, :, :, 1)
```

Not sure what else we might want maybe @navidcy has ideas.

**Comment by glwagner** [comment]
Could do 

```julia
@test_throws BoundsError cv[1, 1, 1]
```

**Comment by glwagner** [comment]
And to do those tests on the GPU we need `CUDA.@allowscalar`.

**Comment by navidcy** [comment]
Thanks for this @glwagner!

**Comment by navidcy** [comment]
I ran the doctests locally and this one:

https://github.com/CliMA/Oceananigans.jl/blob/f217b80e26fd08752159a73b2e150ddf9fabd287/src/Fields/field.jl#L270-L298

fails.

I need to head out now but I wanted to document this.

**Comment by navidcy** [comment]
```Julia
julia> using Oceananigans

julia> grid = RectilinearGrid(size=(2, 3, 4), x=(0, 1), y=(0, 1), z=(0, 1));

julia> c = CenterField(grid)
2×3×4 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 2×3×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 6×9×10 OffsetArray(::Array{Float64, 3}, -1:4, -2:6, -2:7) with eltype Float64 with indices -1:4×-2:6×-2:7
    └── max=0.0, min=0.0, mean=0.0

julia> c .= rand(size(c)...);

julia> v = view(c, :, 2:3, 1:2)
2×2×2 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 2×3×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Nothing, north: Nothing, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, 2:3, 1:2)
└── data: 6×2×2 OffsetArray(view(::Array{Float64, 3}, :, 1:2, 1:2), -1:4, 2:3, 1:2) with eltype Float64 with indices -1:4×2:3×1:2
    └── max=0.0, min=0.0, mean=0.0

julia> size(v)
(2, 2, 2)

julia> v[2, 2, 2] == c[2, 2, 2]
false
```

**Comment by glwagner** [comment]
Can't reproduce that @navidcy 

```julia
julia> using Oceananigans
Precompiling Oceananigans
  1 dependency successfully precompiled in 11 seconds. 160 already precompiled.

julia> grid = RectilinearGrid(size=(2, 3, 4), x=(0, 1), y=(0, 1), z=(0, 1));

julia> c = CenterField(grid)
2×3×4 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 2×3×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 6×9×10 OffsetArray(::Array{Float64, 3}, -1:4, -2:6, -2:7) with eltype Float64 with indices -1:4×-2:6×-2:7
    └── max=0.0, min=0.0, mean=0.0

julia> c .= rand(size(c)...);

julia> v = view(c, :, 2:3, 1:2)
2×2×2 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 2×3×4 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 2×3×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Nothing, north: Nothing, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, 2:3, 1:2)
└── data: 6×2×2 OffsetArray(view(::Array{Float64, 3}, :, 5:6, 4:5), -1:4, 2:3, 1:2) with eltype Float64 with indices -1:4×2:3×1:2
    └── max=0.943733, min=0.11545, mean=0.571896

julia> size(v)
(2, 2, 2)

julia> v[2, 2, 2] == c[2, 2, 2]
true
```

**Comment by navidcy** [comment]
And all tests pass! Great! Ignore my messages!

**Comment by navidcy** [comment]
@siddharthabishnu will you add test(s)?

**Comment by siddharthabishnu** [comment]
@glwagner and @navidcy, I will add the tests today. @glwagner, thank you for investigating and identifying the root cause of the issue.

File: test/test_field.jl [hunk 2]
```diff
@@ -451,4 +450,67 @@ end
...
+
+            # First test that the regular view is correct
+            cv = view(c, :, :, firstindex(interior(c), 3)+1:lastindex(interior(c), 3)-1)
+            # cv = view(c, :, :, 2:6) for periodic topology in z and cv = view(c, :, :, 2:7) for bounded topology in z.
+            @test size(cv) == (1, 1, size_c[3]-2)
+            @test size(parent(cv)) == (1+2Hx, 1+2Hy, size_c[3]-2)
+            @test all(cv[1, 1, i] == c[1, 1, i] for i in firstindex(interior(c), 3)+1:lastindex(interior(c), 3)-1)
+
+            # Now test the views of views
+            cvv = view(cv, :, :, firstindex(interior(c), 3)+2:lastindex(interior(c), 3)-2)
```
Comment (glwagner) [inline test/test_field.jl:477]: Maybe define `k_tops = [Nz, Nz+1]` and include that in the loop above

File: test/test_field.jl [hunk 3]
```diff
@@ -451,4 +450,67 @@ end
...
         end
     end
+
+    @testset "Views of field views" begin
+        @info "  Testing views of field views..."
+
+        FieldTypes = (CenterField, XFaceField, YFaceField, ZFaceField)
+        ZTopologies = (Periodic, Bounded)
+
+        for arch in archs, FT in float_types, FieldType in FieldTypes, ZTopology in ZTopologies
```
Comment (glwagner) [inline test/test_field.jl:460]: I know its written all over the tests, from a distance of a few years of writing this code I wonder if something like this would be easier to understand:

```suggestion
        for n = 1:2
        
            arch = archs[n]
            FT = float_types[n]
            FieldType = FieldTypes[n]
            ZTopology = ZTopologies[n]
```

**Comment by glwagner** [comment]
The tests use a lot of scalar indexing that's why they fail on the GPU:

https://buildkite.com/clima/oceananigans/builds/15604#018f40ed-787d-4e74-a5f4-ae1656fa3043/18-724

I think if we are comparing single numbers it makes sense to use `@allowscalar`.

If we are comparing vectors it could be nice to figure out how to get the tests to run without `@allowscalar` since presumably this is possible.

File: test/test_field.jl (hunk 3 above)
Comment (navidcy) [reply test/test_field.jl:460]: I don't really like that that tbh

Comment (glwagner) [reply test/test_field.jl:460]: Then we have to write something like

```julia
for arch in archs, FT in float_types, FieldType in FieldTypes, (ZTopology, k_top) in zip(ZTopologies, k_tops)
```

Comment (glwagner) [reply test/test_field.jl:460]: I realized what I wrote above is not equivalent to the current code, which does every permutation (not just 2 cases, its 2^4 cases)

**Comment by navidcy** [comment]
@siddharthabishnu could you deal with this?

File: test/test_field.jl (hunk 3 above)
Comment (siddharthabishnu) [reply test/test_field.jl:462]: Even the code snippet
```julia
        Nx, Ny, Nz = 1, 1, 7

        FieldTypes = (CenterField, XFaceField, YFaceField, ZFaceField)
        ZTopologies = (Periodic, Bounded)
        k_tops = (Nz, Nz+1)

        for arch in archs, FT in float_types, FieldType in FieldTypes, (ZTopology, k_top) in zip(ZTopologies, k_tops)
            grid = RectilinearGrid(arch, FT, size=(Nx, Ny, Nz), x=(0, 1), y=(0, 1), z=(0, 1), topology = (Periodic, Periodic, ZTopology))
            Hx, Hy, Hz = halo_size(grid)
```
would yield erroneous results since `k_top = Nz + 1` only for a `ZFaceField` with bounded topology in `z` and `k_top = Nz` for all other cases. So, I adjusted the implementation as follows:
```julia
        Nx, Ny, Nz = 1, 1, 7

        FieldTypes = (CenterField, XFaceField, YFaceField, ZFaceField)
        ZTopologies = (Periodic, Bounded)

        for arch in archs, FT in float_types, FieldType in FieldTypes, ZTopology in ZTopologies
            grid = RectilinearGrid(arch, FT, size=(Nx, Ny, Nz), x=(0, 1), y=(0, 1), z=(0, 1), topology = (Periodic, Periodic, ZTopology))
            Hx, Hy, Hz = halo_size(grid)

            k_top = (FieldType == ZFaceField && ZTopology == Bounded) ? Nz+1 : Nz 
```

Comment (glwagner) [reply test/test_field.jl:462]: great

**Comment by siddharthabishnu** [comment]
> The tests use a lot of scalar indexing that's why they fail on the GPU:
> 
> https://buildkite.com/clima/oceananigans/builds/15604#018f40ed-787d-4e74-a5f4-ae1656fa3043/18-724
> 
> I think if we are comparing single numbers it makes sense to use `@allowscalar`.
> 
> If we are comparing vectors it could be nice to figure out how to get the tests to run without `@allowscalar` since presumably this is possible.

Given that we're comparing elements of vectors with a maximum length of 6, I opted to use `CUDA.@allowscalar`. The impact on performance is minimal when running on a GPU.

**Comment by siddharthabishnu** [comment]
> @siddharthabishnu could you deal with this?

Done. I think it's ready to merge once the tests pass.

**Comment by siddharthabishnu** [comment]
@glwagner, @navidcy, could one of you please review the changes and approve them if you are satisfied?

File: test/test_field.jl [hunk 4]
```diff
@@ -451,4 +450,65 @@ end
...
+
+                @test_throws BoundsError cv[:, :, 1]
+                @test_throws BoundsError cv[:, :, k_top]
+                # @test_throws BoundsError cv[:, :, 8] for a ZFaceField with bounded topology in z else @test_throws BoundsError cv[:, :, 7].
+                @test_throws BoundsError cvv[:, :, 1:1+1]
+                @test_throws BoundsError cvv[:, :, k_top-1:k_top]
+                # @test_throws BoundsError cvv[:, :, 7:8] for a ZFaceField with bounded topology in z else @test_throws BoundsError cvv[:, :, 6:7].
+                @test_throws BoundsError cvvv[:, :, 1:1+2]
+                @test_throws BoundsError cvvv[:, :, k_top-2:k_top]
+                # @test_throws BoundsError cvvv[:, :, 6:8] for a ZFaceField with bounded topology in z else @test_throws BoundsError cvvv[:, :, 5:7].
```
Comment (glwagner) [inline test/test_field.jl:510]: @siddharthabishnu can you put `@allowscalar` around only the specific lines where it is needed? I thought by using `k_top` we eliminated the need for the comments. Not sure what the comments mean

File: test/test_field.jl [hunk 5]
```diff
@@ -451,4 +450,65 @@ end
...
+                # @test_throws ArgumentError view(cvvv, :, :, 6:8) for a ZFaceField with bounded topology in z else @test_throws ArgumentError view(cvvv, :, :, 5:7).
+
+                @test_throws BoundsError cv[:, :, 1]
+                @test_throws BoundsError cv[:, :, k_top]
+                # @test_throws BoundsError cv[:, :, 8] for a ZFaceField with bounded topology in z else @test_throws BoundsError cv[:, :, 7].
+                @test_throws BoundsError cvv[:, :, 1:1+1]
+                @test_throws BoundsError cvv[:, :, k_top-1:k_top]
+                # @test_throws BoundsError cvv[:, :, 7:8] for a ZFaceField with bounded topology in z else @test_throws BoundsError cvv[:, :, 6:7].
+                @test_throws BoundsError cvvv[:, :, 1:1+2]
+                @test_throws BoundsError cvvv[:, :, k_top-2:k_top]
```
Comment (glwagner) [inline test/test_field.jl:509]: should this use `interior`? We don't ever directly index fields in the user interface

```suggestion
                @test_throws BoundsError cvvv[:, :, k_top-2:k_top]

```

File: test/test_field.jl (hunk 4 above)
Comment (siddharthabishnu) [reply test/test_field.jl]: @glwagner, agreed. Resolved in commit [427cb51](https://github.com/CliMA/Oceananigans.jl/pull/3573/commits/427cb51b0a4abef57dd6f504bfa1c5fef0096eed).

File: test/test_field.jl (hunk 5 above)
Comment (siddharthabishnu) [reply test/test_field.jl]: Unfortunately, not, unless we also extend the interior index range like we did with the parent index range. Consider the following MWE:

```julia
julia> using Oceananigans

julia> Nx, Ny, Nz = 1, 1, 7;

julia> grid = RectilinearGrid(size=(Nx, Ny, Nz), x=(0, 1), y=(0, 1), z=(0, 1), topology = (Periodic, Periodic, Bounded));

julia> k_top = Nz + 1;

julia> c = ZFaceField(grid)
1×1×8 Field{Center, Center, Face} on RectilinearGrid on CPU
├── grid: 1×1×7 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
└── data: 3×3×14 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:11) with eltype Float64 with indices 0:2×0:2×-2:11
    └── max=0.0, min=0.0, mean=0.0

julia> set!(c, (x, y, z) -> rand())
1×1×8 Field{Center, Center, Face} on RectilinearGrid on CPU
├── grid: 1×1×7 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
└── data: 3×3×14 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:11) with eltype Float64 with indices 0:2×0:2×-2:11
    └── max=0.72276, min=0.0939695, mean=0.428961

julia> cv = view(c, :, :, 1+1:k_top-1)
1×1×6 Field{Center, Center, Face} on RectilinearGrid on CPU
├── grid: 1×1×7 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: Nothing, top: Nothing, immersed: ZeroFlux
├── indices: (:, :, 2:7)
└── data: 3×3×6 OffsetArray(view(::Array{Float64, 3}, :, :, 5:10), 0:2, 0:2, 2:7) with eltype Float64 with indices 0:2×0:2×2:7
    └── max=0.72276, min=0.0939695, mean=0.503409

julia> interior(cv)
1×1×6 view(::Array{Float64, 3}, 2:2, 2:2, 5:10) with eltype Float64:
[:, :, 1] =
 0.6491566506900277

[:, :, 2] =
 0.5118574586205709

[:, :, 3] =
 0.6214555441666034

[:, :, 4] =
 0.09396949649555086

[:, :, 5] =
 0.7227599953730516

[:, :, 6] =
 0.4212556767008805
```
Currently, the interior indices start from 1 and extend up to the size of the interior of the field.

File: test/test_field.jl [hunk 6]
```diff
@@ -451,4 +450,54 @@ end
...
+        Nx, Ny, Nz = 1, 1, 7
+
+        FieldTypes = (CenterField, XFaceField, YFaceField, ZFaceField)
+        ZTopologies = (Periodic, Bounded)
+
+        for arch in archs, FT in float_types, FieldType in FieldTypes, ZTopology in ZTopologies
+            grid = RectilinearGrid(arch, FT, size=(Nx, Ny, Nz), x=(0, 1), y=(0, 1), z=(0, 1), topology = (Periodic, Periodic, ZTopology))
+            Hx, Hy, Hz = halo_size(grid)
+
+            k_top = (FieldType == ZFaceField && ZTopology == Bounded) ? Nz+1 : Nz
```
Comment (navidcy) [inline test/test_field.jl:466]: there is a function for this; you need to do `using Oceananigans.Grids: total_length` and then 

```suggestion
            k_top = total_length(location(c, 3)(), topology(c, 3)(), size(grid, 3))
```

File: test/test_field.jl [hunk 7]
```diff
@@ -451,4 +450,54 @@ end
...
+            Hx, Hy, Hz = halo_size(grid)
+
+            k_top = (FieldType == ZFaceField && ZTopology == Bounded) ? Nz+1 : Nz 
+
+            c = FieldType(grid)
+            set!(c, (x, y, z) -> rand())
+
+            # First test that the regular view is correct
+            cv = view(c, :, :, 1+1:k_top-1)
+            @test size(cv) == (1, 1, k_top-2)
```
Comment (navidcy) [inline test/test_field.jl:473]:
```suggestion
            @test size(cv) == (Nx, Ny, k_top-2)

```

File: test/test_field.jl [hunk 8]
```diff
@@ -451,4 +450,54 @@ end
...
+            @test size(parent(cv)) == (1+2Hx, 1+2Hy, k_top-2)
```
Comment (navidcy) [inline test/test_field.jl:474]:
```suggestion
            @test size(parent(cv)) == (Nx+2Hx, Ny+2Hy, k_top-2)

```

File: test/test_field.jl [hunk 9]
```diff
@@ -451,4 +450,54 @@ end
...
+            CUDA.@allowscalar @test all(cv[1, 1, i] == c[1, 1, i] for i in 1+1:k_top-1)
```
Comment (navidcy) [inline test/test_field.jl:475]:
```suggestion
            CUDA.@allowscalar @test all(cv[1, 1, i] == c[1, 1, i] for i in 1+1:k_top-1)

```

Comment (navidcy) [reply test/test_field.jl:475]: @siddharthabishnu could you remove all the rest hardcoded 1's below (unless they are not hard coded and I missed it...)

**Comment by siddharthabishnu** [comment]
> made few suggestions

All incorporated in commit [d71e14a](https://github.com/CliMA/Oceananigans.jl/pull/3573/commits/d71e14a29b48b54b701d322d26becca151d49154).

File: test/test_field.jl (hunk 5 above)
Comment (glwagner) [reply test/test_field.jl]: I guess I'm not totally sure what the test is contributing

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
good to merge by me

**Comment by navidcy** [comment]
I'm merging
