### PR TITLE
Fix transform planning for uniform grids used by FourierTridiagonalPoissonSolver

### LINKED ISSUE #4580: `FourierTridiagonalPoissonSolver` doesn't work with regular grids
This is related to https://github.com/CliMA/Oceananigans.jl/pull/4535, which was intended to extend `FourierTridiagonalPoissonSolver` to accommodate regular grids. Below is a MWE:

```julia
using Oceananigans
using Printf
using JLD2
using Oceananigans.Solvers: FourierTridiagonalPoissonSolver
using Statistics
using Random

rng = Xoshiro(123)

function initial_conditions!(model)
    h = 0.05
    x₀ = 0.5
    y₀ = 0.5
    z₀ = 0.55
    bᵢ(x, z) = - exp(-((x - x₀)^2 + (z - z₀)^2) / 2h^2)

    set!(model, b=bᵢ)
end

function setup_grid(Nx, Nz)
    zs = collect(range(0, 1, length=Nz + 1))
    zs[2:end-1] .+= rand(rng, length(zs[2:end-1])) * (1 / Nz) / 5

    grid = RectilinearGrid(CPU(), Float64,
                        size = (Nx, Nz), 
                        halo = (4, 4),
                        x = (0, 1),
                        z = (0, 1),
                        # z = zs,
                        topology = (Bounded, Flat, Bounded))

    return grid
end

function setup_model(grid, pressure_solver)
    model = NonhydrostaticModel(; grid, pressure_solver,
                                  advection = WENO(),
                                  coriolis = FPlane(f=0.1),
                                  tracers = :b,
                                  buoyancy = BuoyancyTracer())

    initial_conditions!(model)
    return model
end

Nx = Nz = 64
grid = setup_grid(Nx, Nz)

pressure_solver = FourierTridiagonalPoissonSolver(grid)
model = setup_model(grid, pressure_solver)

stop_iteration = 10
simulation = Simulation(model; Δt=1e-2, stop_iteration=stop_iteration)

time_wizard = TimeStepWizard(cfl=0.6, max_change=1.05, min_Δt=1e-4, max_Δt=1)
simulation.callbacks[:wizard] = Callback(time_wizard, IterationInterval(1))

u, v, w = model.velocities
b = model.tracers.b

d = Field(∂x(u) + ∂y(v) + ∂z(w))
wall_time = Ref(time_ns())

function progress(sim)
    msg = @sprintf("i: %d, t: %s, Δt: %6.3e",
                    iteration(sim), prettytime(time(sim)), sim.Δt)

    elapsed = 1e-9 * (time_ns() - wall_time[])

    compute!(d)

    msg *= @sprintf(", max u: %6.3e, max w: %6.3e, max b: %6.3e, max d: %6.3e, (max, mean) p: (%6.3e %6.3e), wall t: %s",
                    maximum(abs, sim.model.velocities.u),
                    maximum(abs, sim.model.velocities.w),
                    maximum(abs, sim.model.tracers.b),
                    maximum(abs, d),
                    maximum(abs, sim.model.pressures.pNHS),
                    mean(sim.model.pressures.pNHS),
                    prettytime(elapsed))

    @info msg
    wall_time[] = time_ns()

    return nothing
end

simulation.callbacks[:progress] = Callback(progress, IterationInterval(1))

run!(simulation)
```

with outputs

```julia
[ Info: Initializing simulation...
[ Info: i: 0, t: 0 seconds, Δt: 1.050e-02, max u: 0.000e+00, max w: 0.000e+00, max b: 9.835e-01, max d: 0.000e+00, (max, mean) p: (0.000e+00 0.000e+00), wall t: 7.060 seconds
[ Info:     ... simulation initialization complete (6.027 seconds)
[ Info: Executing initial time step...
[ Info: i: 1, t: 10 ms, Δt: 5.250e-03, max u: 5.839e-01, max w: 1.153e+01, max b: 9.843e-01, max d: 1.360e+03, (max, mean) p: (2.921e+01 -4.493e-17), wall t: 3.443 seconds
[ Info:     ... initial time step complete (3.455 seconds).
[ Info: i: 2, t: 15.250 ms, Δt: 2.625e-03, max u: 5.812e+18, max w: 2.463e+21, max b: 5.763e+07, max d: 1.778e+23, (max, mean) p: (1.904e+22 -2.253e+05), wall t: 355.275 ms
[ Info: i: 3, t: 17.875 ms, Δt: 1.313e-03, max u: 1.849e+179, max w: 1.788e+183, max b: 5.097e+152, max d: 1.203e+185, (max, mean) p: (2.943e+184 2.856e+167), wall t: 5.163 ms
[ Info: i: 4, t: 19.188 ms, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 4.891 ms
[ Info: i: 5, t: NaN days, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 4.704 ms
[ Info: i: 6, t: NaN days, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 4.464 ms
[ Info: i: 7, t: NaN days, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 4.366 ms
[ Info: i: 8, t: NaN days, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 4.002 ms
[ Info: i: 9, t: NaN days, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 5.644 ms
[ Info: Simulation is stopping after running for 9.978 seconds.
[ Info: Model iteration 10 equals or exceeds stop iteration 10.
[ Info: i: 10, t: NaN days, Δt:    NaN, max u:    NaN, max w:    NaN, max b:    NaN, max d:    NaN, (max, mean) p: (   NaN    NaN), wall t: 4.877 ms
```

Note that if we use an irregular grid by uncommenting `zs` line in the MWE and commenting out the `z` line the solver works fine, with output like

```julia
[ Info: Initializing simulation...
[ Info: i: 0, t: 0 seconds, Δt: 1.050e-02, max u: 0.000e+00, max w: 0.000e+00, max b: 9.807e-01, max d: 0.000e+00, (max, mean) p: (0.000e+00 0.000e+00), wall t: 4.636 seconds
[ Info:     ... simulation initialization complete (4.884 seconds)
[ Info: Executing initial time step...
[ Info: i: 1, t: 10 ms, Δt: 1.103e-02, max u: 3.060e-03, max w: 3.220e-03, max b: 9.807e-01, max d: 6.002e-16, (max, mean) p: (6.161e-02 1.549e-19), wall t: 3.314 seconds
[ Info:     ... initial time step complete (3.374 seconds).
[ Info: i: 2, t: 21.025 ms, Δt: 1.158e-02, max u: 6.083e-03, max w: 7.688e-03, max b: 9.806e-01, max d: 7.910e-16, (max, mean) p: (7.701e-02 -4.070e-19), wall t: 403.726 ms
[ Info: i: 3, t: 32.601 ms, Δt: 1.216e-02, max u: 8.411e-03, max w: 1.275e-02, max b: 9.803e-01, max d: 1.027e-15, (max, mean) p: (8.614e-02 -3.610e-20), wall t: 7.560 ms
[ Info: i: 4, t: 44.756 ms, Δt: 1.276e-02, max u: 1.048e-02, max w: 1.823e-02, max b: 9.798e-01, max d: 1.679e-15, (max, mean) p: (9.227e-02 1.290e-18), wall t: 5.006 ms
[ Info: i: 5, t: 57.519 ms, Δt: 1.340e-02, max u: 1.250e-02, max w: 2.409e-02, max b: 9.790e-01, max d: 1.360e-15, (max, mean) p: (9.652e-02 1.430e-19), wall t: 4.788 ms
[ Info: i: 6, t: 70.920 ms, Δt: 1.407e-02, max u: 1.455e-02, max w: 3.037e-02, max b: 9.780e-01, max d: 1.221e-15, (max, mean) p: (9.996e-02 4.258e-19), wall t: 4.547 ms
[ Info: i: 7, t: 84.991 ms, Δt: 1.477e-02, max u: 1.667e-02, max w: 3.708e-02, max b: 9.766e-01, max d: 1.471e-15, (max, mean) p: (1.035e-01 -5.932e-19), wall t: 9.957 ms
[ Info: i: 8, t: 99.766 ms, Δt: 1.551e-02, max u: 1.888e-02, max w: 4.417e-02, max b: 9.758e-01, max d: 2.165e-15, (max, mean) p: (1.067e-01 -1.964e-19), wall t: 7.709 ms
[ Info: i: 9, t: 115.279 ms, Δt: 1.629e-02, max u: 2.121e-02, max w: 5.162e-02, max b: 9.780e-01, max d: 2.526e-15, (max, mean) p: (1.073e-01 -2.647e-21), wall t: 10.525 ms
[ Info: Simulation is stopping after running for 8.856 seconds.
[ Info: Model iteration 10 equals or exceeds stop iteration 10.
[ Info: i: 10, t: 131.568 ms, Δt: 1.710e-02, max u: 2.367e-02, max w: 5.945e-02, max b: 9.803e-01, max d: 2.331e-15, (max, mean) p: (1.070e-01 1.552e-19), wall t: 5.734 ms
```

@glwagner

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #4580. Thanks @xkykai for finding this.

### CODE REVIEW

File: src/Solvers/plan_transforms.jl [hunk 1]
```diff
@@ -146,16 +146,28 @@ function plan_transforms(grid::XYZRegularRG, storage, planner_flag)
 end
 
 """ Used by FourierTridiagonalPoissonSolver. """
-function plan_transforms(grid::Union{XYRegularRG, XZRegularRG, YZRegularRG}, storage, planner_flag)
+function plan_transforms(grid, storage, planner_flag, untransformed_dim)
```
Comment (glwagner) [inline src/Solvers/plan_transforms.jl:149]: @xkykai this is the key change. Transforms were being planned assuming something about grid regularity. This assumption is violated when we want to use a tridiagonal solver on triply uniform grid...

Comment (glwagner) [reply src/Solvers/plan_transforms.jl:149]: @shriyafruitwala this could affect your code too but not sure.

**Review by navidcy — APPROVED** [review]
some tests are failing but as soon as those are smoothed out we should merge
