### PR TITLE
Code cleanup

### LINKED ISSUE #5151: Bogus `Oceananigans.Fields.validate_shifted_index` method
```julia-repl
julia> using Oceananigans

julia> Oceananigans.Fields.validate_shifted_index([nothing])
ERROR: UndefVarError: `from_idx` not defined in `Oceananigans.Fields`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] validate_shifted_index(shifted_idx::Vector{Nothing})
   @ Oceananigans.Fields ~/.julia/dev/Oceananigans/src/Fields/field_indices.jl:76
```
https://github.com/CliMA/Oceananigans.jl/blob/478f45bdf95866018e82086bc021b8bfa9c98954/src/Fields/field_indices.jl#L76-L77
This was originally introduced by @navidcy in #2867.

Detected with JETLS.

### LINKED ISSUE #5152: Bogus `Oceananigans.Grids.default_horizontal_extent` method
```julia-repl
julia> using Oceananigans

julia> Oceananigans.Grids.default_horizontal_extent(0, [])
ERROR: UndefVarError: `i` not defined in `Oceananigans.Grids`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] default_horizontal_extent(T::Int64, extent::Vector{Any})
   @ Oceananigans.Grids ~/.julia/dev/Oceananigans/src/Grids/input_validation.jl:167
```
https://github.com/CliMA/Oceananigans.jl/blob/478f45bdf95866018e82086bc021b8bfa9c98954/src/Grids/input_validation.jl#L167
Originally introduced by @glwagner in #1003.

Detected with JETLS.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #5152
Closes #5151

### CODE REVIEW

**Comment by navidcy** [comment]
Nice! LGTM!

File: src/Advection/reconstruction_coefficients.jl [hunk 1]
```diff
@@ -166,7 +166,6 @@ end
         rng = rng .+ 1
     end
     stencil_full = Vector(undef, N)
-    coeff = Symbol(:coeff, order, :_, shift)
```
Comment (simone-silvestri) [inline src/Advection/reconstruction_coefficients.jl:169]: will this work?

Comment (simone-silvestri) [reply src/Advection/reconstruction_coefficients.jl:169]: ah ok I see it was unused because we only grab the stencil in this method
