### PR TITLE
Time averaging and `FieldSlicer` for `NetCDFOutputWriter`

### LINKED ISSUE #876: `Computation` has result at wrong location
Disclaimer: I might be misunderstanding the way abstract operations work.

I'm trying to compute the horizontally-averaged wT at cell faces (of which there should be `Nz+1` values). X-Ref: https://github.com/ali-ramadhan/ClimateSurrogates.jl/pull/4

The abstract operation for wT ends up at `(Cell, Cell, Face)` by default which is where I want it, but it seems to be computed at `(Cell, Cell, Cell)` even when I explicitly specify `@at (Cell, Cell, Face)`.

```julia
using Oceananigans, Oceananigans.Grids,Oceananigans.Diagnostics, Oceananigans.AbstractOperations
grid = RegularCartesianGrid(size=(16, 16, 16), extent=(1, 1, 1))
model = IncompressibleModel(grid=grid)
u, v, w = model.velocities
T, S = model.tracers
wT = w*T
MultiaryOperation at (Cell, Cell, Face)
├── grid: RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
│   ├── size: (16, 16, 16)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0625]
└── tree: 

* at (Cell, Cell, Face)
├── OffsetArray{Float64, 3, Array{Float64,3}}
└── OffsetArray{Float64, 3, Array{Float64,3}}
```

This is fine so far.

```julia
wT_avg = Average(wT, model, dims=(1, 2))

wT_avg.field.operation
MultiaryOperation at (Cell, Cell, Face)
├── grid: RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}
│   ├── size: (16, 16, 16)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0625]
└── tree: 

* at (Cell, Cell, Face)
├── OffsetArray{Float64, 3, Array{Float64,3}}
└── OffsetArray{Float64, 3, Array{Float64,3}}

wT_avg.field.result
Field located at (Cell, Cell, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (18, 18, 18)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=16, Ny=16, Nz=16)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)
```

Seems wrong that the result is at `(Cell, Cell, Cell)` when the operation is at `(Cell, Cell, Face)`.

Don't think `Average` has anything to do with this as constructing the `Computation` manually produces the same bug.

```julia
c = Computation(wT, model.pressures.pHY′)
c.result
Field located at (Cell, Cell, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (18, 18, 18)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=16, Ny=16, Nz=16)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)
```

Will try to look into this tomorrow.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR refactors the `NetCDFOutputWriter` to use `FieldSlicer` (which cleans it up a bit) and adds support for time-averaging for NetCDF. All the existing NetCDF tests pass (of which there are quite a few).

I also added a test for strided windowed time averaging of horizontal averages for `NetCDFOutputWriter`. Oceananigans solves `∂c/∂t = - λ(x, y, z) c` where `λ(x, y, z) = x + (1 - y)^2 + tanh(z)` which is independent exoponential decay at every grid point so you can analytically compute what the output of the horizontal average and the strided windowed time average should be. Thankfully the test passes :tada:

I also reorganized `test_output_writers.jl` quite a bit. I think it's big enough that it should be split up into multiple files but I'll leave this for a future PR since it would make reviewing this PR's diff difficult.

Would be nice if NetCDF accepted a named tuple for `outputs` and had a less clunky interface than just dicts for everything. Might have to wait for a future PR though...

X-Ref: https://github.com/Alexander-Barth/NCDatasets.jl/issues/105

Resolves #876

### CODE REVIEW

File: src/OutputWriters/netcdf_output_writer.jl [hunk 1]
```diff
@@ -26,20 +39,21 @@ const default_output_attributes = Dict(
...
-                slices :: S
+          field_slicer :: S
+            array_type :: A
               previous :: Float64
                verbose :: Bool
 end
 
 """
-    NetCDFOutputWriter(model, outputs; filename, iteration_interval=nothing, time_interval=nothing,
+    NetCDFOutputWriter(model, outputs; filepath, iteration_interval=nothing, time_interval=nothing,
```
Comment (glwagner) [inline src/OutputWriters/netcdf_output_writer.jl:56]: In `JLD2OutputWriter` we have two arguments: `dir`, and `filename`. This is combined internally into a `filepath`. I suppose the reasoning is that its common to have multiple output writers (which you'd want to save data into the same directory), but different names. Having two keyword arguments makes that slightly more convenient. I'm ok with using `filepath` instead if there's a good argument. But I think both output writers should have the same interface?

Comment (glwagner) [reply src/OutputWriters/netcdf_output_writer.jl:56]: Actually, looks like `JLD2OutputWriter` uses "prefix":

https://github.com/CliMA/Oceananigans.jl/blob/2281da8a6c1857024c38c622f2729fb760645f61/src/OutputWriters/jld2_output_writer.jl#L30

The distinction is that prefix is appended with various endings (eg `.jld2`, or sometimes `_part$n.jld2`) to complete the file name.

Happy to change `JLD2OutputWriter` to conform to a style we think is clearest --- let's discuss.

Comment (glwagner) [reply src/OutputWriters/netcdf_output_writer.jl:56]: I actually think a friendly interface would use `filename`, but allow the user to give only the first "part" of the file name, leaving out `.jld2` or `.nc` --- which are already made obvious by the name of the object (`NetCDF*` or `JLD2*`). This has the advantage that this keyword argument doesn't need to be changed if switching between output writers.

**Comment by glwagner** [comment]
Does `AveragedField` and `ComputedField` work seamlessly with `NetCDFOutputWriter` now? If so, we can nuke `average.jl` and `computation.jl`.

File: src/OutputWriters/netcdf_output_writer.jl (hunk 1 above)
Comment (ali-ramadhan) [reply src/OutputWriters/netcdf_output_writer.jl:56]: Yeah I agree a shared interface would be good, but I think the reason `JLD2OutputWriter` has both a `dir` and `filename` is to support file splitting with automatic file naming.

The `filepath` should include both the directory and filename so I think having two arguments is kind of clunky. Ideally both would just use a `filepath`.

I guess `NetCDFOutputWriter` gets away with just a `filepath` because it doesn't support file splitting so the filename never changes during the course of a simulation.

We could modify the `JLD2OutputWriter` to just take in a `filepath`. Two possible solutions are:
1. File splitting could be supported by injecting `part1`, `part2`, etc. appropriately into the `filepath`, or
2. via another kwarg `filename_pattern` that's a function `filename_pattern(n::Int)::String` that returns the filename for part `n`.

Comment (ali-ramadhan) [reply src/OutputWriters/netcdf_output_writer.jl:56]: A third alternative would be to remove the ability to split files, but I think this is a bad idea. While there is no file size limit for HDF5 and we typically don't split files since our files aren't huge, there will be users in the future who will run huge models and need this functionality due to memory limits (or even filesystem limits).

**Comment by ali-ramadhan** [comment]
> Does `AveragedField` and `ComputedField` work seamlessly with `NetCDFOutputWriter` now? If so, we can nuke `average.jl` and `computation.jl`.

Yes good point. I'll nuke them and probably just need to do some `%s/Average/AveragedField/gc`.

File: src/OutputWriters/netcdf_output_writer.jl (hunk 1 above)
Comment (glwagner) [reply src/OutputWriters/netcdf_output_writer.jl:56]: > I guess NetCDFOutputWriter gets away with just a filepath because it doesn't support file splitting so the filename never changes during the course of a simulation.

Do we plan on supporting file splitting for `NetCDFOutputWriter` in the future?

Comment (ali-ramadhan) [reply src/OutputWriters/netcdf_output_writer.jl:56]: Yeah I think we should. We should continue discussion in #884 (where it seems we already liked `filepath` haha).
