### PR TITLE
(v0.102.3) Fix NetCDF outputs on vertically stretched lat-lon grids, test non-hydrostatic η output, and fix non-hydrostatic free surface time stepping

### LINKED ISSUE #5029: Cannot output η via a `NetCDFWriter` on a vertically stretched lat-lon grid
I think the code is trying to pass a `CuArray` directly to the NetCDF C library which won't work. It needs to be converted to a CPU `Array`.

I think this isn't an issue on regular grids because the coordinates are ranges. But on stretched grids the coordinates are arrays which may need to be converted to CPU `Array`s. So the issue is more general than η. We do test outputting stretched grids in `test_netcdf_vertically_stretched_grid_output` but only on a rectilinear grid.

I'll open a PR with a test that fails, then introduce a fix for this issue.

---

MWE:

```julia
using CUDA
using NCDatasets
using Oceananigans

Nz = 4
grid = LatitudeLongitudeGrid(GPU();
    topology = (Bounded, Bounded, Bounded),
    size = (8, 8, Nz),
    longitude = (-1, 1),
    latitude = (-1, 1),
    z = [k^2 - 100 for k in 0:Nz]
)

model = HydrostaticFreeSurfaceModel(; grid)
simulation = Simulation(model, Δt=1, stop_iteration=1)

simulation.output_writers[:test] = NetCDFWriter(
    model,
    (; η = model.free_surface.η);
    filename = "test.nc",
    schedule = IterationInterval(1),
    overwrite_existing = true
)
```

Error:

```
ERROR: LoadError: ArgumentError: Illegal conversion of a CUDA.DeviceMemory to a Ptr{Float64}
Stacktrace:
  [1] convert(T::Type{Ptr{Float64}}, mem::CUDA.DeviceMemory)
    @ CUDA ~/.julia/packages/CUDA/x8d2s/lib/cudadrv/memory.jl:16
  [2] convert(::Type{Ptr{Float64}}, managed::CUDA.Managed{CUDA.DeviceMemory})
    @ CUDA ~/.julia/packages/CUDA/x8d2s/src/memory.jl:583
  [3] unsafe_convert(typ::Type{Ptr{Float64}}, x::CuArray{Float64, 1, CUDA.DeviceMemory})
    @ CUDA ~/.julia/packages/CUDA/x8d2s/src/array.jl:464
  [4] unsafe_convert(::Type{Ptr{Nothing}}, a::CuArray{Float64, 1, CUDA.DeviceMemory})
    @ Base ./pointer.jl:64
  [5] nc_put_vars(ncid::Int32, varid::Int32, startp::Vector{Int64}, countp::Vector{Int64}, stridep::Vector{Int64}, op::CuArray{Float64, 1, CUDA.DeviceMemory})
    @ NCDatasets ~/.julia/packages/NCDatasets/W31Xc/src/netcdf_c.jl:992
  [6] _write_data_to_nc(v::NCDatasets.Variable{Float64, 1, NCDataset{Nothing, Missing}}, data::CuArray{Float64, 1, CUDA.DeviceMemory}, indexes::Base.OneTo{Int64})
    @ NCDatasets ~/.julia/packages/NCDatasets/W31Xc/src/variable.jl:433
  [7] writeblock!(v::NCDatasets.Variable{Float64, 1, NCDataset{Nothing, Missing}}, data::CuArray{Float64, 1, CUDA.DeviceMemory}, indexes::Base.OneTo{Int64})
    @ NCDatasets ~/.julia/packages/NCDatasets/W31Xc/src/variable.jl:419
  [8] writeblock!(v::CommonDataModel.CFVariable{Float64, 1, NCDatasets.Variable{…}, CommonDataModel.Attributes{…}, @NamedTuple{…}}, data::CuArray{Float64, 1, CUDA.DeviceMemory}, indexes::Base.OneTo{Int64})
    @ CommonDataModel ~/.julia/packages/CommonDataModel/b3BkC/src/cfvariable.jl:516
  [9] writeblock_checked!(a::CommonDataModel.CFVariable{Float64, 1, NCDatasets.Variable{…}, CommonDataModel.Attributes{…}, @NamedTuple{…}}, values::CuArray{Float64, 1, CUDA.DeviceMemory}, i::Base.OneTo{Int64})
    @ DiskArrays ~/.julia/packages/DiskArrays/cJ8RQ/src/indexing.jl:301
 [10] setindex_disk_nobatch!(a::CommonDataModel.CFVariable{Float64, 1, NCDatasets.Variable{…}, CommonDataModel.Attributes{…}, @NamedTuple{…}}, values::CuArray{Float64, 1, CUDA.DeviceMemory}, i::Tuple{Base.OneTo{…}})
    @ DiskArrays ~/.julia/packages/DiskArrays/cJ8RQ/src/indexing.jl:178
 [11] setindex_disk!(a::CommonDataModel.CFVariable{Float64, 1, NCDatasets.Variable{…}, CommonDataModel.Attributes{…}, @NamedTuple{…}}, values::CuArray{Float64, 1, CUDA.DeviceMemory}, i::Base.OneTo{Int64})
    @ DiskArrays ~/.julia/packages/DiskArrays/cJ8RQ/src/indexing.jl:137
 [12] setindex!(a::CommonDataModel.CFVariable{Float64, 1, NCDatasets.Variable{…}, CommonDataModel.Attributes{…}, @NamedTuple{…}}, v::CuArray{Float64, 1, CUDA.DeviceMemory}, i::Base.OneTo{Int64})
    @ DiskArrays ~/.julia/packages/DiskArrays/cJ8RQ/src/indexing.jl:324
 [13] _defVar(ds::NCDataset{Nothing, Missing}, name::String, data::CuArray{Float64, 1, CUDA.DeviceMemory}, nctype::Type, vardimnames::Tuple{String}; attrib::Dict{String, String}, kwargs::@Kwargs{})
    @ CommonDataModel ~/.julia/packages/CommonDataModel/b3BkC/src/variable.jl:185
 [14] _defVar
    @ ~/.julia/packages/CommonDataModel/b3BkC/src/variable.jl:126 [inlined]
 [15] #defVar#4
    @ ~/.julia/packages/CommonDataModel/b3BkC/src/variable.jl:104 [inlined]
 [16] create_spatial_dimensions!(dataset::NCDataset{Nothing, Missing}, dims::OrderedCollections.OrderedDict{String, AbstractVector{Float64}}, attributes_dict::Dict{String, Dict{String, String}}; dimension_type::Type, kwargs::@Kwargs{})
    @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:228
 [17] create_field_dimensions!(ds::NCDataset{…}, fd::Field{…}, dimension_name_generator::Function; time_dependent::Bool, with_halos::Bool, array_type::Type, dimension_type::Type)
    @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:170
 [18] create_field_dimensions!
    @ ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:161 [inlined]
 [19] defVar(ds::NCDataset{…}, field_name::String, fd::Field{…}; array_type::Type, time_dependent::Bool, with_halos::Bool, dimension_name_generator::Function, dimension_type::Type, write_data::Bool, kwargs::@Kwargs{…})
    @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:128
 [20] define_output_variable!(model::HydrostaticFreeSurfaceModel{…}, dataset::NCDataset{…}, output::Field{…}, output_name::String; array_type::Type, deflatelevel::Int64, attrib::Dict{…}, dimension_name_generator::Function, time_dependent::Bool, with_halos::Bool, dimensions::Dict{…}, filepath::String, dimension_type::Type)
    @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:1403
 [21] initialize_nc_file(model::HydrostaticFreeSurfaceModel{…}, grid::LatitudeLongitudeGrid{…}, filepath::String, outputs::Dict{…}, schedule::IterationInterval, array_type::Type, indices::Tuple{…}, global_attributes::Dict{…}, output_attributes::Dict{…}, dimensions::Dict{…}, with_halos::Bool, include_grid_metrics::Bool, overwrite_existing::Bool, deflatelevel::Int64, dimension_name_generator::typeof(Oceananigans.OutputWriters.trilocation_dim_name), dimension_type::Type)
    @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:1323
 [22] NetCDFWriter(model::HydrostaticFreeSurfaceModel{…}, outputs::@NamedTuple{…}; filename::String, schedule::IterationInterval, grid::LatitudeLongitudeGrid{…}, dir::String, array_type::Type, indices::Tuple{…}, global_attributes::Dict{…}, output_attributes::Dict{…}, dimensions::Dict{…}, with_halos::Bool, include_grid_metrics::Bool, overwrite_existing::Bool, verbose::Bool, deflatelevel::Int64, part::Int64, file_splitting::Oceananigans.OutputWriters.NoFileSplitting, dimension_name_generator::typeof(Oceananigans.OutputWriters.trilocation_dim_name), dimension_type::Type)
    @ OceananigansNCDatasetsExt ~/.julia/packages/Oceananigans/ivuPr/ext/OceananigansNCDatasetsExt.jl:1180
 [23] top-level scope
    @ ~/atdepth/Chitin.jl/examples/regional_simulation/mwe_netcdf_gpu_stretched_grid.jl:32
 [24] include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./Base.jl:307
 [25] top-level scope
    @ REPL[1]:1
in expression starting at /home/alir/atdepth/Chitin.jl/examples/regional_simulation/mwe_netcdf_gpu_stretched_grid.jl:32
Some type information was truncated. Use `show(err)` to see complete types.
```

---

Environment:

```
julia> versioninfo()
Julia Version 1.12.2
Commit ca9b6662be4 (2025-11-20 16:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 48 × AMD Ryzen Threadripper 7960X 24-Cores
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver4)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 48 virtual cores)
Environment:
  LD_PRELOAD = /usr/NX/lib/libnxegl.so

(Oceananigans) pkg> st
Project Oceananigans v0.102.1
Status `~/atdepth/Oceananigans.jl/Project.toml`
  [79e6a3ab] Adapt v4.4.0
  [a8cc5b0e] Crayons v4.1.1
  [7445602f] CubedSphere v0.3.4
  [b4f34e82] Distances v0.10.12
  [ffbed154] DocStringExtensions v0.9.5
  [7a1cc6ca] FFTW v1.10.0
  [46192b85] GPUArraysCore v0.2.0
  [c27321d9] Glob v1.3.1
  [033835bb] JLD2 v0.6.3
  [63c18a36] KernelAbstractions v0.9.39
  [ba0b0d4f] Krylov v0.10.3
  [da04e1cc] MPI v0.20.23
  [46d2c3a1] MuladdMacro v0.2.4
  [6fe1bfb0] OffsetArrays v1.17.0
  [bac558e1] OrderedCollections v1.8.1
  [a3311ec8] ReactantCore v0.1.16
  [6038ab10] Rotations v1.7.1
  [d496a93d] SeawaterPolynomials v0.3.10
  [90137ffa] StaticArrays v1.9.15
  [10745b16] Statistics v1.11.1
  [09ab397b] StructArrays v0.7.2
  [ade2ca70] Dates v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [37e2e46d] LinearAlgebra v1.12.0
  [56ddb016] Logging v1.11.0
  [44cfe95a] Pkg v1.12.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [2f01184e] SparseArrays v1.12.0
```

### LINKED ISSUE #5032: Cannot time step a `NonhydrostaticModel` with an `ImplicitFreeSurface` on a CUDA GPU
Not sure if this is supposed to be supported following PR #4740 but as part of testing #5030 I realized we cannot time step a non-hydrostatic model with an implicit free surface on the GPU.

I'll try to do some debugging, but opening this issue to document that this configuration does not currently work.

---

MWE:

```julia
using CUDA
using Oceananigans
using Oceananigans.Models.HydrostaticFreeSurfaceModels: ImplicitFreeSurface

grid = RectilinearGrid(CPU();
    topology = (Bounded, Bounded, Bounded),
    size = (8, 8, 4),
    x = (-1, 1),
    y = (-1, 1),
    z = (-1, 0)
)

model = NonhydrostaticModel(; grid,
    free_surface = ImplicitFreeSurface(),
    closure = ScalarDiffusivity(ν=4e-2, κ=4e-2),
    buoyancy = SeawaterBuoyancy(),
    tracers = (:T, :S)
)

time_step!(model, 0.1)
```

Error:

```
ERROR: LoadError: GPU compilation of MethodInstance for Oceananigans.BoundaryConditions.gpu__fill_bottom_and_top_halo!(::KernelAbstractions.CompilerMetadata{…}, ::OffsetArrays.OffsetArray{…}, ::Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, ::BoundaryCondition{…}, ::Tuple{…}, ::RectilinearGrid{…}, ::Tuple{}) failed
KernelError: passing non-bitstype argument

Argument 5 to your kernel function is of type BoundaryCondition{Oceananigans.BoundaryConditions.Mixed, Oceananigans.BoundaryConditions.MixedCondition{Base.RefValue{Float64}, Field{Center, Center, Nothing, Nothing, RectilinearGrid{Float64, Bounded, Bounded, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64, Float64}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, GPU{CUDABackend}}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, CuArray{Float64, 3, CUDA.DeviceMemory}}, Float64, FieldBoundaryConditions{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Nothing, Nothing, Nothing, @NamedTuple{bottom_and_top::Nothing, south_and_north::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_south_and_north_halo!)}, west_and_east::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_west_and_east_halo!)}}, @NamedTuple{bottom_and_top::Tuple{Nothing, Nothing}, south_and_north::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}, west_and_east::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}}}, Nothing, Nothing}}}, which is not a bitstype:
  .condition is of type Oceananigans.BoundaryConditions.MixedCondition{Base.RefValue{Float64}, Field{Center, Center, Nothing, Nothing, RectilinearGrid{Float64, Bounded, Bounded, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64, Float64}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, GPU{CUDABackend}}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, CuArray{Float64, 3, CUDA.DeviceMemory}}, Float64, FieldBoundaryConditions{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Nothing, Nothing, Nothing, @NamedTuple{bottom_and_top::Nothing, south_and_north::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_south_and_north_halo!)}, west_and_east::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_west_and_east_halo!)}}, @NamedTuple{bottom_and_top::Tuple{Nothing, Nothing}, south_and_north::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}, west_and_east::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}}}, Nothing, Nothing}} which is not isbits.
    .coefficient is of type Base.RefValue{Float64} which is not isbits.
    .inhomogeneity is of type Field{Center, Center, Nothing, Nothing, RectilinearGrid{Float64, Bounded, Bounded, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64, Float64}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, GPU{CUDABackend}}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, CuArray{Float64, 3, CUDA.DeviceMemory}}, Float64, FieldBoundaryConditions{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Nothing, Nothing, Nothing, @NamedTuple{bottom_and_top::Nothing, south_and_north::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_south_and_north_halo!)}, west_and_east::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_west_and_east_halo!)}}, @NamedTuple{bottom_and_top::Tuple{Nothing, Nothing}, south_and_north::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}, west_and_east::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}}}, Nothing, Nothing} which is not isbits.
      .data is of type OffsetArrays.OffsetArray{Float64, 3, CuArray{Float64, 3, CUDA.DeviceMemory}} which is not isbits.
        .parent is of type CuArray{Float64, 3, CUDA.DeviceMemory} which is not isbits.
          .data is of type GPUArrays.DataRef{CUDA.Managed{CUDA.DeviceMemory}} which is not isbits.
            .rc is of type GPUArrays.RefCounted{CUDA.Managed{CUDA.DeviceMemory}} which is not isbits.
              .obj is of type CUDA.Managed{CUDA.DeviceMemory} which is not isbits.
                .stream is of type CuStream which is not isbits.
                  .ctx is of type Union{Nothing, CuContext} which is not isbits.
              .finalizer is of type Any which is not isbits.
              .count is of type Base.Threads.Atomic{Int64} which is not isbits.
      .boundary_conditions is of type FieldBoundaryConditions{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Nothing, Nothing, Nothing, @NamedTuple{bottom_and_top::Nothing, south_and_north::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_south_and_north_halo!)}, west_and_east::KernelAbstractions.Kernel{CUDABackend, KernelAbstractions.NDIteration.StaticSize{(16, 16)}, KernelAbstractions.NDIteration.StaticSize{(8, 1)}, typeof(Oceananigans.BoundaryConditions.gpu__fill_west_and_east_halo!)}}, @NamedTuple{bottom_and_top::Tuple{Nothing, Nothing}, south_and_north::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}, west_and_east::Tuple{Oceananigans.BoundaryConditions.NoFluxBoundaryCondition, Oceananigans.BoundaryConditions.NoFluxBoundaryCondition}}} which is not isbits.


Only bitstypes, which are "plain data" types that are immutable
and contain no references to other values, can be used in GPU kernels.
For more information, see the `Base.isbitstype` function.

Stacktrace:
  [1] check_invocation(job::GPUCompiler.CompilerJob)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/validation.jl:108
  [2] compile_unhooked(output::Symbol, job::GPUCompiler.CompilerJob; kwargs::@Kwargs{})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/driver.jl:87
  [3] compile_unhooked
    @ ~/.julia/packages/GPUCompiler/j4HFa/src/driver.jl:80 [inlined]
  [4] compile(target::Symbol, job::GPUCompiler.CompilerJob; kwargs::@Kwargs{})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/driver.jl:67
  [5] compile
    @ ~/.julia/packages/GPUCompiler/j4HFa/src/driver.jl:55 [inlined]
  [6] #compile##0
    @ ~/.julia/packages/CUDA/x8d2s/src/compiler/compilation.jl:250 [inlined]
  [7] JuliaContext(f::CUDA.var"#compile##0#compile##1"{GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams}}; kwargs::@Kwargs{})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/driver.jl:34
  [8] JuliaContext(f::Function)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/driver.jl:25
  [9] compile(job::GPUCompiler.CompilerJob)
    @ CUDA ~/.julia/packages/CUDA/x8d2s/src/compiler/compilation.jl:249
 [10] actual_compilation(cache::Dict{Any, CuFunction}, src::Core.MethodInstance, world::UInt64, cfg::GPUCompiler.CompilerConfig{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams}, compiler::typeof(CUDA.compile), linker::typeof(CUDA.link))
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/execution.jl:245
 [11] cached_compilation(cache::Dict{Any, CuFunction}, src::Core.MethodInstance, cfg::GPUCompiler.CompilerConfig{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams}, compiler::Function, linker::Function)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/j4HFa/src/execution.jl:159
 [12] macro expansion
    @ ~/.julia/packages/CUDA/x8d2s/src/compiler/execution.jl:373 [inlined]
 [13] macro expansion
    @ ./lock.jl:376 [inlined]
 [14] cufunction(f::typeof(Oceananigans.BoundaryConditions.gpu__fill_bottom_and_top_halo!), tt::Type{Tuple{…}}; kwargs::@Kwargs{always_inline::Bool, maxthreads::Int64})
    @ CUDA ~/.julia/packages/CUDA/x8d2s/src/compiler/execution.jl:368
 [15] macro expansion
    @ ~/.julia/packages/CUDA/x8d2s/src/compiler/execution.jl:112 [inlined]
 [16] (::KernelAbstractions.Kernel{…})(::OffsetArrays.OffsetArray{…}, ::Vararg{…}; ndrange::Nothing, workgroupsize::Nothing)
    @ CUDA.CUDAKernels ~/.julia/packages/CUDA/x8d2s/src/CUDAKernels.jl:127
 [17] Kernel
    @ ~/.julia/packages/CUDA/x8d2s/src/CUDAKernels.jl:113 [inlined]
 [18] fill_halo_event!
    @ ~/atdepth/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions.jl:40 [inlined]
 [19] fill_halo_regions!(::OffsetArrays.OffsetArray{…}, ::@NamedTuple{…}, ::Tuple{…}, ::Tuple{…}, ::RectilinearGrid{…}; kwargs::@Kwargs{})
    @ Oceananigans.BoundaryConditions ~/atdepth/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions.jl:32
 [20] fill_halo_regions!
    @ ~/atdepth/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions.jl:25 [inlined]
 [21] #fill_halo_regions!#65
    @ ~/atdepth/Oceananigans.jl/src/Fields/field.jl:852 [inlined]
 [22] fill_halo_regions!
    @ ~/atdepth/Oceananigans.jl/src/Fields/field.jl:838 [inlined]
 [23] compute_pressure_correction!(model::NonhydrostaticModel{…}, Δt::Float64)
    @ Oceananigans.Models.NonhydrostaticModels ~/atdepth/Oceananigans.jl/src/Models/NonhydrostaticModels/pressure_correction.jl:19
 [24] time_step!(model::NonhydrostaticModel{…}, Δt::Float64; callbacks::Vector{…})
    @ Oceananigans.TimeSteppers ~/atdepth/Oceananigans.jl/src/TimeSteppers/runge_kutta_3.jl:124
 [25] time_step!(model::NonhydrostaticModel{…}, Δt::Float64)
    @ Oceananigans.TimeSteppers ~/atdepth/Oceananigans.jl/src/TimeSteppers/runge_kutta_3.jl:94
 [26] top-level scope
    @ ~/atdepth/Oceananigans.jl/test_nh_free_surface.jl:20
 [27] include(mapexpr::Function, mod::Module, _path::String)
    @ Base ./Base.jl:307
 [28] top-level scope
    @ REPL[1]:1
in expression starting at /home/alir/atdepth/Oceananigans.jl/test_nh_free_surface.jl:20
Some type information was truncated. Use `show(err)` to see complete types.
```

---

Environment:

```
julia> versioninfo()
Julia Version 1.12.2
Commit ca9b6662be4 (2025-11-20 16:25 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 48 × AMD Ryzen Threadripper 7960X 24-Cores
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver4)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 48 virtual cores)
Environment:
  LD_PRELOAD = /usr/NX/lib/libnxegl.so

julia> CUDA.versioninfo()
CUDA toolchain: 
- runtime 13.0, artifact installation
- driver 580.95.5 for 13.0
- compiler 13.0

CUDA libraries: 
- CUBLAS: 13.1.0
- CURAND: 10.4.0
- CUFFT: 12.0.0
- CUSOLVER: 12.0.4
- CUSPARSE: 12.6.3
- CUPTI: 2025.3.1 (API 13.0.1)
- NVML: 13.0.0+580.95.5

Julia packages: 
- CUDA: 5.9.5
- CUDA_Driver_jll: 13.0.2+0
- CUDA_Compiler_jll: 0.3.0+0
- CUDA_Runtime_jll: 0.19.2+0

Toolchain:
- Julia: 1.12.2
- LLVM: 18.1.7

1 device:
  0: NVIDIA GeForce RTX 4090 (sm_89, 19.144 GiB / 23.988 GiB available)

(Oceananigans) pkg> st
Project Oceananigans v0.102.3
Status `~/atdepth/Oceananigans.jl/Project.toml`
  [79e6a3ab] Adapt v4.4.0
  [a8cc5b0e] Crayons v4.1.1
  [7445602f] CubedSphere v0.3.4
  [b4f34e82] Distances v0.10.12
  [ffbed154] DocStringExtensions v0.9.5
  [7a1cc6ca] FFTW v1.10.0
  [46192b85] GPUArraysCore v0.2.0
  [c27321d9] Glob v1.3.1
  [033835bb] JLD2 v0.6.3
  [63c18a36] KernelAbstractions v0.9.39
  [ba0b0d4f] Krylov v0.10.3
  [da04e1cc] MPI v0.20.23
  [46d2c3a1] MuladdMacro v0.2.4
  [6fe1bfb0] OffsetArrays v1.17.0
  [bac558e1] OrderedCollections v1.8.1
  [a3311ec8] ReactantCore v0.1.16
  [6038ab10] Rotations v1.7.1
  [d496a93d] SeawaterPolynomials v0.3.10
  [90137ffa] StaticArrays v1.9.15
  [10745b16] Statistics v1.11.1
  [09ab397b] StructArrays v0.7.2
  [ade2ca70] Dates v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [37e2e46d] LinearAlgebra v1.12.0
  [56ddb016] Logging v1.11.0
  [44cfe95a] Pkg v1.12.0
  [de0858da] Printf v1.11.0
  [9a3f8284] Random v1.11.0
  [2f01184e] SparseArrays v1.12.0
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Tests should fail right now. Once they do, I'll push the fix.

Resolves #5029 
Resolves #5032

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Confirming that the test fails as intended: https://buildkite.com/clima/oceananigans/builds/27414#019b04b3-b5b2-491d-8646-8cdde7e4f3c9/17-4192

File: test/test_netcdf_writer.jl [hunk 1]
```diff
@@ -2513,19 +2513,23 @@ function test_netcdf_overriding_attributes(arch)
     return nothing
 end
 
-function test_netcdf_free_surface_only_output(arch)
+function test_netcdf_free_surface_only_output(arch; immersed=false, vertically_stretched=false)
```
Comment (tomchor) [inline test/test_netcdf_writer.jl]: Nice

**Comment by tomchor** [comment]
Nice job bulking up the tests! Since `NonhydrostaticModel` now also has a free surface, should we also extend the tests further to catch that case?

**Comment by ali-ramadhan** [comment]
Seems like we got some new failures so I'll look into getting all the tests to pass. Happy to add tests for the non-hydrostatic free surface!

**Comment by ali-ramadhan** [comment]
@tomchor Tests should pass now and I added tests for free surface outputs from non-hydrostatic models, although I could only run the tests on the CPU because of #5032.

**Comment by tomchor** [comment]
> @tomchor Tests should pass now and I added tests for free surface outputs from non-hydrostatic models, although I could only run the tests on the CPU because of #5032.

Nice catch there!

**Comment by glwagner** [comment]
I thikn `MixedCondition` just needs an adapt_structure right? We can solve it on this PR and be flying into the future if you like.

**Comment by glwagner** [comment]
eg

```julia
Adapt.adapt_structure(to, mc::MixedCondition) =
    MixedCondition(Adapt.adapt(to, mc.coefficient), Adapt.adapt(to, mc.inhomogeneity))
```

here

https://github.com/CliMA/Oceananigans.jl/blob/129959d13aeff154b770c398dbcd6efc226954cd/src/BoundaryConditions/boundary_condition.jl#L117-L120

**Comment by ali-ramadhan** [comment]
@glwagner Happy to fix non-hydrostatic free surface time stepping here. I agree it's probably just a missing `Adapt.adapt` method. I tried a few things but will document progress in #5032.

**Comment by ali-ramadhan** [comment]
I enabled the NetCDF non-hydrostatic free surface output tests and added some time-stepping tests which should resolve #5032.

Looks like all tests pass except the distributed tests which failed to initialize.

File: test/test_time_stepping.jl [hunk 2]
```diff
@@ -399,6 +414,13 @@ timesteppers = (:QuasiAdamsBashforth2, :RungeKutta3)
         end
     end
 
+    @testset "NonhydrostaticModel with ImplicitFreeSurface" begin
+        for arch in archs, FT in float_types
+            @info "  Testing NonhydrostaticModel with ImplicitFreeSurface time stepping [$FT, $arch]..."
+            @test time_step_nonhydrostatic_model_with_implicit_free_surface_works(arch, FT)
+        end
+    end
```
Comment (tomchor) [inline test/test_time_stepping.jl:422]: :heart:
