### PR TITLE
Fix bug when using Lagrangian particles on Flat topologies

### LINKED ISSUE #3545: Lagrangian particles on Flat topology
I was trying to add some Lagrangian particles to a 2D simulation I was running but Lagrangian particle advection currently assumes that the grid is bounded or periodic in all dimensions. An MWE (on Julia 1.10.1+0.x64.w64.mingw32 and Oceananigans version 0.90.12) that reproduces the issue is:

```
using Oceananigans
NX, NZ = 16, 16
grid = RectilinearGrid(size=(NX,NZ), x=(0,1), z=(0,1), topology=(Periodic, Flat, Bounded))
# initialise some particles at the cell centres
x₀ = reshape(xnodes(grid, Center()) * ones(NZ)', NX * NZ)
y₀ = zeros(NX * NZ)
z₀ = reshape(ones(NX) * znodes(grid, Center())', NX * NZ)
model = NonhydrostaticModel(; grid, particles=LagrangianParticles(x=x₀, y=y₀, z=z₀))
simulation = Simulation(model; Δt=1, stop_iteration=5)
run!(simulation)
```

with output

```
[ Info: Initializing simulation...
[ Info:     ... simulation initialization complete (115.810 ms)
[ Info: Executing initial time step...
ERROR: LoadError: MethodError: no method matching unsafe_trunc(::Type{Int64}, ::Nothing)

Closest candidates are:
  unsafe_trunc(::Type{Int64}, ::Union{Float16, Float32, Float64})
   @ Base float.jl:336
  unsafe_trunc(::Type{<:Integer}, ::BFloat16s.BFloat16)
   @ BFloat16s C:\Users\hildi\.julia\packages\BFloat16s\u3WQc\src\bfloat16.jl:288
  unsafe_trunc(::Type{T}, ::BigFloat) where T<:Integer
   @ Base mpfr.jl:358
  ...

Stacktrace:
  [1] advect_particle
    @ C:\Users\hildi\.julia\packages\Oceananigans\kBe5X\src\Models\LagrangianParticleTracking\lagrangian_particle_advection.jl:81 [inlined]

...
```

The offending line is https://github.com/CliMA/Oceananigans.jl/blob/ce4fabaa0c6ddfd20ae43c671bbaec7bb5dae847/src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl#L81 

which fails because 
https://github.com/CliMA/Oceananigans.jl/blob/ce4fabaa0c6ddfd20ae43c671bbaec7bb5dae847/src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl#L79
returns `j = nothing` when `y` is `Flat`.

However, I think that in general `advect_particle` is not written with Flat topologies in mind. For example, there are no boundary conditions implemented for the Flat topology. 

The ability to do 2D (and 1D) Lagrangian particles would be quite useful. Although, it's not obvious what it means to advect a particle in the Flat direction. Skipping that direction entirely or simply accumulating the displacement in that direction (as I do below) could both be valid in some contexts. (For my original use case I don't care what happens in `y`.)

Finally, for this particular simple example, propagating `j = nothing` through `unsafe_trunc` and defining some boundary conditions was sufficient to make the example run.

```
using Oceananigans

Base.unsafe_trunc(::T, ::Nothing) where {T} = nothing
Oceananigans.Models.LagrangianParticleTracking.enforce_boundary_conditions(::Flat,  x, xᴸ, xᴿ, Cʳ) = x

NX, NZ = 16, 16
grid = RectilinearGrid(size=(NX,NZ), x=(0,1), z=(0,1), topology=(Periodic, Flat, Bounded))
# initialise some particles at the cell centres
x₀ = reshape(xnodes(grid, Center()) * ones(NZ)', NX * NZ)
y₀ = zeros(NX * NZ)
z₀ = reshape(ones(NX) * znodes(grid, Center())', NX * NZ)
model = NonhydrostaticModel(; grid, particles=LagrangianParticles(x=x₀, y=y₀, z=z₀))
simulation = Simulation(model; Δt=1, stop_iteration=5)
run!(simulation)
```
 I'm not sure whether propagating `j = nothing` forward is a sensible or desirable thing to do, or if it even works in other cases, but I thought that I'd point out that it works here.

### PR DESCRIPTION
**Pull request by Jamie-Hilditch**
Fixes #3545 

- Add `truncate_fractional_indices` to handle the truncation of `nothing` indices returned by `fractional_indices` for `Flat` dimensions. `nothing` indices are "truncated" to 1.
- `truncate_fractional_indices` used in `advect_particle` and `bounce_immersed_particle`.
- Add method of `enforce_boundary_conditions` for `Flat` boundaries. This method does not modify the particle position.

### CODE REVIEW

File: src/Fields/interpolate.jl [hunk 1]
```diff
@@ -211,6 +211,23 @@ end
     return (ii, jj, kk)
 end
 
+"""
+    truncate_fractional_indices(fi, fj, fk)
+
+Truncate _fractional_ indices output from `fractional_indices` to integer indices, dealing
```
Comment (navidcy) [inline src/Fields/interpolate.jl:217]:
```suggestion
Truncate _fractional_ indices output from fractional indices `fi, fj, fk` to integer indices, dealing
```

File: src/Fields/interpolate.jl [hunk 2]
```diff
@@ -211,6 +211,23 @@ end
...
 end
 
+"""
+    truncate_fractional_indices(fi, fj, fk)
+
+Truncate _fractional_ indices output from fractional indices `fi, fj, fk` to integer indices, dealing
+with `nothing` indices for `Flat` domains.
+"""
+@inline function truncate_fractional_indices(fi, fj, fk)
+    i = _truncate_fractional_index(fi)
```
Comment (glwagner) [inline src/Fields/interpolate.jl:221]:
```suggestion
    i = truncate_fractional_index(fi)
```

since one function is "indices" and the other is "index" I don't think you need to disambiguiate the function names with a leading underscore.

**Review by glwagner — APPROVED** [review]
Looks great!

Should we add a test to make sure this doesn't break in the future? The low bar is just to test that interpolation doesn't error with a `Flat` direction (we don't have to test correctness, though we could do that too)

File: src/Fields/interpolate.jl (hunk 2 above)
Comment (Jamie-Hilditch) [reply src/Fields/interpolate.jl]: I've changed the name

**Comment by Jamie-Hilditch** [comment]
> Should we add a test to make sure this doesn't break in the future? The low bar is just to test that interpolation doesn't error with a `Flat` direction (we don't have to test correctness, though we could do that too)

Yes, probably should. The current tests have a hard coded topology 

```
function run_simple_particle_tracking_tests(arch, timestepper; vertically_stretched=false)
    topo = (Periodic, Periodic, Bounded)


    Nx = Ny = Nz = 5
...
```
We could add tests to check that simulations can run on different topologies without error. Alternatively, I don't see anything in the existing tests that would not be supported if one or more of the  `Periodic` dimensions was `Flat`. So we could extent the existing tests to allow for different topologies.

**Comment by navidcy** [comment]
We can do something like this?

```Julia
topologies = ((Periodic, Periodic, Bounded), (Periodic, Flat, Bounded))

for topo in topologies
    function run_simple_particle_tracking_tests(arch, timestepper; vertically_stretched=false)
        topo = topo ....

```

**Comment by Jamie-Hilditch** [comment]
I think so. The only thing we'd have to add is a little bit of logic when constructing the grid.

**Comment by navidcy** [comment]
E.g., 

```Julia
topologies = ((Periodic, Bounded, Bounded), (Periodic, Flat, Bounded))
sizes = ((5, 5, 5), (5, 5))

for (topo, size) in zip(topologies, sizes)
    println(topo)
    println(size)
end
```

```Julia
topo = (Periodic, Bounded, Bounded)
size = (5, 5, 5)
topo = (Periodic, Flat, Bounded)
size = (5, 5)
```

**Comment by glwagner** [comment]
> Yeah that would work. It's a bit weird to pass `y=(-1,1)` to the grid constructor when `y` is `Flat` but it seems to be ignored. An alternative would be to pass the grid as an input to `run_simple_particle_tracking_tests` and move all the grid construction logic (including the stretched vertical grid) to separate functions.

Maybe better is to create a list of grids:

```julia
three_dim_grid = RectilinearGrid(arch, ...)
x_flat_grid = RectilinearGrid(arch, topology=(Flat, Periodic, Bounded), ...)
```

etc, then pass the `grid` into `run_simple_particle_tracking_tests`

**Comment by navidcy** [comment]
@glwagner's suggestion is cleaner!

**Comment by Jamie-Hilditch** [comment]
How about something like this

```julia
archs = (CPU(),) # just to make this code run

timesteppers = (:QuasiAdamsBashforth2, :RungeKutta3)
y_topologies = (Periodic(), Flat())
vertical_grids = (uniform=(-1,1), stretched=[-1, -0.5, 0.0, 0.4, 0.7, 1])

lagrangian_particle_test_grid(arch, ::Periodic, z) = RectilinearGrid(arch; topology=(Periodic, Periodic, Bounded), size=(5, 5, 5), x=(-1, 1), y=(-1, 1), z)
lagrangian_particle_test_grid(arch, ::Flat, z) = RectilinearGrid(arch; topology=(Periodic, Flat, Bounded), size=(5, 5), x=(-1, 1), z)

for arch in archs, timestepper in timesteppers, y_topo in y_topologies, (z_grid_type, z) in pairs(vertical_grids)
    @info "  Testing Lagrangian particle tracking [$(typeof(arch)), $timestepper] with y $(typeof(y_topo)) on vertically $z_grid_type grid ..."
    grid = lagrangian_particle_test_grid(arch, y_topo, z)
    # run_simple_particle_tracking_tests(arch, grid, timestepper)
    @show grid
end
```

which would give us these 8 (per architecture) testsets

```julia
[ Info:   Testing Lagrangian particle tracking [CPU, QuasiAdamsBashforth2] with y Periodic on vertically uniform grid ...
grid = 5×5×5 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [-1.0, 1.0) regularly spaced with Δx=0.4
├── Periodic y ∈ [-1.0, 1.0) regularly spaced with Δy=0.4
└── Bounded  z ∈ [-1.0, 1.0] regularly spaced with Δz=0.4
[ Info:   Testing Lagrangian particle tracking [CPU, QuasiAdamsBashforth2] with y Periodic on vertically stretched grid ...
grid = 5×5×5 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [-1.0, 1.0) regularly spaced with Δx=0.4
├── Periodic y ∈ [-1.0, 1.0) regularly spaced with Δy=0.4
└── Bounded  z ∈ [-1.0, 1.0] variably spaced with min(Δz)=0.3, max(Δz)=0.5
[ Info:   Testing Lagrangian particle tracking [CPU, QuasiAdamsBashforth2] with y Flat on vertically uniform grid ...
grid = 5×1×5 RectilinearGrid{Float64, Periodic, Flat, Bounded} on CPU with 3×0×3 halo 
├── Periodic x ∈ [-1.0, 1.0)      regularly spaced with Δx=0.4
├── Flat y
└── Bounded  z ∈ [-1.0, 1.0]      regularly spaced with Δz=0.4
[ Info:   Testing Lagrangian particle tracking [CPU, QuasiAdamsBashforth2] with y Flat on vertically stretched grid ...
grid = 5×1×5 RectilinearGrid{Float64, Periodic, Flat, Bounded} on CPU with 3×0×3 halo
├── Periodic x ∈ [-1.0, 1.0)      regularly spaced with Δx=0.4
├── Flat y
└── Bounded  z ∈ [-1.0, 1.0]      variably spaced with min(Δz)=0.3, max(Δz)=0.5       
[ Info:   Testing Lagrangian particle tracking [CPU, RungeKutta3] with y Periodic on vertically uniform grid ...
grid = 5×5×5 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [-1.0, 1.0) regularly spaced with Δx=0.4
├── Periodic y ∈ [-1.0, 1.0) regularly spaced with Δy=0.4
└── Bounded  z ∈ [-1.0, 1.0] regularly spaced with Δz=0.4
[ Info:   Testing Lagrangian particle tracking [CPU, RungeKutta3] with y Periodic on vertically stretched grid ...
grid = 5×5×5 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 3×3×3 halo
├── Periodic x ∈ [-1.0, 1.0) regularly spaced with Δx=0.4
├── Periodic y ∈ [-1.0, 1.0) regularly spaced with Δy=0.4
└── Bounded  z ∈ [-1.0, 1.0] variably spaced with min(Δz)=0.3, max(Δz)=0.5
[ Info:   Testing Lagrangian particle tracking [CPU, RungeKutta3] with y Flat on vertically uniform grid ...
grid = 5×1×5 RectilinearGrid{Float64, Periodic, Flat, Bounded} on CPU with 3×0×3 halo 
├── Periodic x ∈ [-1.0, 1.0)      regularly spaced with Δx=0.4
├── Flat y
└── Bounded  z ∈ [-1.0, 1.0]      regularly spaced with Δz=0.4
[ Info:   Testing Lagrangian particle tracking [CPU, RungeKutta3] with y Flat on vertically stretched grid ...
grid = 5×1×5 RectilinearGrid{Float64, Periodic, Flat, Bounded} on CPU with 3×0×3 halo 
├── Periodic x ∈ [-1.0, 1.0)      regularly spaced with Δx=0.4
├── Flat y
└── Bounded  z ∈ [-1.0, 1.0]      variably spaced with min(Δz)=0.3, max(Δz)=0.5 
```

**Comment by glwagner** [comment]
that looks good, just make sure to add the missing space after a comma and also we prefer `arch = tuple(CPU())` to `arch = (CPU(),)` (slightly easier to read)

File: test/test_lagrangian_particle_tracking.jl [hunk 3]
```diff
@@ -22,41 +22,28 @@ function particle_tracking_simulation(; grid, particles, timestepper=:RungeKutta
...
+            filename="test_particles", schedule=IterationInterval(1))
 
     nc_filepath = "test_particles.nc"
     sim.output_writers[:particles_nc] =
-        NetCDFOutputWriter(model, model.particles, filename=nc_filepath, schedule=IterationInterval(1)) 
+        NetCDFOutputWriter(model, model.particles, filename=nc_filepath, schedule=IterationInterval(1))
 
     sim.output_writers[:checkpointer] = Checkpointer(model, schedule=IterationInterval(1),
-                                                     dir = ".", prefix = "particles_checkpoint")
+        dir=".", prefix="particles_checkpoint")
```
Comment (navidcy) [inline test/test_lagrangian_particle_tracking.jl:32]:
```suggestion
                                                     dir=".", prefix="particles_checkpoint")
```

File: test/test_lagrangian_particle_tracking.jl [hunk 4]
```diff
@@ -127,8 +114,8 @@ function run_simple_particle_tracking_tests(arch, timestepper; vertically_stretc
     @test lagrangian_particles isa LagrangianParticles
 
     model = NonhydrostaticModel(; grid, timestepper,
-                                  velocities, particles=lagrangian_particles,
-                                  background_fields = (v = background_v, ))
+        velocities, particles=lagrangian_particles,
+        background_fields=(v=background_v,))
```
Comment (navidcy) [inline test/test_lagrangian_particle_tracking.jl:118]:
```suggestion
                                  velocities, particles=lagrangian_particles,
                                  background_fields=(v=background_v,))
```

File: test/test_lagrangian_particle_tracking.jl [hunk 5]
```diff
@@ -137,20 +124,20 @@ function run_simple_particle_tracking_tests(arch, timestepper; vertically_stretc
     jld2_filepath = "test_particles.jld2"
     sim.output_writers[:particles_jld2] =
         JLD2OutputWriter(model, (; particles=model.particles),
-                         filename=jld2_filepath, schedule=IterationInterval(1))
+            filename=jld2_filepath, schedule=IterationInterval(1))
```
Comment (navidcy) [inline test/test_lagrangian_particle_tracking.jl:127]:
```suggestion
                         filename=jld2_filepath, schedule=IterationInterval(1))
```

File: test/test_lagrangian_particle_tracking.jl [hunk 6]
```diff
@@ -137,20 +124,20 @@ function run_simple_particle_tracking_tests(arch, timestepper; vertically_stretc
...
 
     nc_filepath = "test_particles.nc"
     sim.output_writers[:particles_nc] =
         NetCDFOutputWriter(model, model.particles, filename=nc_filepath, schedule=IterationInterval(1))
 
     sim.output_writers[:checkpointer] = Checkpointer(model, schedule=IterationInterval(1),
-                                                     dir = ".", prefix = "particles_checkpoint")
+        dir=".", prefix="particles_checkpoint")
```
Comment (navidcy) [inline test/test_lagrangian_particle_tracking.jl:134]:
```suggestion
                                                    dir=".", prefix="particles_checkpoint")
```
