### PR TITLE
Fixes show for VerticallyStretchedRectilinearGrid on GPUs

### LINKED ISSUE #1637: `show()` for VerticallyStretchedRectilinearGrId
On GPU it throws an error regarding CUDA scalar operations.

### PR DESCRIPTION
**Pull request by glwagner**
This PR uses a view into the underlying array of grid spacings rather than a view into the OffsetArray of grid spacings in `Base.show` for `VerticallyStretchedRectilinearGrid`. This should allow `maximum` and `minimum` to run without errors and allow `VerticallyStretchedRectilinearGrid` to be printed on the GPU.

Would be best to add a test, cc @navidcy

Closes #1637 .

### CODE REVIEW

File: src/Grids/vertically_stretched_rectilinear_grid.jl [hunk 1]
```diff
@@ -272,8 +272,8 @@ short_show(grid::VerticallyStretchedRectilinearGrid{FT, TX, TY, TZ}) where {FT,
     "VerticallyStretchedRectilinearGrid{$FT, $TX, $TY, $TZ}(Nx=$(grid.Nx), Ny=$(grid.Ny), Nz=$(grid.Nz))"
 
 function show(io::IO, g::VerticallyStretchedRectilinearGrid{FT, TX, TY, TZ}) where {FT, TX, TY, TZ}
-    Δz_min = minimum(view(g.Δzᵃᵃᶜ, 1:g.Nz))
-    Δz_max = maximum(view(g.Δzᵃᵃᶜ, 1:g.Nz))
+    Δz_min = minimum(view(parent(g.Δzᵃᵃᶜ), g.Hz+1:g.Nz+g.Hz))
+    Δz_max = maximum(view(parent(g.Δzᵃᵃᶜ), g.Hz+1:g.Nz+g.Hz))
```
Comment (navidcy) [inline src/Grids/vertically_stretched_rectilinear_grid.jl:276]: Could you elaborate on why this should eliminate the scalar operation error on GPUs?
(I'm mostly interested to learn... I'm not arguing that it's not the right way forward.)

Comment (glwagner) [reply src/Grids/vertically_stretched_rectilinear_grid.jl:276]: `g.Δzᵃᵃᶜ` is an `OffsetArray`, which is a wrapper around a `CuArray` that changes indexing behavior. (`parent(g.Δzᵃᵃᶜ) returns the underlying `CuArray`.) `view` also returns a wrapper that both shifts indices and defines new `size` and `length` functions.

So `view(g.Δzᵃᵃᶜ)` is a doubly nested wrapper.

For computing reductions on the GPU like `maximum` and `minimum`, `GPUArrays.jl` and `CUDA.jl` provide special implementations of `Base.mapreducedim!`, which performs in-place reductions of array-like objects. Then some common reduction functions are defined using this implementation

https://github.com/JuliaGPU/GPUArrays.jl/blob/7f8410a1147bfb25a552d8ab1ee85d74bf9ed6fa/src/host/mapreduce.jl#L83-L91

(this mirrors the implementation in `Base`.)

However, in those lines you'll notice that this special implementation is only provided for objects of type `AnyGPUArray`, defined here:

https://github.com/JuliaGPU/GPUArrays.jl/blob/4de9fbb3a64546f13834214f97b5ecfb4d94f1d3/src/host/abstractarray.jl#L23

This includes `WrappedGPUArray`, which is a large type union defined in `Adapt.jl` that includes many common "nested" array types, including `view`s into `CuArray`. But it only includes _singly_ nested arrays. It does not include _doubly_ nested arrays. The number of types that'd be needed in the type union to support _doubly_ nested arrays might be very long...

Because doubly nested arrays cannot use the special GPU-specified reduction functions (because they are not included in the type union `AnyGPUArray`), when we call `maximum` on a `view` into an `OffsetArray`, we fallback to the implementation in `Base`. And this implementation relies on indexing into the array, rather than launching a kernel that's GPU-friendly.

Comment (glwagner) [reply src/Grids/vertically_stretched_rectilinear_grid.jl:276]: See

https://github.com/JuliaGPU/Adapt.jl/blob/cac58aa57367cb6d607328d4679e7c2d39ddba61/src/wrappers.jl#L63

for the definition of `WrappedArray` in `Adapt`.

Bottom line is that in order to use the special GPU reductions we need to pass either raw `CuArray` or _singly_ wrapped `CuArray`, like `view(a::CuArray)` or `OffsetArray(a::CuArray)`. Doubly nested wrappers like `view(OffsetArray(a::CuArray))` cannot be used (at least not right not).

Comment (glwagner) [reply src/Grids/vertically_stretched_rectilinear_grid.jl:276]: The fact that `WrappedArray` only works with one level of nesting is mentioned here:

https://github.com/JuliaGPU/Adapt.jl/blob/cac58aa57367cb6d607328d4679e7c2d39ddba61/src/wrappers.jl#L101-L102

and can also be seen from the definition of `WrappedArray`.

Comment (glwagner) [reply src/Grids/vertically_stretched_rectilinear_grid.jl:276]: Also note that the "allocation" versions of reduction functions (eg `maximum`, compared with the in-place `maximum!`) work merely by first calling `similar(a)` (to allocate output) and then calling the in-place versions on that object). For the case of a scalar (`maximum(a, dims=:)`) we get the somewhat silly pattern

https://github.com/JuliaGPU/GPUArrays.jl/blob/7f8410a1147bfb25a552d8ab1ee85d74bf9ed6fa/src/host/mapreduce.jl#L64-L68

So in order to understand how all the reduction functions work at the outermost level, we should first focus on the in-place versions.

**Comment by navidcy** [comment]
I'm trying to write up a test and for that I'm running Oceananigans.jl on an HPC with GPU. I run into these sort of trouble though...


```julia
(base) [nc3020@gadi-gpu-v100-0045 Oceananigans.jl]$ JULIA_DEBUG=all julia-1.5 --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.4 (2021-03-11)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |

shell> nvidia-smi
Wed May 12 11:45:39 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:B1:00.0 Off |                    0 |
| N/A   32C    P0    42W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

julia> using Oceananigans
┌ Debug: Using LLVM 9.0.1 at /g/data/v45/nc3020/julia-1.5/usr/bin/../lib/libLLVM-9jl.so
└ @ LLVM /g/data/v45/nc3020/.julia/packages/LLVM/7Q46C/src/LLVM.jl:87
┌ Warning: You appear to be using MPI.jl with the default MPI binary on a cluster.
│ We recommend using the system-provided MPI, see the Configuration section of the MPI.jl docs.
└ @ MPI /g/data/v45/nc3020/.julia/packages/MPI/b7MVG/deps/deps.jl:15
[ Info: Oceananigans will use 48 threads
┌ Debug: Initializing CUDA driver
└ @ CUDA /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/initialization.jl:88
┌ Debug: Trying to use local installation...
└ @ CUDA /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/deps/bindeps.jl:194
┌ Debug: Looking for CUDA toolkit via environment variables CUDA_HOME, CUDA_ROOT
└ @ CUDA /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/deps/discovery.jl:326
┌ Debug: Request to look for binary nvdisasm
│   locations =
│    1-element Array{String,1}:
│     "/apps/cuda/11.2.2"
└ @ CUDA /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/deps/discovery.jl:118
┌ Debug: Looking for binary nvdisasm
│   locations =
│    2-element Array{String,1}:
│     "/apps/cuda/11.2.2"
│     "/apps/cuda/11.2.2/bin"
└ @ CUDA /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/deps/discovery.jl:128
┌ Debug: Found binary nvdisasm at /apps/cuda/11.2.2/bin/nvdisasm
└ @ CUDA /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/deps/discovery.jl:134

julia> zF = collect(0:10).^2; grid = VerticallyStretchedRectilinearGrid(Float64, architecture=GPU(), size=(1, 1, length(zF)-1), x=(0, 1), y=(0, 1), z_faces=zF)
ERROR: CUDA.jl did not successfully initialize, and is not usable.
If you did not see any other error message, try again in a new session
with the JULIA_DEBUG environment variable set to 'CUDA'.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] libcuda() at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/initialization.jl:48
 [3] (::CUDA.var"#690#cache_fptr!#9")() at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/lib/utils/call.jl:31
 [4] macro expansion at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/lib/utils/call.jl:39 [inlined]
 [5] macro expansion at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/lib/cudadrv/libcuda.jl:29 [inlined]
 [6] macro expansion at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/lib/cudadrv/error.jl:102 [inlined]
 [7] cuDeviceGet(::Base.RefValue{Int32}, ::Int64) at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/lib/utils/call.jl:93
 [8] CUDA.CuDevice(::Int64) at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/lib/cudadrv/devices.jl:25
 [9] initialize_thread(::Int64) at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/state.jl:121
 [10] prepare_cuda_call() at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/state.jl:80
 [11] device at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/state.jl:227 [inlined]
 [12] alloc at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/pool.jl:293 [inlined]
 [13] CUDA.CuArray{Float64,1}(::UndefInitializer, ::Tuple{Int64}) at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/array.jl:20
 [14] CuArray at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/array.jl:190 [inlined]
 [15] CuArray at /g/data/v45/nc3020/.julia/packages/CUDA/wTQsK/src/array.jl:198 [inlined]
 [16] arch_array(::GPU, ::Array{Float64,1}) at /g/data/v45/nc3020/Oceananigans.jl/src/Architectures.jl:62
 [17] VerticallyStretchedRectilinearGrid(::Type{T} where T; architecture::GPU, size::Tuple{Int64,Int64,Int64}, z_faces::Array{Int64,1}, x::Tuple{Int64,Int64}, y::Tuple{Int64,Int64}, halo::Nothing, topology::Tuple{DataType,DataType,DataType}) at /g/data/v45/nc3020/Oceananigans.jl/src/Grids/vertically_stretched_rectilinear_grid.jl:169
 [18] top-level scope at REPL[1]:1

julia>
```

**Comment by navidcy** [comment]
pinging @ali-ramadhan here in case he has some insight...

**Comment by ali-ramadhan** [comment]
Hmmm not sure of the HPC setup details but it doesn't seem to be an Oceananigans.jl issue... Can you create a `CuArray` with something like

```julia
using CUDA
c = CuArray(zeros(10))
```

?

**Comment by navidcy** [comment]
oh sorry, I just saw your reply... 
indeed the problem was with CUDA... I fixed it!

(I removed my question though... just putting this here in case the messages seem strange for the git-archaeologists of the next century.)

File: test/test_grids.jl [hunk 2]
```diff
@@ -585,7 +585,7 @@ end
 
             # Testing show function
             Nz = 20
-            grid = VerticallyStretchedRectilinearGrid(size=(1, 1, Nz), x=(0, 1), y=(0, 1), z_faces=collect(0:Nz).^2)
+            grid = VerticallyStretchedRectilinearGrid(architecture=arch, size=(1, 1, Nz), x=(0, 1), y=(0, 1), z_faces=collect(0:Nz).^2)
```
Comment (navidcy) [inline test/test_grids.jl:588]: @glwagner, @ali-ramadhan: does this really test `show()`?

Comment (glwagner) [reply test/test_grids.jl:588]: Right. A more explicit way to write the test is something like

```
@test try
    show(grid)
    true
catch err
    # figure out how to print the error message...
    false
end
```

Would even be nice to have a macro that writes this out like `@test_works` or something.

On the other hand just running code works fine for isolating errors in CI and seems to be practical.

**Comment by navidcy** [comment]
At the moment only `show(::VerticallyStretchedRectilinearGrid)` is tested on both CPU and GPU. Should we test all of the grids on both architectures? Why not?

File: test/test_grids.jl [hunk 3]
```diff
@@ -554,7 +554,15 @@ end
         # Testing show function
         topo = (Periodic, Periodic, Periodic)
         grid = RegularRectilinearGrid(topology=topo, size=(3, 7, 9), x=(0, 1), y=(-π, π), z=(0, 2π))
-        show(grid); println();
+
+        @test try
+            show(grid)
+            true
+        catch err
+            error("error in show(::RegularRectilinearGrid)")
```
Comment (glwagner) [inline test/test_grids.jl:562]: Can you print the error message?

Comment (glwagner) [reply test/test_grids.jl:562]: Otherwise its annoying to debug because you have to reproduce the error; we can't see it in the build log for example...

Comment (navidcy) [reply test/test_grids.jl:562]: sure, but why? is it better?

Comment (glwagner) [reply test/test_grids.jl]: It could be

```julia
julia> f() = b
f (generic function with 1 method)

julia> f()
ERROR: UndefVarError: b not defined
Stacktrace:
 [1] f() at ./REPL[13]:1
 [2] top-level scope at REPL[14]:1

julia> a = try
       f()
       true
       catch err
       println(sprint(showerror, err))
       false
       end
UndefVarError: b not defined
false
```

Maybe in addition to a statement about where it came from (here, `show(grid)`).

Comment (glwagner) [reply test/test_grids.jl]: Also if we throw the error in the `catch`, the test still errors rather than fails right? It's unclear what behavior we want. I guess it's nice to know whether you got an error or a fail so we probably do want `throw(err)` in fact.

File: test/test_grids.jl [hunk 4]
```diff
@@ -601,7 +619,16 @@ end
...
         # Testing show function
         grid = RegularLatitudeLongitudeGrid(size=(36, 32, 1), longitude=(-180, 180), latitude=(-80, 80), z=(0, 1))
-        show(grid); println();
+    
+        @test try
+            show(grid)
+            return true
+        catch err
+            println("error in show(::RegularLatitudeLongitudeGrid)")
+            println(sprint(showerror, err))
```
Comment (glwagner) [inline test/test_grids.jl:628]: Ok, we'll see if we like this better than `throw(err)` I suppose.

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
I approve but @glwagner I'd like your approval before I merge.
Let's see if all tests pass first ;)

**Comment by navidcy** [comment]
OK, the idea is that tests should pass in this PR but fail here: https://github.com/CliMA/Oceananigans.jl/tree/ncc/test-show-on-gpu
If that happens I am merging. @glwagner?

**Comment by navidcy** [comment]
> OK, the idea is that tests should pass in this PR but fail here: https://github.com/CliMA/Oceananigans.jl/tree/ncc/test-show-on-gpu
> If that happens I am merging. @glwagner, @ali-ramadhan ?

That’s the case!

**Comment by glwagner** [comment]
go for it
