### PR TITLE
Introduce distributed conservation tests and fix some bugs

### LINKED ISSUE #5161: Conservation with `Distributed` architecture and `ZStarCoordinate` not ensured
there must be a bug somewhere that destroys conservation on a `Distributed` architecture. 
There are two TODOs connected to this issue:
enable the tests commented out in
https://github.com/CliMA/Oceananigans.jl/blob/5fc355c22df9768667d4046b44c4710f5b14b2a0/.buildkite/distributed/pipeline.yml#L158
and the tests that compare distributed with serial models in 
https://github.com/CliMA/Oceananigans.jl/blob/5fc355c22df9768667d4046b44c4710f5b14b2a0/test/test_distributed_hydrostatic_model.jl#L96

### PR DESCRIPTION
**Pull request by simone-silvestri**
this PR is another step for closing the distributed zstar conservation issue 

Edit: a couple of bugs including the `MutableVerticalDiscretization` and `SplitExplicitFreeSurface` were found
- The `surface_buffer_kernel_parameters` needs to include corners to make sure the column height is correctly computed when iterating the split explicit free surface
- In case of a non-distributed grid, we need to have topology-aware column_height operators that do not go and look in the halos when iterating the split explicit solution (this is `SplitExplicitFreeSurface` specific)
- topology-aware operators need to include the new topologies `RightCenterFolded` and `RightFaceFolded` which act the same as a `RightConnected` topology.

Closes #5161

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

File: src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl [hunk 1]
```diff
@@ -305,10 +305,9 @@ function validate_vertical_velocity_boundary_conditions(w)
     return nothing
 end
 
-validate_free_surface(::Distributed, free_surface::SplitExplicitFreeSurface) = free_surface
-validate_free_surface(::Distributed, free_surface::ExplicitFreeSurface)      = free_surface
-validate_free_surface(::Distributed, free_surface::Nothing)                  = free_surface
-validate_free_surface(arch::Distributed, free_surface) = error("$(typeof(free_surface)) is not supported with $(typeof(arch))")
+const FFTIFS = ImplicitFreeSurface{<:Any, <:Any, <:FFTImplicitFreeSurfaceSolver}
+
+validate_free_surface(arch::Distributed, ::FFTIFS) = error("$(typeof(free_surface)) is not supported with $(typeof(arch))")
```
Comment (giordano) [inline src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:310]: `free_surface` is undefined, I presume this was supposed to be
```suggestion
validate_free_surface(arch::Distributed, ::FFTIFS) = error("$(FFTIFS) is not supported with $(typeof(arch))")
```
?
