### PR TITLE
Fix ranks not seeing the correct device

### LINKED ISSUE #4826: `SplitRungeKutta3` time stepper does not distribute memory correctly in distributed runs
I am trying to run an ocean model using the `SplitRungeKutta3` time stepper with distributed GPU and/or CPUs. 

Somehow, when creating the model using `ocean_model = HydrostaticFreeSurfaceModel(; grid, free_surface, timestepper = :SplitRungeKutta3)`, the  memory used per-GPU goes UP when we increase the number of GPUs:

RK3:
________________________
2 GPUS: 51 MB per GPU
3 GPUS: 80 MB per GPU

and also for CPUS:

2 CPUS: 161 MB per CPU
3 CPUS: 258 MB per CPU
________________________
The issue with GPUs is present even for `AdamBashforth` (though not as bad) but the CPUs seem to scale well there. 

AB2
________________________
2 GPUS: 60 MB per GPU
3 GPUS: 73 MB per GPU

and also for CPUS:

2 CPUS: 133 MB per CPU
3 CPUS: 50MB per CPU 
_______________________

Here's an MWE that outputs memory at opportune moments that illustrates the issue. 

```Julia
using MPI
using CUDA

MPI.Init()
atexit(MPI.Finalize)  

using Oceananigans
using Oceananigans.Units
using ClimaOcean
using Oceananigans.DistributedComputations
using Printf
using Dates

data_path = expanduser("/g/data/v46/txs156/ocean-ensembles/data/")

arch = Distributed(GPU(); partition = Partition(y = DistributedComputations.Equal()), synchronized_communication=true)

function memory_status(arch::Union{Distributed{<:GPU}, <:GPU})
    free, total = CUDA.memory_info()
    used = total - free
    used_GiB, free_GiB, total_GiB = used / 2^30, free / 2^30, total / 2^30
    @show arch.local_rank, used_GiB, free_GiB, total_GiB
end

function memory_status(arch::Union{Distributed{<:CPU}, <:CPU})
    total = Sys.total_memory()
    free  = Sys.free_memory()
    used  = total - free
    used_GiB, free_GiB, total_GiB = used / 2^30, free / 2^30, total / 2^30
    @show arch.local_rank, used_GiB, free_GiB, total_GiB
end

Nx, Ny, Nz = 100, 100, 50
Lx, Ly = 100, 100
@info "Defining vertical z faces"
depth = -6000.0 # Depth of the ocean in meters
z_faces = ExponentialCoordinate(Nz, depth, 0) 
memory_status(arch)
@info "Creating grid"

underlying_grid = TripolarGrid(arch;
                    size = (Nx, Ny, Nz),
                    z = z_faces,
                    halo = (6, 6, 3))

@info "Defining bottom bathymetry"

memory_status(arch)

ETOPOmetadata = Metadatum(:bottom_height, dataset=ETOPO2022(), dir = data_path)
ClimaOcean.DataWrangling.download_dataset(ETOPOmetadata)
memory_status(arch)
@time bottom_height = regrid_bathymetry(underlying_grid, ETOPOmetadata;
                                  minimum_depth = 15,
                                  interpolation_passes = 1, # 75 interpolation passes smooth the bathymetry near Florida so that the Gulf Stream is able to flow
				                  major_basins = 2)

memory_status(arch)

@info "Defining grid"

@time grid = ImmersedBoundaryGrid(underlying_grid, GridFittedBottom(bottom_height); active_cells_map=true)

memory_status(arch)
### Restoring

@info "Creating model"
free_surface = SplitExplicitFreeSurface(grid; substeps = 70)

memory_status(arch)

ocean_model = HydrostaticFreeSurfaceModel(; grid, free_surface, timestepper = :SplitRungeKutta3)

memory_status(arch)

@info "Creating simulation"

simulation = Simulation(ocean_model; Δt=10, verbose=false, stop_time=2hours)

memory_status(arch)

wizard = TimeStepWizard(cfl=1, max_change=1.1, max_Δt=1minutes)
simulation.callbacks[:wizard] = Callback(wizard, IterationInterval(10))

# Nice progress messaging is helpful:

## Print a progress message
progress_message(sim) = @printf("Iteration: %04d, time: %s, Δt: %s, max(|w|) = %.1e ms⁻¹, wall time: %s\n",
                                iteration(sim), prettytime(sim), prettytime(sim.Δt),
                                maximum(abs, sim.model.velocities.w), prettytime(sim.run_wall_time))

add_callback!(simulation, progress_message, IterationInterval(40))
@info "Running simulation"
run!(simulation)
```

*apologies for using ClimaOcean, that was just for the bottom bathymetry so we don't have singularities over the ocean.

### PR DESCRIPTION
**Pull request by simone-silvestri**
See issue #4826 
In this branch, the MWE in [comment](https://github.com/CliMA/Oceananigans.jl/issues/4826#issuecomment-3355474437) returns
```julia
ssilvest@tartarus:/storage4/simone/TestsScaling/Oceananigans.jl$ for i in $(seq 1 3); do echo ""; echo "RUNNING with rank $i"; echo ""; ../openmpi/bin/mpirun -np $i julia --project -O0 test_memory.jl "latitude" ""; echo ""; echo ""; done

RUNNING with rank 1

No protocol specified
[ Info: Rank 0 running on device:
[ Info: CuDevice(0)



RUNNING with rank 2

No protocol specified
[ Info: Rank 0 running on device:
[ Info: CuDevice(0)
[ Info: Rank 1 running on device:
[ Info: CuDevice(1)



RUNNING with rank 3

No protocol specified
[ Info: Rank 0 running on device:
[ Info: CuDevice(0)
[ Info: Rank 1 running on device:
[ Info: CuDevice(1)
[ Info: Rank 2 running on device:
[ Info: CuDevice(2)
```

@taimoorsohail can you test that this fixes your issue?
closes #4826

### CODE REVIEW

**Comment by simone-silvestri** [comment]
I can confirm that also @taimoorsohail's MWE posted in this [comment](https://github.com/CliMA/Oceananigans.jl/issues/4826#issuecomment-3355017005) works (I have increased the grid size to (1000, 1000, 100) to remove the noise coming from non-scaling overheads)
```julia
ssilvest@tartarus:/storage4/simone/TestsScaling/Oceananigans.jl$ for i in $(seq 1 3); do echo ""; echo "RUNNING with rank $i"; echo ""; ../openmpi/bin/mpirun -np $i julia --project -O0 test_memory.jl "latitude" ""; echo ""; echo ""; done

RUNNING with rank 1

No protocol specified
[ Info: Defining vertical z faces
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.30352783203125, 11.470947265625, 11.77447509765625)
[ Info: Creating grid
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.46173095703125, 11.312744140625, 11.77447509765625)
[ Info: Defining grid
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.46954345703125, 11.304931640625, 11.77447509765625)
[ Info: Creating free surface
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.46954345703125, 11.304931640625, 11.77447509765625)
[ Info: Creating model
┌ Warning: Split barotropic-baroclinic time stepping with SplitRungeKutta3TimeStepper is experimental.
│ Use at own risk, and report any issues encountered at [https://github.com/CliMA/Oceananigans.jl/issues](https://github.com/CliMA/Oceananigans.jl/issues).
└ @ Oceananigans.TimeSteppers /storage4/simone/TestsScaling/Oceananigans.jl/src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl:59
(rank, used_GiB, free_GiB, total_GiB) = (0, 7.27423095703125, 4.500244140625, 11.77447509765625)



RUNNING with rank 2

No protocol specified
[ Info: Defining vertical z faces
[ Info: Defining vertical z faces
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.30352783203125, 11.470947265625, 11.77447509765625)
[ Info: Creating grid
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.30352783203125, 11.470947265625, 11.77447509765625)
[ Info: Creating grid
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.38360595703125, 11.390869140625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.38360595703125, 11.390869140625, 11.77447509765625)
[ Info: Defining grid
[ Info: Defining grid
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.38751220703125, 11.386962890625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating free surface
[ Info: Creating free surface
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.38751220703125, 11.386962890625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating model
[ Info: Creating model
┌ Warning: Split barotropic-baroclinic time stepping with SplitRungeKutta3TimeStepper is experimental.
│ Use at own risk, and report any issues encountered at [https://github.com/CliMA/Oceananigans.jl/issues](https://github.com/CliMA/Oceananigans.jl/issues).
└ @ Oceananigans.TimeSteppers /storage4/simone/TestsScaling/Oceananigans.jl/src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl:59
┌ Warning: Split barotropic-baroclinic time stepping with SplitRungeKutta3TimeStepper is experimental.
│ Use at own risk, and report any issues encountered at [https://github.com/CliMA/Oceananigans.jl/issues](https://github.com/CliMA/Oceananigans.jl/issues).
└ @ Oceananigans.TimeSteppers /storage4/simone/TestsScaling/Oceananigans.jl/src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl:59
(rank, used_GiB, free_GiB, total_GiB) = (1, 3.96173095703125, 7.812744140625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (0, 3.96173095703125, 7.812744140625, 11.77447509765625)



RUNNING with rank 3

No protocol specified
[ Info: Defining vertical z faces
[ Info: Defining vertical z faces
[ Info: Defining vertical z faces
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.30352783203125, 11.470947265625, 11.77447509765625)
[ Info: Creating grid
(rank, used_GiB, free_GiB, total_GiB) = (2, 0.30352783203125, 11.470947265625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.30352783203125, 11.470947265625, 11.77447509765625)
[ Info: Creating grid
[ Info: Creating grid
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.38360595703125, 11.390869140625, 11.77447509765625)
[ Info: Defining grid
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.38360595703125, 11.390869140625, 11.77447509765625)
[ Info: Defining grid
(rank, used_GiB, free_GiB, total_GiB) = (2, 0.38360595703125, 11.390869140625, 11.77447509765625)
[ Info: Defining grid
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating free surface
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating free surface
(rank, used_GiB, free_GiB, total_GiB) = (2, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating free surface
(rank, used_GiB, free_GiB, total_GiB) = (0, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating model
(rank, used_GiB, free_GiB, total_GiB) = (1, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating model
(rank, used_GiB, free_GiB, total_GiB) = (2, 0.38751220703125, 11.386962890625, 11.77447509765625)
[ Info: Creating model
┌ Warning: Split barotropic-baroclinic time stepping with SplitRungeKutta3TimeStepper is experimental.
│ Use at own risk, and report any issues encountered at [https://github.com/CliMA/Oceananigans.jl/issues](https://github.com/CliMA/Oceananigans.jl/issues).
└ @ Oceananigans.TimeSteppers /storage4/simone/TestsScaling/Oceananigans.jl/src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl:59
┌ Warning: Split barotropic-baroclinic time stepping with SplitRungeKutta3TimeStepper is experimental.
│ Use at own risk, and report any issues encountered at [https://github.com/CliMA/Oceananigans.jl/issues](https://github.com/CliMA/Oceananigans.jl/issues).
└ @ Oceananigans.TimeSteppers /storage4/simone/TestsScaling/Oceananigans.jl/src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl:59
┌ Warning: Split barotropic-baroclinic time stepping with SplitRungeKutta3TimeStepper is experimental.
│ Use at own risk, and report any issues encountered at [https://github.com/CliMA/Oceananigans.jl/issues](https://github.com/CliMA/Oceananigans.jl/issues).
└ @ Oceananigans.TimeSteppers /storage4/simone/TestsScaling/Oceananigans.jl/src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl:59
(rank, used_GiB, free_GiB, total_GiB) = (1, 2.93829345703125, 8.836181640625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (0, 2.83477783203125, 8.939697265625, 11.77447509765625)
(rank, used_GiB, free_GiB, total_GiB) = (2, 2.83477783203125, 8.939697265625, 11.77447509765625)
```

**Comment by navidcy** [comment]
Thanks @simone-silvestri!

**Comment by simone-silvestri** [comment]
I guess the correct thing to do would be to fix `KA.device!`, however, that might require changes in more than just KA, so we probably should just merge this and maybe switch back to `KA.device!` when https://github.com/JuliaGPU/KernelAbstractions.jl/issues/636 is resolved

**Comment by navidcy** [comment]
The @testset "Distributed architectures" you added will catch this, right?

**Comment by navidcy** [comment]
So this PR closes https://github.com/CliMA/Oceananigans.jl/issues/4826, right?

**Comment by simone-silvestri** [comment]
yeah I guess we can close it.

File: test/test_distributed_architectures.jl [hunk 1]
```diff
@@ -57,3 +57,18 @@ using Oceananigans.DistributedComputations
     @onrank split_comm 0 @test a == [1, 3, 5, 7, 9]
     @onrank split_comm 1 @test a == [2, 4, 6, 8, 10]
 end
+
+@testset "Distributed architectures" begin
+    for arch in test_architectures()
+        child_arch = child_architecture(arch)
+        if child_arch isa Architectures.CUDAGPU
```
Comment (navidcy) [inline test/test_distributed_architectures.jl]:
```suggestion
        if child_arch isa Oceananigans.Architectures.CUDAGPU
```

File: test/test_distributed_architectures.jl [hunk 2]
```diff
@@ -57,3 +57,16 @@ using Oceananigans.DistributedComputations
     @onrank split_comm 0 @test a == [1, 3, 5, 7, 9]
     @onrank split_comm 1 @test a == [2, 4, 6, 8, 10]
 end
+
+@testset "Distributed architectures" begin
+    for arch in test_architectures()
+        child_arch = child_architecture(arch)
+        if child_arch isa Oceananigans.Architectures.CUDAGPU
```
Comment (navidcy) [inline test/test_distributed_architectures.jl]: or should it be something else here @simone-silvestri?
I changed it because tests were failing.....

**Comment by navidcy** [comment]
@simone-silvestri could you have a look? seems like tests fail?

https://buildkite.com/clima/oceananigans-distributed/builds/10179#01999fb5-838e-416d-977c-958850aedef7/208-1362

**Comment by simone-silvestri** [comment]
Weird, it works locally on tartarus...
```julia
ssilvest@tartarus:/storage4/simone/TestsScaling/Oceananigans.jl$ MPI_TEST=true TEST_ARCHITECTURE=GPU ../openmpi/bin/mpirun -np 4 julia --project test/test_distributed_architectures.jl
No protocol specified
Test Summary:      | Test Summary:      | Pass  Pass  Test Summary:      | Total  Total  Test Summary:      | Pass  Total  Pass  Total  TimeTimeTimeTime

Distributed macros | Distributed macros |    3     3      3  0.4s    3  0.3s


Distributed macros |
Distributed macros |    3      3  0.3s
   4      4  0.3s
Test Summary:             | Pass  Total  Time
Distributed architectures |    6      6  0.1s
Test Summary:             | Pass  Total  Time
Distributed architectures |    6      6  0.1s
Test Summary:             | Pass  Total  Test Summary:             | Pass  Total  Time
Distributed architectures |    6  Time
Distributed architectures |    6      6  0.1s
    6  0.1s
```

**Comment by navidcy** [comment]
The error persists... :( 

https://buildkite.com/clima/oceananigans-distributed/builds/10197#0199a0b3-1536-49f7-9c82-94a7bf11b25e/206-1360

**Comment by simone-silvestri** [comment]
Not sure why this test doesn't pass. Let's merge without then, we will probably revert to `KA.device!` when this is solved in CUDA.jl and a new version is registered.
