### PR TITLE
Postcompute, not precompute

### LINKED ISSUE #1063: Halo regions need to be filled prior to computations and abstract operations
Currently halo regions are filled _prior_ to performing a time-step. This means that _after_ the time-step, they are incorrect. We therefore cannot output fields with correct halo regions, since data is outputted after a time-step is taken.

But it gets worse. If the average of a field is taken, we zero out the halo regions.

Zeroing out the halo regions corrupts near-boundary data for all subsequent computations with the fields. Currently, abstract operations cannot be trusted in boundary-adjacent cells.

To remedy this we need to fill halo regions on fields prior to performing computations. One way we might do this is to write a `compute!` method for fields:

```julia
compute!(field::Field) = fill_halo_regions!(field)
```

We can also define a `conditional_compute!` method for `Field`s and add a `status` property, so that halo regions are not filled "redundantly". For this to work, we also need to invalidate `field.status` when halo regions are zeroed out by `compute!(averaged_field::AveragedField)`, (for example by setting `field.status.time = NaN`).

This won't work currently, of course, due to #971 . So this issue cannot be resolved until #971 is resolved.

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #1063 (depends on #1081)

### CODE REVIEW

File: src/TimeSteppers/quasi_adams_bashforth_2.jl [hunk 1]
```diff
@@ -37,21 +37,21 @@ Step forward `model` one time step `Δt` with a 2nd-order Adams-Bashforth method
 pressure-correction substep. Setting `euler=true` will take a forward Euler time step.
 """
 function time_step!(model::IncompressibleModel{<:QuasiAdamsBashforth2TimeStepper}, Δt; euler=false)
+
     χ = ifelse(euler, convert(eltype(model.grid), -0.5), model.timestepper.χ)
 
-    precomputations!(model)
+    model.clock.iteration == 0 && update_state!(model) #
```
Comment (ali-ramadhan) [inline src/TimeSteppers/quasi_adams_bashforth_2.jl:43]:
```suggestion
    model.clock.iteration == 0 && update_state!(model)
```

**Review by ali-ramadhan — APPROVED** [review]

**Comment by glwagner** [comment]
A few thoughts while I'm debugging these test failures:

* I think at least some of the failures are occurring because we are still using `time_step!(model, dt)` for tests. Now we have to call `update_state!(model)` before a hand-written loop when `model.clock.iteration != 0`.

* checking `model.clock.iteration == 0` does not catch some cases. In the regression tests, we manually restore the model state to a configuration (essentially manual checkpointing). However, the halos are not correct (after this PR is merged they will be correct in saved data. However we still could have incorrect halos if models are "hack checkpointed" with NetCDFOutputWriter or JLD2OutputWriter that don't include halos). For these cases, we need to call `update_state!` before running a simulation. It seems we probably want to call `update_state` as part of the initialization of `run!` whether or not `iteration == 0` to be safe.

* Calling `update_state!(model)` every time that `run!` is called can lead to excess computation. But I think the excess is very small even in cases where `run!` is misused to advance the simulation only 10-20 time-steps (because `update_state!` is already a minor part of the total cost of time-stepping --- I think).
