### PR TITLE
Resolve bug in `binary_operation`

### LINKED ISSUE #5167: Bogus methods in `binary_operations.jl`
https://github.com/CliMA/Oceananigans.jl/blob/6fd02a4ac1d9f0f904b11f82994380df3c8f141a/src/AbstractOperations/binary_operations.jl#L133-L134
Both methods refer to `a` and `b`, but each of them takes only `a` or `b` as argument, so both methods try to access undefined variables.  No clue of what this should be.  Introduced by @simone-silvestri in #4870.

Detected with JETLS.

### PR DESCRIPTION
**Pull request by simone-silvestri**
closes #5167

### CODE REVIEW

File: src/AbstractOperations/binary_operations.jl [hunk 1]
```diff
@@ -130,8 +130,8 @@ function define_binary_operator(op)
         $op(Lc::Tuple, f::Function, b::AbstractField) = $op((Lc[1](), Lc[2](), Lc[3]()), a, b)
         $op(Lc::Tuple, a::AbstractField, f::Function) = $op((Lc[1](), Lc[2](), Lc[3]()), a, b)
```
Comment (giordano) [inline src/AbstractOperations/binary_operations.jl]: Also these are wrong.  Is it
```suggestion
        $op(Lc::Tuple, f::Function, b::AbstractField) = $op((Lc[1](), Lc[2](), Lc[3]()), f, b)
        $op(Lc::Tuple, a::AbstractField, f::Function) = $op((Lc[1](), Lc[2](), Lc[3]()), a, f)
```
?
