### PR TITLE
Default momentum advection for the `HydrostaticFreeSurfaceModel`

### LINKED ISSUE #3806: Error with default `HydrostaticFreeSurfaceModel` on `TripolarGrid`
I was actually expecting a different error. But this isn't a good one either.

```julia
julia> using Oceananigans

julia> using OrthogonalSphericalShellGrids

julia> grid = TripolarGrid(size=(4, 4, 4), z=(-1, 0))
4×4×4 OrthogonalSphericalShellGrid{Float64, Periodic, RightConnected, Bounded} on CPU with 4×4×4 halo and with precomputed metrics
├── centered at (λ, φ) = (0.0, -0.3201)
├── longitude: Periodic  extent 360.112 degrees     variably spaced with min(Δλ)=15.6283, max(Δλ)=95.2245
├── latitude:  RightConnected  extent 212.5 degrees variably spaced with min(Δφ)=23.4259, max(Δφ)=56.6667
└── z:         Bounded  z ∈ [-1.0, 0.0]             regularly spaced with Δz=0.25

julia> free_surface = SplitExplicitFreeSurface(grid; cfl=0.7)
SplitExplicitFreeSurface with Barotropic time step equal to 8.112 days


julia> model = HydrostaticFreeSurfaceModel(; grid, free_surface)
ERROR: Centered{1, Float64, Nothing, Nothing, Nothing, Nothing} is not supported with Oceananigans.Grids.ZRegOrthogonalSphericalShellGrid{Float64, Periodic, RightConnected, Bounded, OffsetArrays.OffsetMatrix{Float64, Matrix{Float64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Float64, OrthogonalSphericalShellGrids.Tripolar{Int64, Int64, Int64}, CPU}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] validate_momentum_advection(momentum_advection::Centered{…}, grid::Oceananigans.Grids.ZRegOrthogonalSphericalShellGrid{…})
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Projects/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:227
 [3] #construct_regionally#62
   @ ~/Projects/Oceananigans.jl/src/Utils/multi_region_transformation.jl:148 [inlined]
 [4] construct_regionally
   @ ~/Projects/Oceananigans.jl/src/Utils/multi_region_transformation.jl:143 [inlined]
 [5] macro expansion
   @ ~/Projects/Oceananigans.jl/src/Utils/multi_region_transformation.jl:221 [inlined]
 [6] HydrostaticFreeSurfaceModel(; grid::Oceananigans.Grids.ZRegOrthogonalSphericalShellGrid{…}, clock::Clock{…}, momentum_advection::Centered{…}, tracer_advection::Centered{…}, buoyancy::Nothing, coriolis::Nothing, free_surface::SplitExplicitFreeSurface{…}, tracers::Nothing, forcing::@NamedTuple{}, closure::Nothing, boundary_conditions::@NamedTuple{}, particles::Nothing, biogeochemistry::Nothing, velocities::Nothing, pressure::Nothing, diffusivity_fields::Nothing, auxiliary_fields::@NamedTuple{})
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Projects/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:129
 [7] top-level scope
   @ REPL[18]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by simone-silvestri**
closes #3806

### CODE REVIEW

File: src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl [hunk 1]
```diff
@@ -53,24 +53,28 @@ default_free_surface(grid::XYRegularRG; gravitational_acceleration=g_Earth) =
 default_free_surface(grid; gravitational_acceleration=g_Earth) =
     SplitExplicitFreeSurface(grid; cfl = 0.7, gravitational_acceleration)
 
+default_momentum_advection(grid) = CenteredSecondOrder()
+
+default_momentum_advection(::OrthogonalSphericalShellGrid) = VectorInvariant()
```
Comment (glwagner) [inline src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:58]:
```suggestion
default_momentum_advection(grid) = CenteredSecondOrder()
default_momentum_advection(::OrthogonalSphericalShellGrid) = VectorInvariant()
```

what's your thought on 

```julia
default_momentum_advection(grid) = VectorInvariant()
```

Comment (simone-silvestri) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:58]: It might be advantageous. So that the momentum equation is by default in the vector invariant form for the HydrostaticFreeSurfaceModel

Comment (glwagner) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl]: This default makes sense to me.

**Comment by glwagner** [comment]
some doctest errors

**Review by glwagner — APPROVED** [review]

File: src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl [hunk 2]
```diff
@@ -55,22 +55,22 @@ default_free_surface(grid; gravitational_acceleration=g_Earth) =
...
-                   boundary_conditions::NamedTuple = NamedTuple(),
-                                           tracers = (:T, :S),
-                     particles::ParticlesOrNothing = nothing,
-             biogeochemistry::AbstractBGCOrNothing = nothing,
-                                        velocities = nothing,
-                                          pressure = nothing,
-                                diffusivity_fields = nothing,
-                                  auxiliary_fields = NamedTuple(),
+                                clock = Clock{eltype(grid)}(time = 0),
+                   momentum_advection = default_momentum_advection(grid),
```
Comment (navidcy) [inline src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:59]: the docstring and the construction don't seem to match.. am I right?

Comment (glwagner) [inline src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:59]:
```suggestion
                   momentum_advection = VectorInvariant(),
```

Comment (glwagner) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:59]: agree

File: src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl (hunk 1 above)
Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl]: nice

**Comment by navidcy** [comment]
merge?
