### PR TITLE
Use tuple instead of vector in `tilted_bottom_boundary_layer.jl`

### LINKED ISSUE #4438: Tilted BBL example not working on GPU
Hi! I’m trying to design a simulation based on the tilted BBL example, but it’s not working properly on GPUs. The error message is attached below. If I remove b = B∞_field from the background_fields = (; b = B∞_field, v = V∞_field) line, the simulation runs. Any help would be appreciated! (thanks for including this example - it’s been very helpful for me @tomchor )

```julia
ERROR: LoadError: GPU compilation of MethodInstance for Oceananigans.Models.NonhydrostaticModels.gpu_compute_Gu!(::KernelAbstractions.CompilerMetadata{…}, ::OffsetArrays.OffsetArray{…}, ::RectilinearGrid{…}, ::Nothing, ::Tuple{…}) failed
KernelError: passing non-bitstype argument

Argument 6 to your kernel function is of type Tuple{UpwindBiased{3, Float64, Nothing, Nothing, Nothing, UpwindBiased{2, Float64, Nothing, Nothing, Nothing, UpwindBiased{1, Float64, Nothing, Nothing, Nothing, Nothing, Centered{1, Float64, Nothing, Nothing, Nothing, Nothing}}, Centered{1, Float64, Nothing, Nothing, Nothing, Nothing}}, Centered{2, Float64, Nothing, Nothing, Nothing, Centered{1, Float64, Nothing, Nothing, Nothing, Nothing}}}, ConstantCartesianCoriolis{Float64}, Nothing, ScalarDiffusivity{Oceananigans.TurbulenceClosures.ExplicitTimeDiscretization, Oceananigans.TurbulenceClosures.ThreeDimensionalFormulation, @NamedTuple{b::Float64}, Float64, @NamedTuple{b::Float64}}, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}, BuoyancyForce{BuoyancyTracer, Tuple{Float64, Float64, Float64}}, @NamedTuple{velocities::@NamedTuple{u::Oceananigans.Fields.ZeroField{Int64, 3}, v::Oceananigans.Fields.ConstantField{Float64, 3}, w::Oceananigans.Fields.ZeroField{Int64, 3}}, tracers::@NamedTuple{b::Oceananigans.Fields.FunctionField{Center, Center, Center, @NamedTuple{time::Float64, last_Δt::Float64, last_stage_Δt::Float64, iteration::Int64, stage::Int64}, @NamedTuple{ĝ::Vector{Float64}, N²::Float64}, typeof(constant_stratification), RectilinearGrid{Float64, Periodic, Flat, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing, Nothing}, Float64}}}, @NamedTuple{u::OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, v::OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, w::OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}}, @NamedTuple{b::OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}}, @NamedTuple{}, Nothing, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, @NamedTuple{time::Float64, last_Δt::Float64, last_stage_Δt::Float64, iteration::Int64, stage::Int64}, typeof(Oceananigans.Forcings.zeroforcing)}, which is not a bitstype:
  .7 is of type @NamedTuple{velocities::@NamedTuple{u::Oceananigans.Fields.ZeroField{Int64, 3}, v::Oceananigans.Fields.ConstantField{Float64, 3}, w::Oceananigans.Fields.ZeroField{Int64, 3}}, tracers::@NamedTuple{b::Oceananigans.Fields.FunctionField{Center, Center, Center, @NamedTuple{time::Float64, last_Δt::Float64, last_stage_Δt::Float64, iteration::Int64, stage::Int64}, @NamedTuple{ĝ::Vector{Float64}, N²::Float64}, typeof(constant_stratification), RectilinearGrid{Float64, Periodic, Flat, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing, Nothing}, Float64}}} which is not isbits.
    .tracers is of type @NamedTuple{b::Oceananigans.Fields.FunctionField{Center, Center, Center, @NamedTuple{time::Float64, last_Δt::Float64, last_stage_Δt::Float64, iteration::Int64, stage::Int64}, @NamedTuple{ĝ::Vector{Float64}, N²::Float64}, typeof(constant_stratification), RectilinearGrid{Float64, Periodic, Flat, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing, Nothing}, Float64}} which is not isbits.
      .b is of type Oceananigans.Fields.FunctionField{Center, Center, Center, @NamedTuple{time::Float64, last_Δt::Float64, last_stage_Δt::Float64, iteration::Int64, stage::Int64}, @NamedTuple{ĝ::Vector{Float64}, N²::Float64}, typeof(constant_stratification), RectilinearGrid{Float64, Periodic, Flat, Bounded, Oceananigans.Grids.StaticVerticalDiscretization{OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}, OffsetArrays.OffsetVector{Float64, CUDA.CuDeviceVector{Float64, 1}}}, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, Nothing, Nothing}, Float64} which is not isbits.
        .parameters is of type @NamedTuple{ĝ::Vector{Float64}, N²::Float64} which is not isbits.
          .ĝ is of type Vector{Float64} which is not isbits.


Only bitstypes, which are "plain data" types that are immutable
and contain no references to other values, can be used in GPU kernels.
For more information, see the `Base.isbitstype` function.
```

### PR DESCRIPTION
**Pull request by simone-silvestri**
probably good to not use vectors in example scripts because they go against our philosophy that "only the architecture should change to run on different backends"

closes #4438

### CODE REVIEW

**Review by tomchor — APPROVED** [review]
Are there performance benefits to tuples here?

**Comment by simone-silvestri** [comment]
I don't think so, I think the performance gain / loss would be quite negligible here. This change is just to address issue #4438  where @xiaozhour tried to change the example to make it run on the GPU and it was not immediate. 

I guess when it's ready, this PR will
close #4438

**Comment by simone-silvestri** [comment]
Then, we cannot fix all the problems related to plotting I guess...

File: examples/tilted_bottom_boundary_layer.jl [hunk 1]
```diff
@@ -71,28 +71,28 @@ current_figure() #hide
 # so that ``x`` is the along-slope direction, ``z`` is the across-slope direction that
 # is perpendicular to the bottom, and the unit vector anti-aligned with gravity is
 
-ĝ = (sind(θ), 0, cosd(θ))
+ẑ = (sind(θ), 0, cosd(θ))
```
Comment (tomchor) [inline examples/tilted_bottom_boundary_layer.jl:74]: Nice change of notation. This is more correct.
