### PR TITLE
Close advection scheme errors + tests

### LINKED ISSUE #5155: Bogus `Oceananigans.Advection.centered_reconstruction_weights` method
```julia-repl
julia> using Oceananigans

julia> Oceananigans.Advection.centered_reconstruction_weights(Float64, 1, 2, 3, 4, 5, 6)
ERROR: UndefVarError: `ε` not defined in `Oceananigans.Advection`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] centered_reconstruction_weights(FT::Type{Float64}, β₀::Int64, β₁::Int64, β₂::Int64, γ₀::Int64, γ₁::Int64, γ₂::Int64)
   @ Oceananigans.Advection ~/.julia/dev/Oceananigans/src/Advection/multi_dimensional_reconstruction.jl:56
```
https://github.com/CliMA/Oceananigans.jl/blob/478f45bdf95866018e82086bc021b8bfa9c98954/src/Advection/multi_dimensional_reconstruction.jl#L54-L58
When this method was introduced by @simone-silvestri in #3091 there was a constant `ε` https://github.com/CliMA/Oceananigans.jl/blob/ecb559fe9b84a76db514f8d26638abaef582aec4/src/Advection/weno_interpolants.jl#L69 but then it was renamed to `ϵ` by @glwagner in #4432.  This is easy to fix!

Detected with JETLS

### LINKED ISSUE #5156: Bogus methods `Oceananigans.Advection._multi_dimensional_reconstruction_x`/`Oceananigans.Advection._multi_dimensional_reconstruction_y`
https://github.com/CliMA/Oceananigans.jl/blob/478f45bdf95866018e82086bc021b8bfa9c98954/src/Advection/topologically_conditional_interpolation.jl#L125-L133 `outside_symmetric_bufferᶜ` is undefined.  Introduced by @simone-silvestri in #3091, but I haven't tracked where `outside_symmetric_bufferᶜ` was defined.

Detected with JETLS.

### LINKED ISSUE #5157: Bogus methods `Oceananigans.Advection.upwinded_divergence_flux_Uᶠᶜᶜ`/`Oceananigans.Advection.upwinded_divergence_flux_Vᶜᶠᶜ`
https://github.com/CliMA/Oceananigans.jl/blob/478f45bdf95866018e82086bc021b8bfa9c98954/src/Advection/vector_invariant_cross_upwinding.jl#L36-L54 `cross_scheme` is undefined in both methods.  Probably should be a field of `scheme` or something like that?  It was introduced by @simone-silvestri in #3956.

Detected with JETLS

### PR DESCRIPTION
**Pull request by simone-silvestri**
closes #5157, closes #5156, closes #5155

### CODE REVIEW

**Comment by simone-silvestri** [comment]
Oh my god this whitespace check 🤣

File: src/Advection/multi_dimensional_reconstruction.jl [hunk 1]
```diff
@@ -53,9 +53,9 @@ const a₂³ = (62 - 9*sqrt(15), -4 + 12*sqrt(15),  2 - 3 * sqrt(15)) ./ 60
 
 @inline function centered_reconstruction_weights(FT, β₀, β₁, β₂, γ₀, γ₁, γ₂)
 
-    α₀ = FT(γ₀) / (β₀ + FT(ε))^two_32
-    α₁ = FT(γ₁) / (β₁ + FT(ε))^two_32
-    α₂ = FT(γ₂) / (β₂ + FT(ε))^two_32
+    α₀ = FT(γ₀) / (β₀ + FT(ϵ))^two_32
```
Comment (navidcy) [inline src/Advection/multi_dimensional_reconstruction.jl:56]: where is ϵ being defined?

Comment (navidcy) [reply src/Advection/multi_dimensional_reconstruction.jl:56]: found it; https://github.com/CliMA/Oceananigans.jl/blob/a34cbaf41c0b0ff1d4c7d7eddf1dc5a4a595af66/src/Advection/weno_interpolants.jl#L71

**Review by giordano — APPROVED** [review]

File: src/Advection/multi_dimensional_reconstruction.jl (hunk 1 above)
Comment (giordano) [reply src/Advection/multi_dimensional_reconstruction.jl:56]: Yep, as mentioned in #5155 it was renamed in #4432.

File: test/test_hydrostatic_free_surface_models.jl [hunk 2]
```diff
@@ -273,14 +273,23 @@ topos_3d = ((Periodic, Periodic, Bounded),
             end
         end
 
-        for momentum_advection in (VectorInvariant(), WENOVectorInvariant(), Centered(), WENO())
+        momentum_advections = (
+            Centered(),
+            WENO(),
+            VectorInvariant(),
+            WENOVectorInvariant(),
+            WENOVectorInvariant(; upwinding = CrossAndSelfUpwinding(cross_scheme = WENO()))
```
Comment (giordano) [inline test/test_hydrostatic_free_surface_models.jl]:
```suggestion
            WENOVectorInvariant(; upwinding = CrossAndSelfUpwinding(cross_scheme = WENO())),
```

File: test/test_hydrostatic_free_surface_models.jl [hunk 3]
```diff
@@ -273,14 +273,23 @@ topos_3d = ((Periodic, Periodic, Bounded),
...
         end
 
-        for momentum_advection in (VectorInvariant(), WENOVectorInvariant(), Centered(), WENO())
+        momentum_advections = (
+            Centered(),
+            WENO(),
+            VectorInvariant(),
+            WENOVectorInvariant(),
+            WENOVectorInvariant(; upwinding = CrossAndSelfUpwinding(cross_scheme = WENO())),
+            WENOVectorInvariant(; multi_dimensional_stencil = true)
```
Comment (giordano) [inline test/test_hydrostatic_free_surface_models.jl]:
```suggestion
            WENOVectorInvariant(; multi_dimensional_stencil = true),
```

**Comment by navidcy** [comment]
Should we tag 0.104 after this PR?

File: test/test_hydrostatic_free_surface_models.jl [hunk 4]
```diff
@@ -273,14 +273,23 @@ topos_3d = ((Periodic, Periodic, Bounded),
...
+            Centered(),
+            WENO(),
+            VectorInvariant(),
+            WENOVectorInvariant(),
+            WENOVectorInvariant(; upwinding = CrossAndSelfUpwinding(cross_scheme = WENO())),
+            WENOVectorInvariant(; multi_dimensional_stencil = true),
+        )
+
+        for momentum_advection in momentum_advections
             @testset "Time-stepping HydrostaticFreeSurfaceModels [$arch, $(typeof(momentum_advection))]" begin
```
Comment (navidcy) [inline test/test_hydrostatic_free_surface_models.jl]: Would something like this be a bit more helpful?
Because atm, the types are huuuuuge

```suggestion
            @testset "Time-stepping HydrostaticFreeSurfaceModels [$arch, $(summary(momentum_advection))]" begin
```

Comment (navidcy) [reply test/test_hydrostatic_free_surface_models.jl]: Suggestion holds for many other places also in this tests file

**Comment by navidcy** [comment]
I could reproduce the failing test with the `WENOVectorInvariant(; multi_dimensional_stencil = true)` but I couldn't figure out a way to heal it.

@simone-silvestri/@giordano could you have a look?

**Comment by navidcy** [comment]
> I could reproduce the failing test with the `WENOVectorInvariant(; multi_dimensional_stencil = true)` but I couldn't figure out a way to heal it.
> 
> @simone-silvestri/@giordano could you have a look?

I think I figured it out; https://github.com/CliMA/Oceananigans.jl/pull/5158/commits/974caa3fc118f9947658b834ee8ecfcf58b6bfeb
