### PR TITLE
Fix Clock constructor preventing Nonhydrostatic model to run on MetalGPU

### LINKED ISSUE #5186: Nonhydrostatic model fails on MetalGPU due to Clock(::AbstractGrid) constructor
The constructor 
```Julia
 Clock(grid::AbstractGrid) = Clock{Float64}(time=0)
```  
in `clock.jl` prevents the Nonhydrostatic model from running on MetalGPU. This is fixed in an upcoming PR.

### PR DESCRIPTION
**Pull request by alesok**
This PR fixes issue #5186 related to 
```Julia
Clock(grid::AbstractGrid) = Clock{Float64}(time=0)
```

Closes #5186

### CODE REVIEW

File: test/test_metal.jl [hunk 1]
```diff
@@ -131,3 +131,17 @@ end
...
+
+    arch = GPU(Metal.MetalBackend());
+    grid = RectilinearGrid(arch; size=(64, 64, 16), x=(0, 5000), y=(0, 5000), z=(-20, 0))
+    @test eltype(grid) == Float32
+
+    model = NonhydrostaticModel(grid; advection=WENO(),
+                                pressure_solver=ConjugateGradientPoissonSolver(grid, maxiter=50),)
+    sim = Simulation(model, Δt=5, stop_iteration=20)
+    run!(sim)
+    @test time(sim) == 100seconds
```
Comment (simone-silvestri) [inline test/test_metal.jl]: Maybe you can run only for 2 iterations and use a smaller grid?

Comment (alesok) [reply test/test_metal.jl]: Good point! It was copied from previous test where several iterations are required

**Comment by glwagner** [comment]
are we using the CG pressure solver? Last I checked there were no FFTs on Metal, so nonhydrostatic will probably be slow

**Comment by alesok** [comment]
> are we using the CG pressure solver? Last I checked there were no FFTs on Metal, so nonhydrostatic will probably be slow

The default pressure solver does not work for me. I found that
```Julia
pressure_solver = ConjugateGradientPoissonSolver(grid, maxiter = 50)
```
works, although I am not sure how efficient it is.

I also confirmed that FFT support is not available on Metal (at least for me), and I was therefore unable to run the `NonhydrostaticModel` using `ImmersedBoundaryGrid`. But I believe that is a separate issue.

**Comment by glwagner** [comment]
> > are we using the CG pressure solver? Last I checked there were no FFTs on Metal, so nonhydrostatic will probably be slow
> 
> The default pressure solver does not work for me. I found that
> 
> ```julia
> pressure_solver = ConjugateGradientPoissonSolver(grid, maxiter = 50)
> ```
> 
> works, although I am not sure how efficient it is.

We should make this the default for MetalGPU. This should go in the extension.

**Comment by alesok** [comment]
OK, ConjugateGradientPoissonSolver is now the default for the nonhydrostatic model on Metal.

**Comment by navidcy** [comment]
Probably this issue is pertinent to all models? Not just the NonhydrostaticModel, right?

**Comment by alesok** [comment]
> Probably this issue is pertinent to all models? Not just the NonhydrostaticModel, right?

Yes, I think so. In case of the `NonhydrostaticModel`, the clock issue prevents the model from running, whereas the `HydrostaticFreeSurfaceModel` appears to be insensitive to it.

**Comment by alesok** [comment]
BTW, why do these two tests always fail for me? 
```
buildkite/oceananigans-distributed] — Build #12804 failed (12 seconds)
buildkite/oceananigans-distributed/pipeline — Failed (exit status 128)
```
Could this be an issue with my fork of Oceanangans? How to fix it?

**Comment by simone-silvestri** [comment]
yeah, forks do not have the permission to run the distributed tests. I am not sure if we can enable this.

File: test/test_metal.jl [hunk 2]
```diff
@@ -139,8 +139,7 @@ end
     grid = RectilinearGrid(arch; size=(32, 32, 8), x=(0, 5000), y=(0, 5000), z=(-20, 0))
     @test eltype(grid) == Float32
 
-    model = NonhydrostaticModel(grid; advection=WENO(),
-                                pressure_solver=ConjugateGradientPoissonSolver(grid, maxiter=50),)
+    model = NonhydrostaticModel(grid;)
```
Comment (glwagner) [inline test/test_metal.jl]:
```suggestion
    model = NonhydrostaticModel(grid)
```

**Comment by alesok** [comment]
> yeah, forks do not have the permission to run the distributed tests. I am not sure if we can enable this.

Thanks. Good to know that it is not my fault.

**Comment by alesok** [comment]
Please merge it!
