### PR TITLE
All-purpose `using Oceananigans`

### LINKED ISSUE #1075: Move `src/Utils/units.jl` to its own `Oceananigans.Units` submodule
> Is this for examples and docs? It does obviously read better; I'm not sure about the downside of name proliferation. Maybe we can stew on it and update in a future PR?

I was thinking both, i.e. encourage their use to improve script readability. Yeah we can just update things as we go along.

I guess the downside is that new users may not immediately notice that these common words, e.g. `minutes`, are actually being exported by `Oceananigans.Utils`. Perhaps if they were exported by a submodule like `Oceananigans.Units` that would be clearer. Also, newcomers to Julia may not realize that you can write things like `2π` or `3hours` but this should not stop us from using this nice language feature.

_Originally posted by @ali-ramadhan in https://github.com/CliMA/Oceananigans.jl/pull/1070#issuecomment-711026555_

### LINKED ISSUE #1131: Where to export schedules and output writers from?
Currently schedules are exported from `Oceananigans.Diagnostics` and `Oceananigans.OutputWriters` while being defined in `Oceananigans.Utils`.

I guess an inconsistency is that we export output writers from the top-level `Oceananigans` module so users can end up with access to output writers via `using Oceananigans` but without any schedules/intervals, leading to errors like

```
ERROR: LoadError: UndefVarError: TimeInterval not defined
```
cc @mukund-gupta @qwert2266

Might make sense to either export schedules at the top-level or stop exporting output writers at the top-level. Both seem like consistent solutions to me but I'll argue

### LINKED ISSUE #1132: Proposal to export the entire user interface at the top-level module
I think it would be to good to export the entire user interface at the top-level module so it's all fully available to the user with just `using Oceananigans`.

Some thoughts:
1. Would make it much easier to set up scripts. Many times I've found that users add something to their scripts, e.g. `AveragedField` or a `NetCDFOutputWriter`, and forget to add `using Oceananigans.Fields` or `using Oceananigans.OutputWriters`. It can be hard for a user to figure out exactly which import statement they're missing without consulting the docs (this could be considered a pain point).

2. Our current approach is not consistent either. The top level `Oceananigans` module exports a lot of the user interface but not all of it, so users are expected to import submodules but the submodules themselves export way more than just the user interface including functions that are not part of the user interface (example: https://github.com/CliMA/Oceananigans.jl/blob/master/src/Fields/Fields.jl).

3. I think we should export the entire user-interface at the top-level and be mindful of not exporting too much. Everything that gets exported at the top-level requires a docstring (this would allow us to enable strict checking for exported docstrings in `makedocs`: https://github.com/CliMA/Oceananigans.jl/blob/9026438047fe3e5d4805edcebe42560268dc65fb/docs/make.jl#L150).

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR ensures enough things are exported by Oceananigans that all the examples can get by with just `using Oceananigans`.

The purpose of this PR is to make the package more user friendly as missing names, e.g. `ComputedField`, have become a large source of errors for new users.

As this is a large change to the user interface, I've bumped v0.52.0.

Resolves #1075
Resolves #1131
Resolves #1132

### CODE REVIEW

**Comment by navidcy** [comment]
It's still failing... Should I have a look or wait?

**Comment by ali-ramadhan** [comment]
Ah I was just hoping it would pass on a Friday night haha. Think I was just missing a `using Oceananigans.Units` statement in one of the examples. Might pass now.

File: examples/convecting_plankton.jl [hunk 1]
```diff
@@ -45,15 +45,14 @@
 # We use a two-dimensional grid with 64² points and 1 m grid spacing:
 
 using Oceananigans
+using Oceananigans.Units
```
Comment (navidcy) [inline examples/convecting_plankton.jl:48]: Perhaps move this further down when first needed?

Comment (navidcy) [reply examples/convecting_plankton.jl:48]: Do we need a clarification about what does this import is used for?

File: examples/eady_turbulence.jl [hunk 2]
```diff
@@ -99,29 +99,31 @@
...
 # | ``κ_z``        | Laplacian vertical diffusivity | ``10^{-2}`` | ``\mathrm{m^2 s^{-1}}`` |
 # | ``ϰ_h``        | Biharmonic horizontal diffusivity | ``10^{-2} \times \Delta x^4 / \mathrm{day}`` | ``\mathrm{m^4 s^{-1}}`` |
 #
-# We start off by importing `Oceananigans`, `Printf`, and some convenient utils
-# for specifying dimensional constants:
+# We start off by importing `Oceananigans`, `Printf`, and some convenient constants
+# for specifying dimensional units:
 
-using Oceananigans, Oceananigans.Utils, Printf
+using Printf
```
Comment (navidcy) [inline examples/eady_turbulence.jl:120]: Do we need to add `Printf` in the "Install dependencies" section?

File: examples/langmuir_turbulence.jl [hunk 3]
```diff
@@ -176,16 +171,14 @@ set!(model, u=uᵢ, w=wᵢ, b=bᵢ)
...
-
 wizard = TimeStepWizard(cfl=1.0, Δt=45.0, max_change=1.1, max_Δt=1minute)
 
 # ### Nice progress messaging
 #
 # We define a function that prints a helpful message with
 # maximum absolute value of ``u, v, w`` and the current wall clock time.
 
-using Oceananigans.Diagnostics, Printf
+using Printf
```
Comment (navidcy) [inline examples/langmuir_turbulence.jl:181]: Again, do we need `Printf` in "Install dependencies"? Or does it come with basic Julia installation...? I'm not sure...

**Review by navidcy — APPROVED** [review]
Seems good to me! Only some minor remarks...

File: examples/convecting_plankton.jl (hunk 1 above)
Comment (glwagner) [reply examples/convecting_plankton.jl:48]: Maybe just making the names that are imported explicit:

```julia
using Oceananigans.Units: hour
```

File: examples/eady_turbulence.jl (hunk 2 above)
Comment (ali-ramadhan) [reply examples/eady_turbulence.jl:120]: Thankfully no since `Printf` is part of the standard library: https://docs.julialang.org/en/v1/stdlib/Printf/

Comment (glwagner) [reply examples/eady_turbulence.jl:120]: `Printf` is part of `Base` I think so doesn't need to be installed? `using Printf` seems to work for me on a clean environment.

File: examples/convecting_plankton.jl (hunk 1 above)
Comment (ali-ramadhan) [reply examples/convecting_plankton.jl:48]: Yes I can explicitly import the names used.

File: src/Oceananigans.jl [hunk 4]
```diff
@@ -40,8 +43,8 @@ export
     BuoyancyTracer, SeawaterBuoyancy,
     LinearEquationOfState, RoquetIdealizedNonlinearEquationOfState, TEOS10,
 
-    # Surface waves via Craik-Leibovich equations
-    StokesDrift,
+    # Stokes drift (surface waves) via Craik-Leibovich equations
```
Comment (glwagner) [inline src/Oceananigans.jl:46]:
```suggestion
    # Surface wave Stokes drift via Craik-Leibovich equations
```

**Review by glwagner — APPROVED** [review]
Beautiful <3
