### PR TITLE
Fix computation work layout for faces along bounded dimensions

### LINKED ISSUE #908: Computations do not compute the right end point faces of bounded dimensions
```julia
using Oceananigans, Oceananigans.Grids, Oceananigans.AbstractOperations

topo = (Bounded, Bounded, Bounded)
grid = RegularCartesianGrid(topology=topo, size=(4, 4, 4), extent=(1, 1, 1));
model = IncompressibleModel(grid=grid);

u, v, w = model.velocities;
u.data .= randn.();
v.data .= randn.();
w.data .= randn.();

op = @at (Face, Face, Face) u*v*w;
uvw = Field(Face, Face, Face, model.architecture, model.grid, TracerBoundaryConditions(grid));
c = Computation(op, uvw);
compute!(c);

interior(uvw)
```

```
5×5×5 view(OffsetArray(::Array{Float64,3}, 0:6, 0:6, 0:6), 1:5, 1:5, 1:5) with eltype Float64:
[:, :, 1] =
  0.0683322    0.00500681  -0.0153074   -0.00238774  0.0
 -0.129532    -0.185254    -0.17557     -0.0995522   0.0
  0.02045      0.00128018   0.0299081    0.0749603   0.0
  0.00156302  -0.083662    -0.00593719   0.0257051   0.0
  0.0          0.0          0.0          0.0         0.0

[:, :, 2] =
 -0.0383503   0.136722   -0.000743094  -0.0047771   0.0
 -0.0243957   0.252284    0.013428     -0.00964466  0.0
  0.039018   -0.0288018  -0.0143155     0.150052    0.0
  0.0138557   0.0755403   0.0399274     0.037416    0.0
  0.0         0.0         0.0           0.0         0.0

[:, :, 3] =
  0.0414805   -0.000303551   0.0478135    0.0102004  0.0
  0.173377    -0.0199285     0.0179786   -0.0126028  0.0
 -0.00506192   0.00439417   -0.0281433    0.0988586  0.0
 -0.236862     0.0271338    -0.00985813   0.22861    0.0
  0.0          0.0           0.0          0.0        0.0

[:, :, 4] =
 -0.186161    0.00448596   0.0206118    0.00503756  0.0
  0.283588    0.0864775   -0.00393267   0.0248125   0.0
 -0.159922   -0.110711     0.0208522    0.0136605   0.0
 -0.0489473   0.250635    -0.0116721   -0.120208    0.0
  0.0         0.0          0.0          0.0         0.0

[:, :, 5] =
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #908

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
No dispatch 😳

But no, looks good

File: src/Utils/kernel_launching.jl [hunk 1]
```diff
@@ -43,10 +44,17 @@ function work_layout(grid, dims; include_boundaries=false)
...
-        Nx′ = grid.Nx + (TX() isa Bounded)
-        Ny′ = grid.Ny + (TY() isa Bounded)
-        Nz′ = grid.Nz + (TZ() isa Bounded)
+        LX, LY, LZ = location
+
+        # Add an extra grid point for face-centered fields
+        # along bounded dimensions
+        Nx′ = Nx + (TX() isa Bounded) * (LX() isa Face)
+        Ny′ = Ny + (TY() isa Bounded) * (LY() isa Face)
+        Nz′ = Nz + (TZ() isa Bounded) * (LZ() isa Face)
```
Comment (glwagner) [inline src/Utils/kernel_launching.jl:57]: Attack of the Booleans

File: src/Utils/kernel_launching.jl [hunk 2]
```diff
@@ -43,10 +44,17 @@ function work_layout(grid, dims; include_boundaries=false)
...
 
     if include_boundaries
+        e = "include_boundaries kwarg requires the location kwarg to be specified"
+        isnothing(location) && throw(ArgumentError(e))
+
         TX, TY, TZ = topology(grid)
-        Nx′ = grid.Nx + (TX() isa Bounded)
-        Ny′ = grid.Ny + (TY() isa Bounded)
-        Nz′ = grid.Nz + (TZ() isa Bounded)
+        LX, LY, LZ = location
```
Comment (glwagner) [inline src/Utils/kernel_launching.jl:51]: can use `instantiate` from AbstractOperations (may want to move it to Utils)

File: src/Utils/kernel_launching.jl [hunk 3]
```diff
@@ -43,10 +44,17 @@ function work_layout(grid, dims; include_boundaries=false)
                     (Int(√MAX_THREADS_PER_BLOCK), Int(√MAX_THREADS_PER_BLOCK))
 
     if include_boundaries
+        e = "include_boundaries kwarg requires the location kwarg to be specified"
+        isnothing(location) && throw(ArgumentError(e))
```
Comment (glwagner) [inline src/Utils/kernel_launching.jl:48]: if you use `instantiate(location)` it will throw an error, which might be sufficient error checking for this non-exported function

**Review by glwagner — APPROVED** [review]
Design could be a little cleaner but since it works its ok.

**Comment by glwagner** [comment]
Hmm by the way `include_boundaries` is a slight misnomer --- with `include_boundaries=false` we still include the _left_ boundary, but not the _right_ boundaries. Maybe we could use `include_right_boundaries` to be totally specific and clear.

As for the dispatch, I believe something similar to what `total_length` does would be good:

https://github.com/CliMA/Oceananigans.jl/blob/6d349e1d85d61ff997f249881cd58232de865996/src/Grids/grid_utils.jl#L50

would be nice to have an analogous function `length` that doesn't include halos.

File: src/Utils/kernel_launching.jl (hunk 2 above)
Comment (ali-ramadhan) [reply src/Utils/kernel_launching.jl:51]: :+1:

File: src/Utils/kernel_launching.jl (hunk 3 above)
Comment (ali-ramadhan) [reply src/Utils/kernel_launching.jl:48]: Good point. Done.

File: src/Utils/kernel_launching.jl (hunk 1 above)
Comment (ali-ramadhan) [reply src/Utils/kernel_launching.jl:57]: I thought it was clever. Definitely not the worst use of boolean math ever haha.

**Comment by ali-ramadhan** [comment]
Thanks for the suggestions! I think the code is cleaner now. Will make sure tests pass and `git push`.

**Comment by glwagner** [comment]
@ali-ramadhan ready to merge?
