### PR TITLE
Fix a bug in the adapt of `PartialCellBottom`

### LINKED ISSUE #3681: `PartialCellBottom` needs to be adapted correctly for the GPU when using a `HydrostaticFreeSurfaceModel`
I know `PartialCellBottom` is unexported and therefore experimental but just opening an issue that it doesn't currently work on GPUs with `HydrostaticFreeSurfaceModel`. I believe it's an Adapt issue. It works with `NonhydrostaticModel`.

Might just be an issue with functions describing the bottom height. Probably an easy fix?

---

Minimal working example:

```julia
using Oceananigans
using Oceananigans.ImmersedBoundaries: PartialCellBottom

underlying_grid = RectilinearGrid(GPU(), topology=(Periodic, Flat, Bounded), size=(4, 4), x=(0, 1), z=(0, 1))
slope(x) = x
grid = ImmersedBoundaryGrid(underlying_grid, PartialCellBottom(slope))

model = HydrostaticFreeSurfaceModel(; grid)
time_step!(model, 1)
```

produces this error:

```
ERROR: type OffsetArray has no field data
Stacktrace:
  [1] getproperty
    @ .\Base.jl:37 [inlined]
  [2] adapt_structure(to::CUDA.KernelAdaptor, ib::PartialCellBottom{OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, Float64})
    @ Oceananigans.ImmersedBoundaries C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\ImmersedBoundaries\partial_cell_bottom.jl:80
  [3] adapt(to::CUDA.KernelAdaptor, x::PartialCellBottom{OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, Float64})
    @ Adapt C:\Users\Ali\.julia\packages\Adapt\7T9au\src\Adapt.jl:40
  [4] adapt_structure(to::CUDA.KernelAdaptor, ibg::ImmersedBoundaryGrid{Float64, Periodic, Flat, Bounded, RectilinearGrid{…}, PartialCellBottom{…}, Nothing, Nothing, Nothing})
    @ Oceananigans.ImmersedBoundaries C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\ImmersedBoundaries\ImmersedBoundaries.jl:146
  [5] adapt(to::CUDA.KernelAdaptor, x::ImmersedBoundaryGrid{Float64, Periodic, Flat, Bounded, RectilinearGrid{…}, PartialCellBottom{…}, Nothing, Nothing, Nothing})
    @ Adapt C:\Users\Ali\.julia\packages\Adapt\7T9au\src\Adapt.jl:40
  [6] cudaconvert(arg::ImmersedBoundaryGrid{Float64, Periodic, Flat, Bounded, RectilinearGrid{…}, PartialCellBottom{…}, Nothing, Nothing, Nothing})
    @ CUDA C:\Users\Ali\.julia\packages\CUDA\Tl08O\src\compiler\execution.jl:198
  [7] map
    @ .\tuple.jl:294 [inlined]
  [8] map(f::typeof(CUDA.cudaconvert), t::Tuple{…})
    @ Base .\tuple.jl:294
  [9] macro expansion
    @ C:\Users\Ali\.julia\packages\CUDA\Tl08O\src\compiler\execution.jl:110 [inlined]
 [10] (::KernelAbstractions.Kernel{…})(::ImmersedBoundaryGrid{…}, ::Vararg{…}; ndrange::Nothing, workgroupsize::Nothing)
    @ CUDA.CUDAKernels C:\Users\Ali\.julia\packages\CUDA\Tl08O\src\CUDAKernels.jl:103
 [11] (::KernelAbstractions.Kernel{…})(::ImmersedBoundaryGrid{…}, ::Vararg{…})
    @ CUDA.CUDAKernels C:\Users\Ali\.julia\packages\CUDA\Tl08O\src\CUDAKernels.jl:89
 [12] macro expansion
    @ C:\Users\Ali\.julia\packages\KernelAbstractions\MAxUm\src\extras\loopinfo.jl:26 [inlined]
 [13] iterate_split_explicit!(free_surface::SplitExplicitFreeSurface{…}, grid::ImmersedBoundaryGrid{…}, Δτᴮ::Float64, weights::NTuple{…}, ::Val{…})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Models\HydrostaticFreeSurfaceModels\split_explicit_free_surface_kernels.jl:402
 [14] #apply_regionally!#56
    @ C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Utils\multi_region_transformation.jl:121 [inlined]
 [15] apply_regionally!
    @ C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Utils\multi_region_transformation.jl:118 [inlined]
 [16] macro expansion
    @ C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Utils\multi_region_transformation.jl:233 [inlined]
 [17] macro expansion
    @ C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Models\HydrostaticFreeSurfaceModels\split_explicit_free_surface_kernels.jl:324 [inlined]
 [18] macro expansion
    @ C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Utils\multi_region_transformation.jl:250 [inlined]
 [19] split_explicit_free_surface_step!(free_surface::SplitExplicitFreeSurface{…}, model::HydrostaticFreeSurfaceModel{…}, Δt::Int64, χ::Float64)
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Models\HydrostaticFreeSurfaceModels\split_explicit_free_surface_kernels.jl:320
 [20] ab2_step_free_surface!
    @ C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Models\HydrostaticFreeSurfaceModels\split_explicit_free_surface_kernels.jl:291 [inlined]
 [21] ab2_step!(model::HydrostaticFreeSurfaceModel{…}, Δt::Int64)
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\Models\HydrostaticFreeSurfaceModels\hydrostatic_free_surface_ab2_step.jl:23
 [22] time_step!(model::HydrostaticFreeSurfaceModel{…}, Δt::Int64; callbacks::Vector{…}, euler::Bool, compute_tendencies::Bool)
    @ Oceananigans.TimeSteppers C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\TimeSteppers\quasi_adams_bashforth_2.jl:101
 [23] time_step!(model::HydrostaticFreeSurfaceModel{…}, Δt::Int64)
    @ Oceananigans.TimeSteppers C:\Users\Ali\Home\atdepth\ImmersedShapes.jl\dev\Oceananigans\src\TimeSteppers\quasi_adams_bashforth_2.jl:66
 [24] top-level scope
    @ REPL[17]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

---

Environment: I'm using Julia 1.10.4 and Oceananigans.jl 0.91.4.

### PR DESCRIPTION
**Pull request by simone-silvestri**
closes #3681

We can probably use this PR to add also a validation for the `PartialCellBottom` and the bug-fixes in the implementation.
What do people think?

cc @jm-c

### CODE REVIEW

**Comment by glwagner** [comment]
@ali-ramadhan

**Comment by glwagner** [comment]
> closes #3681
> 
> We can probably use this PR to add also a validation for the `PartialCellBottom` and the bug-fixes in the implementation. What do people think?
> 
> cc @jm-c

presumably we should always use `PartialCellBottom` in examples with bathymetry. Is there a reason to ever use `GridFittedBottom`?

**Comment by glwagner** [comment]
How does this PR change `adapt`?

File: src/ImmersedBoundaries/partial_cell_bottom.jl [hunk 1]
```diff
@@ -95,10 +95,13 @@ Criterion is h ≥ z - ϵ Δz
...
-    z = znode(i, j, k+1, underlying_grid, c, c, f)
-    h = @inbounds ib.bottom_height[i, j, 1]
-    return z ≤ h
+    # Face node below current cell
+    z  = znode(i, j, k, underlying_grid, c, c, f)
+    h  = @inbounds ib.bottom_height[i, j, 1]
+    ϵ  = ib.minimum_fractional_cell_height
+    # z + Δz is equal to the face above the current cell
+    Δz = Δzᶜᶜᶜ(i, j, k, ibg.underlying_grid)
+    return z + Δz * ϵ ≤ h
```
Comment (tomchor) [inline src/ImmersedBoundaries/partial_cell_bottom.jl:104]: Should we expect this change to fix the weird behaviors we were seeing in https://github.com/CliMA/Oceananigans.jl/discussions/3529 ?

cc @francispoulin

Comment (simone-silvestri) [reply src/ImmersedBoundaries/partial_cell_bottom.jl:104]: I am not sure, @jm-c is the author of this fix, and he said that with this fix the immersed boundary example did not NaN immediately but it still NaNed after a little bit so we believe there is more bugs to be squashed. You can try that example on this and see if it makes any difference. It will most likely change the solution.

Comment (francispoulin) [reply src/ImmersedBoundaries/partial_cell_bottom.jl:104]: I am happy to try the example from #3529 it on this branch, when you think it's ready for testing.

**Comment by glwagner** [comment]
What are we waiting for to merge this PR?

**Comment by simone-silvestri** [comment]
I guess to have the partial cells working properly, @jm-c was saying there is still some fixes to be done.

**Comment by glwagner** [comment]
The first thing maybe is to add a test that catches the bug.

**Comment by simone-silvestri** [comment]
This is the status of the internal_tide example on this PR, not producing NaNs anymore, but still not really working.

https://github.com/user-attachments/assets/08cb954e-5f91-45a7-9bb0-f4792770fee7

**Comment by ali-ramadhan** [comment]
@simone-silvestri I think another error has now come up with the original MWE in issue #3681. I tried the `main` branch and this branch on two different systems and I'm getting a different CUDA illegal memory access error. Since it's probably not related to this PR I'll open a new issue about it. I'm guessing something is out of bounds in a `@inbounds`. I'll try catching it with `--check-bounds=yes`.

MWE:

```julia
using Oceananigans
using Oceananigans.ImmersedBoundaries: PartialCellBottom

underlying_grid = RectilinearGrid(GPU(), topology=(Periodic, Flat, Bounded), size=(4, 4), x=(0, 1), z=(0, 1))
slope(x) = x
grid = ImmersedBoundaryGrid(underlying_grid, PartialCellBottom(slope))

model = HydrostaticFreeSurfaceModel(; grid)
```

Error:

```julia
ERROR: CUDA error: an illegal memory access was encountered (code 700, ERROR_ILLEGAL_ADDRESS)
Stacktrace:
  [1] throw_api_error(res::CUDA.cudaError_enum)
    @ CUDA ~/.julia/packages/CUDA/Tl08O/lib/cudadrv/libcuda.jl:30
  [2] check
    @ ~/.julia/packages/CUDA/Tl08O/lib/cudadrv/libcuda.jl:37 [inlined]
  [3] cuStreamGetCaptureInfo
    @ ~/.julia/packages/CUDA/Tl08O/lib/utils/call.jl:34 [inlined]
  [4] capture_status(stream::CUDA.CuStream)
    @ CUDA ~/.julia/packages/CUDA/Tl08O/lib/cudadrv/graph.jl:174
  [5] is_capturing
    @ ~/.julia/packages/CUDA/Tl08O/lib/cudadrv/graph.jl:179 [inlined]
  [6] convert(::Type{CUDA.CuPtr{Float64}}, managed::CUDA.Managed{CUDA.DeviceMemory})
    @ CUDA ~/.julia/packages/CUDA/Tl08O/src/memory.jl:539
  [7] unsafe_convert
    @ ~/.julia/packages/CUDA/Tl08O/src/array.jl:434 [inlined]
  [8] #pointer#1123
    @ ~/.julia/packages/CUDA/Tl08O/src/array.jl:392 [inlined]
  [9] pointer (repeats 2 times)
    @ ~/.julia/packages/CUDA/Tl08O/src/array.jl:384 [inlined]
 [10] unsafe_convert(::Type{CUDA.CuDeviceArray{Float64, 3, 1}}, a::CUDA.CuArray{Float64, 3, CUDA.DeviceMemory})
    @ CUDA ~/.julia/packages/CUDA/Tl08O/src/array.jl:454
 [11] adapt_storage
    @ ~/.julia/packages/CUDA/Tl08O/src/compiler/execution.jl:162 [inlined]
 [12] adapt_structure
    @ ~/.julia/packages/Adapt/7T9au/src/Adapt.jl:57 [inlined]
 [13] adapt
    @ ~/.julia/packages/Adapt/7T9au/src/Adapt.jl:40 [inlined]
 [14] #1
    @ ~/.julia/packages/OffsetArrays/hwmnB/ext/OffsetArraysAdaptExt.jl:9 [inlined]
 [15] parent_call
    @ ~/.julia/packages/OffsetArrays/hwmnB/src/OffsetArrays.jl:315 [inlined]
 [16] adapt_structure
    @ ~/.julia/packages/OffsetArrays/hwmnB/ext/OffsetArraysAdaptExt.jl:9 [inlined]
 [17] adapt
    @ ~/.julia/packages/Adapt/7T9au/src/Adapt.jl:40 [inlined]
 [18] cudaconvert
    @ ~/.julia/packages/CUDA/Tl08O/src/compiler/execution.jl:198 [inlined]
 [19] map
    @ ./tuple.jl:294 [inlined]
 [20] map(f::typeof(CUDA.cudaconvert), t::Tuple{KernelAbstractions.CompilerMetadata{…}, OffsetArrays.OffsetArray{…}, Nothing, Nothing, Tuple{…}, ImmersedBoundaryGrid{…}, Tuple{}})
    @ Base ./tuple.jl:294
 [21] macro expansion
    @ ~/.julia/packages/CUDA/Tl08O/src/compiler/execution.jl:110 [inlined]
 [22] (::KernelAbstractions.Kernel{…})(::OffsetArrays.OffsetArray{…}, ::Vararg{…}; ndrange::Nothing, workgroupsize::Nothing)
    @ CUDA.CUDAKernels ~/.julia/packages/CUDA/Tl08O/src/CUDAKernels.jl:103
 [23] (::KernelAbstractions.Kernel{CUDA.CUDAKernels.CUDABackend, KernelAbstractions.NDIteration.StaticSize{…}, KernelAbstractions.NDIteration.StaticSize{…}, typeof(Oceananigans.BoundaryConditions.gpu__no_fill!)})(::OffsetArrays.OffsetArray{Float64, 3, CUDA.CuArray{…}}, ::Vararg{Any})
    @ CUDA.CUDAKernels ~/.julia/packages/CUDA/Tl08O/src/CUDAKernels.jl:89
 [24] launch!(::GPU, ::ImmersedBoundaryGrid{…}, ::Tuple{…}, ::typeof(Oceananigans.BoundaryConditions._no_fill!), ::OffsetArrays.OffsetArray{…}, ::Vararg{…}; include_right_boundaries::Bool, reduced_dimensions::Tuple{}, location::Nothing, active_cells_map::Nothing, kwargs::@Kwargs{})
    @ Oceananigans.Utils /global/u1/a/alir/Oceananigans.jl/src/Utils/kernel_launching.jl:168
 [25] launch!
    @ /global/u1/a/alir/Oceananigans.jl/src/Utils/kernel_launching.jl:154 [inlined]
 [26] #fill_open_boundary_regions!#48
    @ /global/u1/a/alir/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions_open.jl:20 [inlined]
 [27] fill_open_boundary_regions!
    @ /global/u1/a/alir/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions_open.jl:9 [inlined]
 [28] fill_halo_regions!(::OffsetArrays.OffsetArray{…}, ::FieldBoundaryConditions{…}, ::Tuple{…}, ::Tuple{…}, ::ImmersedBoundaryGrid{…}; fill_boundary_normal_velocities::Bool, kwargs::@Kwargs{…})
    @ Oceananigans.BoundaryConditions /global/u1/a/alir/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions.jl:53
 [29] fill_halo_regions!
    @ /global/u1/a/alir/Oceananigans.jl/src/BoundaryConditions/fill_halo_regions.jl:48 [inlined]
 [30] #fill_halo_regions!#61
    @ /global/u1/a/alir/Oceananigans.jl/src/Fields/field.jl:773 [inlined]
 [31] fill_halo_regions!(::Field{Face, Center, Nothing, Nothing, ImmersedBoundaryGrid{…}, Tuple{…}, OffsetArrays.OffsetArray{…}, Float64, FieldBoundaryConditions{…}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{…}})
    @ Oceananigans.Fields /global/u1/a/alir/Oceananigans.jl/src/Fields/field.jl:770
 [32] fill_halo_regions!(::Tuple{Field{…}, Field{…}}; kwargs::@Kwargs{})
    @ Oceananigans.Fields /global/u1/a/alir/Oceananigans.jl/src/Fields/field_tuples.jl:64
 [33] fill_halo_regions!(::Tuple{Field{…}, Field{…}})
    @ Oceananigans.Fields /global/u1/a/alir/Oceananigans.jl/src/Fields/field_tuples.jl:56
 [34] Oceananigans.Models.HydrostaticFreeSurfaceModels.SplitExplicitAuxiliaryFields(grid::ImmersedBoundaryGrid{Float64, Periodic, Flat, Bounded, RectilinearGrid{…}, PartialCellBottom{…}, Nothing, Nothing, GPU})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels /global/u1/a/alir/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:239
 [35] materialize_free_surface(free_surface::SplitExplicitFreeSurface{…}, velocities::@NamedTuple{…}, grid::ImmersedBoundaryGrid{…})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels /global/u1/a/alir/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:121
 [36] HydrostaticFreeSurfaceModel(; grid::ImmersedBoundaryGrid{…}, clock::Clock{…}, momentum_advection::Centered{…}, tracer_advection::Centered{…}, buoyancy::Nothing, coriolis::Nothing, free_surface::SplitExplicitFreeSurface{…}, tracers::Nothing, forcing::@NamedTuple{}, closure::Nothing, boundary_conditions::@NamedTuple{}, particles::Nothing, biogeochemistry::Nothing, velocities::Nothing, pressure::Nothing, diffusivity_fields::Nothing, auxiliary_fields::@NamedTuple{})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels /global/u1/a/alir/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:177
 [37] top-level scope
    @ REPL[6]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by simone-silvestri** [comment]
Hmmm, I cannot reproduce it on the CPU with `--check-bounds=yes`. Perhaps it was fixed in the latest three commits?
https://github.com/CliMA/Oceananigans.jl/blob/0fd398613170ebb0c0b82b4e55b5bb6659373712/src/ImmersedBoundaries/partial_cell_bottom.jl#L155-L161

**Comment by ali-ramadhan** [comment]
I was able to reproduce on the CPU with `--check-bounds=yes` but on the `main` branch. Lemme try on this branch.

**Comment by ali-ramadhan** [comment]
Confirming that the MWE just above works on this branch on both CPU and GPU!

**Comment by ali-ramadhan** [comment]
Also confirming that my original MWE from #3681 also works on this branch now!

```julia
using Oceananigans
using Oceananigans.ImmersedBoundaries: PartialCellBottom

underlying_grid = RectilinearGrid(GPU(), topology=(Periodic, Flat, Bounded), size=(4, 4), x=(0, 1), z=(0, 1))
slope(x) = x
grid = ImmersedBoundaryGrid(underlying_grid, PartialCellBottom(slope))

model = HydrostaticFreeSurfaceModel(; grid)
time_step!(model, 1)
```

**Comment by glwagner** [comment]
What's keeping us from merging this? It fixes something so its a step forward, I think we should merge it.

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
I implemented the clamping from #3787 and it seems to have fixed the issue:

# GridFittedBottom

https://github.com/user-attachments/assets/1c6e4be4-ae80-42b3-9489-fe8edfb24d34

# PartialCellBottom

https://github.com/user-attachments/assets/91aa2bce-fd9e-4d74-b261-668b36cf786c

I'm not sure I really understand why it would make a difference. I'm wondering @simone-silvestri are you sure that your test was using this code?

Either way I see no reason not to merge this. Perhaps we will continue to find improvements for PartialCellBottom but I think this is ready to be used in an example. Note that in the internal tide case the partial cells have the interesting effect of weakening the vertical velocity. That could make sense if the topography is somehow "less effectively steep" than in the full cell case.

**Comment by glwagner** [comment]
This PR now supercedes #3787

**Comment by francispoulin** [comment]
Now we have merged, should I revisit #3529?

**Comment by glwagner** [comment]
It's a good idea! Also @apaloczy had some tests that might be good to try to re-run.

**Comment by glwagner** [comment]
I suspect it won't change anything though because this PR fixes a bug that affects when criteria about the minimum fractional cell height is met. I don't think that criteria is met in your example (which is good)
