### PR TITLE
Use r-based derivatives in diffusion operators

### LINKED ISSUE #5386: Immersed derivatives incorrectly call `underlying_grid` derivatives
The derivative on mutable immersed grids at the moment dispatch to the underlying grid. 

https://github.com/CliMA/Oceananigans.jl/blob/90bf00d160db1a4fe5db1312fb2a8c43cdd9d8cc/src/ImmersedBoundaries/mutable_immersed_grid.jl#L165-L200

This means that for mutable immersed grids we bypass the conditional check on the differences
https://github.com/CliMA/Oceananigans.jl/blob/90bf00d160db1a4fe5db1312fb2a8c43cdd9d8cc/src/ImmersedBoundaries/conditional_differences.jl#L70-L72

### PR DESCRIPTION
**Pull request by simone-silvestri**
This PR switches to using r-based derivatives in diffusion and GM/Redi operators. Also, it makes sure that the operators for immersed boundaries correctly account for immersed boundaries (see issue #5386).

The other option would be to build `∂xᶻ` and `∂yᶻ` for use in abstract operations.

closes #5386

### CODE REVIEW

File: src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl [hunk 1]
```diff
@@ -42,10 +42,10 @@ end
 
 # Slope in x-direction at F, C, F locations, zeroed out on peripheries
 @inline function Sxᶠᶜᶠ(i, j, k, grid, b, C)
-    bx = ℑzᵃᵃᶠ(i, j, k, grid, ∂x_b, b, C)
+    bx = ℑzᵃᵃᶠ(i, j, k, grid, ∂xᵣ_b, b, C)
     bz = ℑxᶠᵃᵃ(i, j, k, grid, ∂z_b, b, C)
-
-    Sx = ifelse(bz == 0, zero(grid), - bx / bz)
+    Sg = ∂x_zᶠᶜᶠ(i, j, k, grid)
```
Comment (glwagner) [inline src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl]: what does "Sg" mean?

Comment (simone-silvestri) [reply src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl]: It's the slope of the grid itself, it takes into account the additional sloping coming from the non-uniform vertical coordinate.

Comment (glwagner) [reply src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl]: But we already have a notation for it, `∂x_z`. I don't think we should introduce a new notation for the same thing.

**Comment by simone-silvestri** [comment]
This PR is ready for review

File: src/Operators/derivative_operators.jl [hunk 2]
```diff
@@ -92,3 +92,19 @@ for dir in (:x, :y, :z), LX in (:ᶜ, :ᶠ, :ᵃ), LY in (:ᶜ, :ᶠ, :ᵃ), LZ
...
+@inline ∂x_zᶠᶠᶜ(i, j, k, grid) = zero(grid)
+@inline ∂x_zᶜᶜᶠ(i, j, k, grid) = zero(grid)
+
+# y-direction slopes at different staggerings
+@inline ∂y_zᶜᶠᶜ(i, j, k, grid) = zero(grid)
+@inline ∂y_zᶜᶜᶜ(i, j, k, grid) = zero(grid)
+@inline ∂y_zᶜᶠᶠ(i, j, k, grid) = zero(grid)
+@inline ∂y_zᶠᶜᶜ(i, j, k, grid) = zero(grid)
+@inline ∂y_zᶠᶠᶜ(i, j, k, grid) = zero(grid)
+@inline ∂y_zᶜᶜᶠ(i, j, k, grid) = zero(grid)
```
Comment (tomchor) [inline src/Operators/derivative_operators.jl:110]: I know I've had this discussion before and I'm always on the minority, but are these fallbacks necessary? Isn't it better to let cases actually fail when we encounter some situation we didn't envision than to silently generate zeros?

In the past one of the reasons for these fallbacks was that it decreased the amount of code we had to write, but these days we're not manually writing code anymore...

File: src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl [hunk 3]
```diff
@@ -42,10 +42,10 @@ end
...
 # Slope in x-direction at F, C, F locations, zeroed out on peripheries
 @inline function Sxᶠᶜᶠ(i, j, k, grid, b, C)
-    bx = ℑzᵃᵃᶠ(i, j, k, grid, ∂x_b, b, C)
-    bz = ℑxᶠᵃᵃ(i, j, k, grid, ∂z_b, b, C)
-
-    Sx = ifelse(bz == 0, zero(grid), - bx / bz)
+    bx   = ℑzᵃᵃᶠ(i, j, k, grid, ∂xᵣ_b, b, C)
+    bz   = ℑxᶠᵃᵃ(i, j, k, grid, ∂z_b, b, C)
+    ∂x_z = ∂x_zᶠᶜᶠ(i, j, k, grid)
+    Sx   = ifelse(bz == 0, ∂x_z, - bx / bz + ∂x_z)
```
Comment (tomchor) [inline src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl:48]: Is there a reason for this extra white space here? (same for the code below)

```suggestion
    bx = ℑzᵃᵃᶠ(i, j, k, grid, ∂xᵣ_b, b, C)
    bz = ℑxᶠᵃᵃ(i, j, k, grid, ∂z_b, b, C)
    ∂x_z = ∂x_zᶠᶜᶠ(i, j, k, grid)
    Sx = ifelse(bz == 0, ∂x_z, - bx / bz + ∂x_z)
```

File: src/Operators/derivative_operators.jl (hunk 2 above)
Comment (glwagner) [reply src/Operators/derivative_operators.jl:110]: These are correct. We don't want them to fail because that has the potential to break a lot of code.

File: src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl (hunk 3 above)
Comment (glwagner) [reply src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl:48]: the `=` are aligned

File: src/Operators/derivative_operators.jl (hunk 2 above)
Comment (tomchor) [reply src/Operators/derivative_operators.jl:110]: I understand they can break a lot of code, but that's kind of my point. In the past I've spent many hours trying to figure out why a script wasn't giving me the expected result only to eventually find out that it was doing the wrong thing because a blank fallback was being used. Having my code fail would have saved me a lot of time. Admittedly that hasn't happened in a while, but I still think it's something to try and avoid.

I'll mark this as resolved and won't push it, since I'm always in the minority in this issue, but I just wanted to leave my reasons.

Comment (glwagner) [reply src/Operators/derivative_operators.jl:110]: Maybe not being clear. It will break code that we need to work. We have to have these operators in code on static grids (eg one algorithm for all)

**Comment by simone-silvestri** [comment]
This should be ready to merge @glwagner @navidcy
