### PR TITLE
Revisit `SplitExplicitFreeSurface` user-interface and Docs + use `SplitExplicitFreeSurface` as the default when appropriate

### LINKED ISSUE #3238: Some issue(s) with `SplitExplicitFreeSurface`
So initially I was trying to use the `SplitExplicitFreeSurface` with the adaptive barotropic step based on CFL.

This:

```Julia
using Oceananigans

grid = RectilinearGrid(size = (10, 10), x = (-100, 100), z = (-100, 0), topology = (Periodic, Flat, Bounded))

free_surface = SplitExplicitFreeSurface(; grid, cfl = 0.7)
```

errors

```Julia
ERROR: ArgumentError: either specify a cfl or a number of substeps
Stacktrace:
 [1] Oceananigans.Models.HydrostaticFreeSurfaceModels.SplitExplicitSettings(FT::DataType; substeps::Int64, cfl::Float64, grid::RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, fixed_Δt::Nothing, gravitational_acceleration::Float64, averaging_kernel::Function, timestepper::Oceananigans.Models.HydrostaticFreeSurfaceModels.ForwardBackwardScheme)
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/pbNSE/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:306
 [2] SplitExplicitFreeSurface(FT::DataType; gravitational_acceleration::Float64, kwargs::Base.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:grid, :cfl), Tuple{RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Float64}}})
   @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/pbNSE/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:74
 [3] top-level scope
   @ REPL[10]:1
```

I figured that the error was because `substeps` has a default value so when I also prescribe a `cfl` kwarg then 

https://github.com/CliMA/Oceananigans.jl/blob/29a99a0c235b2f6bf0cec525f2249125ad254ccc/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl#L306

gets triggered. A solution was to add `substeps = nothing`. This is a bit counter-intuitive though. Is this the best way forward? Perhaps we should add a note in the dostring....

However, I got another error down the road. Running this:

```Julia
using Oceananigans

grid = RectilinearGrid(size = (10, 10), x = (-100, 100), z = (-100, 0), topology = (Periodic, Flat, Bounded))
								  
free_surface = SplitExplicitFreeSurface(; grid, cfl = 0.7, substeps = nothing)

model = HydrostaticFreeSurfaceModel(; grid, free_surface,
                                    buoyancy = BuoyancyTracer(),
                                    tracers = :b,
                                    momentum_advection = WENO(),
                                    tracer_advection = WENO())

simulation = Simulation(model, Δt=10, stop_time=3600)

run!(simulation)
```

spits out 

```julia
ERROR: LoadError: UndefVarError: `settings` not defined
Stacktrace:
  [1] calculate_substeps
    @ ~/.julia/packages/Oceananigans/pbNSE/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl:324 [inlined]
  [2] iterate_split_explicit!(free_surface::SplitExplicitFreeSurface{Field{Center, Center, Face, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, UnitRange{Int64}}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}, Oceananigans.Models.HydrostaticFreeSurfaceModels.SplitExplicitState{Field{Center, Center, Face, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, UnitRange{Int64}}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}, Field{Face, Center, Nothing, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}, Field{Center, Face, Nothing, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}}, Oceananigans.Models.HydrostaticFreeSurfaceModels.SplitExplicitAuxiliaryFields{Field{Center, Face, Nothing, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}, Field{Face, Center, Nothing, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}, Field{Center, Center, Nothing, Nothing, RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Tuple{Colon, Colon, Colon}, OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, Float64, FieldBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, BoundaryCondition{Oceananigans.BoundaryConditions.Periodic, Nothing}, Nothing, Nothing, Nothing, Nothing, BoundaryCondition{Oceananigans.BoundaryConditions.Flux, Nothing}}, Nothing, Oceananigans.Fields.FieldBoundaryBuffers{Nothing, Nothing, Nothing, Nothing}}, Symbol, Tuple{Int64, Int64}}, Float64, Oceananigans.Models.HydrostaticFreeSurfaceModels.SplitExplicitSettings{Oceananigans.Models.HydrostaticFreeSurfaceModels.FixedTimeStepSize{Float64, typeof(Oceananigans.Models.HydrostaticFreeSurfaceModels.averaging_shape_function)}, Oceananigans.Models.HydrostaticFreeSurfaceModels.ForwardBackwardScheme}}, grid::RectilinearGrid{Float64, Periodic, Flat, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Δt::Float64)
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/pbNSE/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl:339

...

 [15] top-level scope
    @ ~/Research/mean_flow_test/mwe.jl:15
 [16] include(fname::String)
    @ Base.MainInclude ./client.jl:478
 [17] top-level scope
    @ REPL[1]:1
in expression starting at /Users/navid/Research/mean_flow_test/mwe.jl:15
```

I believe this is due to a bug here

https://github.com/CliMA/Oceananigans.jl/blob/29a99a0c235b2f6bf0cec525f2249125ad254ccc/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl#L324

since `settings` is not given to `calculate_substeps`.

cc @djlikesdjs

### LINKED ISSUE #3289: Default free surface solver: `SplitExplicit` or `Implicit`
I noticed that the default free surface model is different than what the docstring says:
https://github.com/CliMA/Oceananigans.jl/blob/e16cdc6cfb67703df9e29368017868331f68b1c0/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L59

vs

https://github.com/CliMA/Oceananigans.jl/blob/e16cdc6cfb67703df9e29368017868331f68b1c0/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L103

I'm not sure which it is meant to be

### PR DESCRIPTION
**Pull request by navidcy**
The PR revisits a bit the `SplitExplicitFreeSurface` user-interface and internals and changes the `HydrostaticFreeSurfaceModel` constructor to use the `SplitExplicitFreeSurface` as the default when the grid is appropriate, i.e., all the time except when `grid` is horizontally-regular rectilinear grid.

Furthermore, the PR cleans up a bit the free surface  constructions. Now all free surfaces have an "outer constructor" and then they get materialized via `materialize_free_surface` within the `HydrostaticFreeSurfaceModel` constructor.

Closes #3289
Closes #3238

### CODE REVIEW

**Comment by francispoulin** [comment]
Sounds like a good idea to me!

Is it worth having a brief comment as to the motivation of this switch, for the historical record?

File: src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl [hunk 1]
```diff
@@ -99,7 +99,7 @@ function HydrostaticFreeSurfaceModel(; grid,
                                   tracer_advection = CenteredSecondOrder(),
                                           buoyancy = SeawaterBuoyancy(eltype(grid)),
                                           coriolis = nothing,
-                                      free_surface = ImplicitFreeSurface(gravitational_acceleration = g_Earth),
+                                      free_surface = SplitExplicitFreeSurface(; grid, cfl = 0.7),
```
Comment (glwagner) [inline src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:102]: while we are at it we could finally make `grid` a positional arg

Comment (glwagner) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:102]: in summary I'm wondering if we should write this

```julia
free_surface = default_free_surface(grid)
```

and have

```julia
default_free_surface(grid) = SplitExplicitFreeSurface(; grid, cfl = 0.7)
default_free_surface(::RectilinearGrid) = # fft based free surface
```

Don't we need to specify the gravitational acceleration for split-explicit?

Comment (simone-silvestri) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:102]: we could use this constructor
https://github.com/CliMA/Oceananigans.jl/blob/77ee4980a32d39d802fc6c7b2a8ef81b4c6c0c1a/src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl#L92-L101

and add the grid as a `kwarg` of `SplitExplicitSettings`

Comment (glwagner) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:102]: ah yes, and what about `cfl`?

Comment (simone-silvestri) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:102]: or probably just remove `settings` as a `kwarg` but do something more on this line 
```julia
 function SplitExplicitFreeSurface(grid; gravitational_acceleration = g_Earth, kwargs...)
     settings = SplitExplicitSettings(eltype(grid); grid, gravitational_acceleration, kwargs...)) 
  
     Nz = size(grid, 3) 
     η  = ZFaceField(grid, indices = (:, :, Nz+1)) 
     gravitational_acceleration = convert(eltype(grid), gravitational_acceleration) 
  
     return SplitExplicitFreeSurface(η, SplitExplicitState(grid, settings.timestepper), SplitExplicitAuxiliaryFields(grid), 
            gravitational_acceleration, settings) 
 end 
```

Comment (glwagner) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:102]: (plus also making the state and auxiliary fields on new lines)

Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl]: I think I did all of these suggestions

**Comment by navidcy** [comment]
I bet some regressions tests will fail because their default free surface solver changed...

File: src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl [hunk 2]
```diff
@@ -75,30 +77,34 @@ References
 
 Shchepetkin, A. F., & McWilliams, J. C. (2005). The regional oceanic modeling system (ROMS): a split-explicit, free-surface, topography-following-coordinate oceanic model. Ocean Modelling, 9(4), 347-404.
 """
-SplitExplicitFreeSurface(FT::DataType = Float64; gravitational_acceleration = g_Earth, kwargs...) = 
-    SplitExplicitFreeSurface(nothing, nothing, nothing, convert(FT, gravitational_acceleration),
-                             SplitExplicitSettings(FT; gravitational_acceleration, kwargs...))
-                             
+function SplitExplicitFreeSurface(grid;
```
Comment (simone-silvestri) [inline src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:80]: so now it is not possible anymore to call
`SpliExplicitFreeSurface()`?

Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:80]: You need to provide a grid. Is this a problem?

Comment (simone-silvestri) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:80]: I guess it's ok. For the other free surfaces we do not provide a grid but "regularize" with a grid in the model constructor. I see two options: (1) all free surfaces are regularized in the model (2) all free surfaces accept grid as an argument. I am ok with both.

Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:80]: Can you point to an example of such regularization? Is it this, for example?

https://github.com/CliMA/Oceananigans.jl/blob/adc63328085687a1908f1c96850aa106311c0d0e/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl#L172

Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:80]: The thing is that SplitExplicit requires grid (in some case, e.g., when cfl is provided); other free surfaces don't require it ever, right?

Comment (simone-silvestri) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:80]: yep. For example, the `ImplicitFreeSurface` is regularized with the method and the grid. So that the `ImplicitFreeSurface` is empty at construction and gets filled in with the correct eta, implicit solver etc at construction. The same for `ExplicitFreeSurface`.

**Comment by navidcy** [comment]
ok, @simone-silvestri, I did what you were suggesting.
we now need to refactor the tests....... oh dear........

**Comment by navidcy** [comment]
This is ready I believe!!

File: src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl (hunk 2 above)
Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl]: Done. I did (1) from what you suggested @simone-silvestri

File: src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl [hunk 3]
```diff
@@ -27,38 +27,46 @@ struct SplitExplicitFreeSurface{𝒩, 𝒮, ℱ, 𝒫 ,ℰ} <: AbstractFreeSurfa
...
 
-- `fixed_Δt`: The maximum baroclinic timestep allowed. If `fixed_Δt` is a `nothing` and a cfl is provided, then
-              the number of substeps will be computed on the fly from the baroclinic time step to maintain a constant cfl.
-
-- `gravitational_acceleration`: the gravitational acceleration (default: `g_Earth`)
+- `fixed_Δt`: The maximum baroclinic timestep allowed. If `fixed_Δt` is a `nothing` and a cfl is provided,
+              then the number of substeps will be computed on the fly from the baroclinic time step to
+              maintain a constant cfl.
 
 - `averaging_kernel`: function of `τ` used to average the barotropic transport `U` and free surface `η`
```
[the remark this answers is not in the document]
Comment (navidcy) [reply src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl]: I added a bit more clarifications

**Review by simone-silvestri — APPROVED** [review]
nice

**Comment by navidcy** [comment]
Can you help me a bit here?

There is this error from the `mask_immersed_field!`:

https://buildkite.com/clima/oceananigans/builds/14988#018e3cf8-4e46-4915-a961-5065db6b172a/24-615

which I can't seem to know how to track down.

File: src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl [hunk 4]
```diff
@@ -60,6 +61,8 @@ Keyword Arguments
 
 !!! info "Needed keyword arguments"
     Either `substeps` _or_ `cfl` need to be prescribed.
+    
+    When `clf` is prescribed then `grid` is also required as a positional argument.
```
Comment (glwagner) [inline src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:65]:
```suggestion
    When `cfl` is prescribed then `grid` is also required as a positional argument.
```

**Comment by glwagner** [comment]
@navidcy it's probably related to this:

https://github.com/CliMA/Oceananigans.jl/blob/22c3aafd4aa9b5812c24dd060a4f4ab57d113a3a/src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl#L55-L67

where we use a special "xy" function for the free surface. When that `if` statement fails, we call the wrong `mask_immersed_field`.

Probably that code can be improved so that it's more robust, or to throw a more obvious error.

**Comment by glwagner** [comment]
The design is poor. We shouldn't rely on a MethodError here. There's an inconsistency: we have

https://github.com/CliMA/Oceananigans.jl/blob/22c3aafd4aa9b5812c24dd060a4f4ab57d113a3a/src/ImmersedBoundaries/mask_immersed_field.jl#L10-L11

which dispatches on `Field` (that's why it doesn't work for `FunctionField` as in the buildkite error). But for the _xy version,

https://github.com/CliMA/Oceananigans.jl/blob/22c3aafd4aa9b5812c24dd060a4f4ab57d113a3a/src/ImmersedBoundaries/mask_immersed_field.jl#L33-L34

we don't dispatch on `Field`. That's why you can call `mask_immersed_field_xy!(::FunctionField)`, but you can't call `mask_immersed_field!(::FunctionField)`.

I don't really get it... @simone-silvestri can you explain.

**Comment by simone-silvestri** [comment]
hmmm, I am not sure. What does `mask_immersed_field!` mean for a `FunctionField`? 
We probably need to specialize `mask_immersed_field_xy!` for  `Field`s only and add a fallback for `mask_immersed_field!`
```julia 
mask_immersed_field!(field, args...; kw...) = nothing
```
why was the wrong mask called in the update?

**Comment by navidcy** [comment]
What should be the default free surface solver for a MultiRegionGrid? Implicit?...

**Comment by simone-silvestri** [comment]
The default now it `Implicit` right? I think `SplitExplicit` will be more efficient. `Implicit` is done on only one GPU while split explicit takes advantage of all the workers

File: src/MultiRegion/multi_region_split_explicit_free_surface.jl [hunk 5]
```diff
@@ -40,11 +40,12 @@ end
 @inline augmented_kernel_offsets(grid, ::YPartition) = (0, - halo_size(grid)[2] + 1)
 @inline augmented_kernel_offsets(grid, ::CubedSpherePartition) = (- halo_size(grid)[2] + 1, - halo_size(grid)[2] + 1)
 
-function FreeSurface(free_surface::SplitExplicitFreeSurface, velocities, grid::MultiRegionGrids)
+# Internal function for HydrostaticFreeSurfaceModel
+function materialize_free_surface(free_surface::SplitExplicitFreeSurface, velocities, grid::MultiRegionGrids)
```
Comment (navidcy) [inline src/MultiRegion/multi_region_split_explicit_free_surface.jl:44]: This method is broken (already broken on `main` that is) and not used in tests. Should we delete it? Seems like we don't support `SplitExplicitFreeSurface` on `MultiRegionGrids` quite yet... Perhaps we replace it with an informative error?

**Comment by navidcy** [comment]
> The default now it `Implicit` right? I think `SplitExplicit` will be more efficient. `Implicit` is done on only one GPU while split explicit takes advantage of all the workers

I'm getting some errors with SplitExplicit + MultiRegionGrid. I'm trying to fix them... if I don't manage I'll leave Implicit as the default and open an issue.

**Comment by navidcy** [comment]
@simone-silvestri 

this

https://github.com/CliMA/Oceananigans.jl/blob/833e2b8e532ad5cf3244d6d1bffafa4004b5b756/src/MultiRegion/multi_region_split_explicit_free_surface.jl#L52

won't work when we provide cfl, i.e., `SplitExplicitFreeSurface(grid, cfl=0.7)`

We basically want a way to compute the number of `Nsubsteps` for `FixedTimeStepSize` which I presume it's not possible until we know the baroclinic timestep, right?

Thus, for MultiRegion / Distributed do we only support `FixedSubstepNumber`??

**Comment by navidcy** [comment]
Actually it started coming back to me as a previous discussion we might have had… :)

**Comment by navidcy** [comment]
I decided to merge and fix the SplitExplicit on MultiRegionGrids elsewhere; see https://github.com/CliMA/Oceananigans.jl/issues/3513 and https://github.com/CliMA/Oceananigans.jl/issues/3514
